using System.Collections.Generic;

namespace CaptainSkillTree.Localization
{
    public static partial class DefaultLanguages
    {
        private static Dictionary<string, string> GetEnglish_JobExpert()
        {
            return new Dictionary<string, string>
            {
                // === Archer Job ===
                ["archer_desc_multishot_fallback"] = "Fires 5 arrows x2 times.",
                ["archer_desc_arrow_damage_fallback"] = "Each arrow deals 50% of bow+arrow damage",
                ["archer_passive_skills"] = "Jump height +{0}%, Fall damage -{1}%",
                ["archer_passive_lv1"] = "Jump +{0}%, Fall -{1}%, Atk Stamina -{2}%, Arrow/Bolt {3}% no-consume",
                ["archer_passive_lv2"] = "Jump +{0}%, Poison Resist +{1}%, Atk Stamina -{2}%, Arrow/Bolt {3}% no-consume",
                ["archer_passive_lv3"] = "Jump +{0}%, Fall -{1}%, Poison/Cold Resist +{2}%, Atk Stamina -{3}%, Arrow/Bolt {4}% no-consume",
                ["archer_passive_lv4"] = "Jump +{0}%, Fall -{1}%, Poison/Cold/Fire Resist +{2}%, Atk Stamina -{3}%, Arrow/Bolt {4}% no-consume",
                ["archer_passive_lv5"] = "Jump +{0}%, Fall -{1}%, All Elem Resist +{2}%, Atk Stamina -{3}%, Arrow/Bolt {4}% no-consume",
                ["requirement_archer"] = "Bow equipped, Archer job",
                ["archer_current_level"] = "Current Level",
                ["archer_max_level"] = "★ Max Level Reached",
                ["archer_next_level_cost"] = "Lv{0} Upgrade Materials",
                ["archer_effect_arrows"] = "Fire {0} arrows x{1}, each deals {2}% damage",
                ["archer_level_item_required"] = "Not enough materials for Archer Lv{0} upgrade",
                ["producer_level_item_required"] = "Not enough trophies for Producer Lv{0} advancement",
                ["archer_upgrade_confirm"] = "Upgrade Archer to Lv{0}?",
                ["archer_missing_items"] = "Missing: {0}",
                ["rogue_upgrade_title"] = "⚔️ Rogue Class Ascension",
                ["rogue_upgrade_confirm"] = "Upgrade Rogue to Lv{0}?",
                ["rogue_missing_items"] = "Missing: {0}",
                ["item_trophy_skeleton"] = "Skeleton Trophy",
                ["item_trophy_greydwarf"] = "Greydwarf Trophy",
                ["item_trophy_greydwarfbrute"] = "Greydwarf Brute Trophy",
                ["item_trophy_greydwarfshaman"] = "Greydwarf Shaman Trophy",
                ["item_trophy_troll"] = "Troll Trophy",
                ["item_trophy_elder"] = "The Elder Trophy",
                ["item_trophy_abomination"] = "Abomination Trophy",
                ["item_trophy_bonemass"] = "Bonemass Trophy",
                ["item_trophy_hatchling"] = "Drake Trophy",
                ["item_trophy_dragonqueen"] = "Moder Trophy",
                ["item_trophy_goblinking"] = "Yagluth Trophy",
                ["item_trophy_thequeen"] = "The Queen Trophy",
                ["item_trophy_frosttroll"] = "Frost Troll Trophy",
                ["item_trophy_seekerqueen"] = "Seeker Queen Trophy",

                // === Tanker Job ===
                ["tanker_skill_warcry"] = "War Cry",
                ["tanker_desc_warcry"] = "Taunt enemies in {0}m range for {1}s (boss {2}s), caster gets {4}% damage reduction for {3}s",
                ["tanker_desc_warcry_fallback"] = "Taunt enemies for 5s (boss 1s), caster gets 20% damage reduction for 5s",
                ["tanker_skill_type_taunt"] = "Active Taunt Skill - Y Key",
                ["tanker_passive_damage_reduction"] = "Damage taken -{0}%",
                ["tanker_reflect_activated"] = "🛡️ Rage Accumulation started!",
                ["tanker_reflect_damage"] = "🛡️ Taunt Reflect: {0}",
                ["tanker_reflect_info"] = "On buff end: {0}% of accumulated damage as fire explosion ({1}m)",
                ["tanker_reflect_explosion"] = "🔥 Rage Explosion: {0} x{1} enemies",

                // === Berserker Job ===
                ["berserker_skill_rage"] = "Berserker Rage",
                ["berserker_desc_rage"] = "Activate rage state for {0}s with powerful attack boost",
                ["berserker_desc_rage_detail"] = "+{0}% damage per 1% health lost, max +{1}%",
                ["berserker_ranged_30pct"] = "(30% effectiveness for ranged attacks)",
                ["berserker_rage_effect"] = "Rage Effect",
                ["berserker_rage_damage_per_health"] = "+{0}% damage per 1% health lost",
                ["berserker_passive_desc"] = "Stamina regen +20%, Max HP +{3}%, Invincible for {1}s when health below {0}% (cooldown {2}min)",
                ["berserker_not_in_rage"] = "Not in rage state",
                ["berserker_current_status"] = "Current health: {0}%\nCurrent damage bonus: +{1}%\nRage state: Active",
                ["berserker_simulation_title"] = "Damage bonus by health:",
                ["berserker_simulation_line"] = "Health {0}%: +{1}% damage",
                ["berserker_simulation_max"] = "Max limit: +{0}%",
                ["berserker_default_tooltip"] = "Description:\n[Active Skill - Y Key]\n+2% damage per -1% health for 20s, stronger at lower health\n\n[Passive Skill]\n• Stamina regen +20% (always active)\n• 7s invincibility when health below 10% (300s cooldown)\n\nAdditional: Max +200% damage limit, red/gold aura effect\nRange: Self\nCost: Stamina 20 (active only)\nCooldown: 45s (active), 300s (passive)\nRequirement: Berserker job\nNotice: Only one job can be selected, Lv 10+\nRequired Item: Ancient Bark Spear",
                ["requirement_job_berserker"] = "Berserker job",

                // === Berserker Lv1~5 Level-Up System ===
                ["berserker_upgrade_msg"] = "Berserker Lv{0} Reached!",
                ["berserker_active_desc"] = "Rage: {0}s CD, {1}s duration, max+{2}%, {3}% per 1% HP lost",
                ["berserker_passive_lv1"] = "Death Defiance: HP+{0}, Stamina regen+20%, Invincible {2}s when below {1}% HP ({3}min CD)",
                ["berserker_passive_lv2"] = "HP+{0}, Lv1 + Fury Hammer/Rush Slash/Pierce Charge: 1 extra use in 30s",
                ["berserker_passive_lv3"] = "HP+{0}, Lv2 + Damage received during rage -{4}%",
                ["berserker_passive_lv4"] = "HP+{0}, Lv3 + Attack+{5}% when HP below {6}%",
                ["berserker_passive_lv5"] = "HP+{0}, Lv4 + Death Defiance enhanced (CD -{7}min, Invincibility +{8}s)",
                ["berserker_max_level"] = "★ Max Level Reached!",
                ["berserker_level_req_items"] = "Lv{0} Required Items",
                ["berserker_level_item_required"] = "Not enough materials for Berserker Lv{0} upgrade",
                ["berserker_lv2_skill_prereq_required"] = "Lv2 condition not met: Need at least 1 of Fury Hammer / Rush Slash / Pierce Charge",
                ["berserker_missing_items"] = "Missing items: {0}",
                ["berserker_rage_damage_display"] = "🔥 Bonus Dmg +{0}% 🔥",
                ["berserker_passive_cd_ms"] = "🛡️ Death Defiance CD: {0}m {1:00}s",
                ["berserker_passive_cd_s"] = "🛡️ Death Defiance CD: {0}s",
                ["berserker_upgrade_title"] = "🪓 Berserker Level Up",
                ["berserker_upgrade_confirm"] = "Upgrade Berserker to Lv{0}?\nTrophies will be consumed.",

                // === Rogue Job ===
                ["rogue_desc_shadow_strike"] = "Poison Blast x{0}, range {1}m",
                ["rogue_desc_attack_bonus"] = "+{1}% attack for {0}s",
                ["rogue_passive_desc"] = "Attack speed +{0}%, Stamina use -{1}%, Evasion +{2}%",
                ["requirement_rogue"] = "Knife or Claw equipped, Rogue job",
                ["rogue_passive_lv1"] = "ATK Speed +{0}%, Stamina -{1}%, Evasion +{2}%, Move Speed +{3}%",
                ["rogue_passive_lv2"] = "ATK Speed +{0}%, Stamina -{1}%, Evasion +{2}%, Move Speed +{3}%",
                ["rogue_passive_lv3"] = "ATK Speed +{0}%, Stamina -{1}%, Evasion +{2}%, Move Speed +{3}%",
                ["rogue_passive_lv4"] = "ATK Speed +{0}%, Stamina -{1}%, Evasion +{2}%, Move Speed +{3}%",
                ["rogue_passive_lv5"] = "ATK Speed +{0}%, Stamina -{1}%, Evasion +{2}%, Move Speed +{3}%",
                ["rogue_effect_strike"] = "ATK Buff {0}% ({1}s), Poison Blast x{2}",
                ["rogue_preview_attack"] = "ATK Buff +{0}%, Poison Blast +{1}",
                ["rogue_preview_charges"] = "Shadow Strike Charge +{0}",
                ["rogue_preview_poison"] = "Poison: Instant +{0}%, DoT +{1}%/s",
                ["rogue_poison_info"] = "Poison Range {0}m │ Instant {1}% │ Per Sec {2}%",
                ["rogue_preview_cd"] = "Cooldown -{0}s",
                ["rogue_max_level"] = "★ Max Level Reached!",
                ["rogue_level_req_items"] = "Lv{0} Required Items",
                ["rogue_charges_display"] = "{0} Charge(s)",
                ["rogue_lv2_unlock_cond"] = "Requires Assassin's Heart skill",
                ["archer_lv2_unlock_cond"] = "Need OneShot or ExplosiveArrow skill for Lv2",
                ["mage_lv2_unlock_cond"] = "Must learn Double Casting for Lv2 upgrade",
                ["rogue_level_item_required"] = "Not enough materials for Rogue Lv{0} upgrade",

                // === Mage Job ===
                ["mage_desc_aoe"] = "Area damage {0}%",
                ["mage_passive_resistance"] = "Magic resistance +{0}%",
                ["requirement_mage"] = "Staff or Wand equipped, Mage job",
                // === Fire Rain ===
                ["mage_firerain_cast"] = "🔥 Fire Rain cast! Target: {0}",
                ["mage_desc_firerain"] = "Target enemy ahead and unleash Fire Rain.",
                ["mage_firerain_damage"] = "{0} Fireballs × 3 Bursts (Weapon dmg {1}%)",
                ["mage_firerain_range"] = "Drop radius {0}m, Impact radius {1}m",
                // === Mage Level System ===
                ["mage_passive_lv1"] = "AOE dmg {0}%, Cooldown {2}s, Elemental Resist {1}%",
                ["mage_passive_lv2"] = "AOE dmg {0}%, Cooldown {2}s, Double Cast +1 (30s), Elemental Resist {1}%",
                ["mage_level_req_items"] = "Lv{0} Required Items",
                ["mage_level_item_required"] = "Not enough trophies for Mage Lv{0} upgrade",
                ["mage_missing_items"] = "Missing items: {0}",
                ["mage_max_level"] = "★ Max Level Reached!",
                ["mage_upgrade_msg"] = "🔮 Upgraded to Mage Lv{0}!",
                ["mage_upgrade_title"] = "🔮 Mage Level Up",
                ["mage_upgrade_confirm"] = "Upgrade Mage to Lv{0}?\nTrophies will be consumed.",
                ["item_missing_msg"] = "{0} is required",
                ["item_trophy_surtling"] = "Surtling Trophy",
                ["item_trophy_wraith"] = "Wraith Trophy",

                // === Healer/Staff ===
                ["healer_self_heal_included"] = "Includes caster",
                ["healer_self_heal_excluded"] = "Caster not healed (other players only)",
                ["healer_desc_instant"] = "Instant heal in {0}m radius from caster",
                ["healer_desc_heal_percent"] = "Instantly restore {0}% of ally max health",
                ["healer_healing_effect"] = "Healing Effect",
                ["healer_instant_heal"] = "Instantly restore {0} of ally max health",
                ["staff_desc_dual_cast_fallback"] = "Fire 7 additional magic projectiles in rapid succession (0.25s interval)",
                ["staff_desc_dual_cast_damage_fallback"] = "15% of staff/wand damage",

                // === Expert Tree Skill Descriptions ===
                // Attack Expert Tree
                ["attack_root_desc"] = "All attack power +{0}% (physical, elemental)",
                ["atk_melee_bonus_desc"] = "Melee weapon attack +{0}%",
                ["atk_bow_bonus_desc"] = "Bow attack power +{0}%",
                ["atk_crossbow_bonus_desc"] = "Crossbow attack +{0}%",
                ["atk_staff_bonus_desc"] = "Staff or Wand attack +{0}%",
                ["atk_crit_chance_desc"] = "Crit chance +{0}%",
                ["atk_melee_crit_desc"] = "+{0}% extra damage on 2-hit combo with one-handed melee",
                ["atk_crit_dmg_desc"] = "Crit damage +{0}%",
                ["atk_twohand_crush_desc"] = "Two-handed weapon damage +{0}%",
                ["atk_staff_mage_desc"] = "Elemental damage +{0}% with staff attack",
                ["atk_finisher_melee_desc"] = "One-handed weapon damage +{0}%",

                // Defense Expert Tree - Names
                ["defense_root_name"] = "Defense Expert",
                ["defense_survival_name"] = "Skin Hardening",
                ["defense_dodge_name"] = "Mind-Body Training",
                ["defense_health_name"] = "Health Training",
                ["defense_breath_name"] = "Core Breathing",
                ["defense_agile_name"] = "Evasion Training",
                ["defense_boost_name"] = "Health Boost",
                ["defense_shield_name"] = "Shield Training",
                ["defense_mental_name"] = "Shockwave Release",
                ["defense_mental_desc"] = "When HP below 45%, stun enemies within {0}m for {1}s (Cooldown: {2}s)",
                ["defense_instant_name"] = "Ground Stomp",
                ["defense_instant_desc"] = "When HP below 35%, push enemies {0}m away (Cooldown: {1}s)",
                ["defense_tanker_name"] = "Rock Skin",
                ["defense_focus_name"] = "Endurance",
                ["defense_stamina_name"] = "Agility",
                ["defense_heal_name"] = "Troll's Regeneration",
                ["defense_parry_name"] = "Block Master",
                ["defense_mind_name"] = "Mind Shield",
                ["defense_mind_short_desc"] = "Activates a shield absorbing up to max Eitr worth of damage",
                ["defense_mind_desc"] = "Press G to activate shield absorbing up to max Eitr worth of damage\nShield duration: {0}s\nCost: Eitr {1}\nSkill Type: Active G Key\nWeapon: Staff or Wand\nCooldown: {2:F0}s\nRequirement: Staff or Wand equipped",
                ["defense_mind_full_desc"] = "Press G to activate shield absorbing up to max Eitr worth of damage\nShield duration: {0}s\nCost: Eitr {1}\nSkill Type: Active G Key\nWeapon: Staff or Wand\nCooldown: {2:F0}s\nRequirement: Staff or Wand equipped",
                ["defense_mind_effect"] = "Mind Shield learned!",
                ["mind_shield_activate"] = "Mind Shield activated!",
                ["mind_shield_eitr_insufficient"] = "Not enough Eitr.",
                ["mind_shield_cooldown"] = "Mind Shield on cooldown",
                ["defense_attack_name"] = "Nerve Enhancement",
                ["defense_double_jump_name"] = "Double Jump",
                ["defense_double_jump_desc"] = "Jump {0} additional time(s) in air",
                ["defense_body_name"] = "Jotunn's Vitality",
                ["defense_true_name"] = "Jotunn's Shield",

                // Defense Expert Tree - Descriptions
                ["defense_root_desc"] = "Health +{0}, Helmet Armor +{1}",
                ["defense_survival_desc"] = "Health +{0}, Chest Armor +{1}",
                ["defense_health_desc"] = "Health +{0}, Legs Armor +{1}",
                ["defense_dodge_desc"] = "Max stamina +{0}, Max Eitr +{1}",
                ["defense_breath_desc"] = "Max Eitr +{0}",
                ["defense_agile_desc"] = "Dodge +{0}%, Roll invincibility +{1}%",
                ["defense_boost_desc"] = "Health +{0}",
                ["defense_shield_desc"] = "Shield block power +{0}",
                ["defense_tanker_desc"] = "Defense +{0}%",
                ["defense_focus_desc"] = "Run stamina -{0}%, Jump stamina -{1}%",
                ["defense_stamina_desc"] = "Dodge +{0}%, Roll stamina -{1}%",
                ["defense_heal_desc"] = "Health +{1} every {0}s",
                ["defense_parry_desc"] = "Parry +{0}s, Shield block power +{1}",
                ["defense_attack_desc"] = "Dodge +{0}% if evasion not triggered for 30s",
                ["defense_body_desc"] = "Max health +{0}%, Physical/Elemental resistance +{1}%",
                ["defense_true_desc"] = "Block stamina -{0}%, Normal shield speed +{1}%, Tower shield speed +{2}%",

                // Defense Expert Tree - Effect Texts (English)
                ["defense_root_effect"] = "🛡️ Defense Expert! Health +{0}, Defense +{1}",
                ["defense_shield_effect"] = "🛡️ Shield Training! Shield block power +{0}",
                ["defense_parry_effect"] = "🛡️ Parry Master! Parry +{0}s, Shield block power +{1}",
                ["defense_body_effect"] = "🛡️ Jotunn's Vitality! Health +{0}%, Resistance +{1}%",

                // Staff Expert Tree
                ["staff_expert_desc"] = "Elemental damage +{0}%",
                ["staff_focus_desc"] = "Eitr cost -{0}%",
                ["staff_stream_desc"] = "Max Eitr +{0}",
                ["staff_frost_desc"] = "Frost damage +{0}",
                ["staff_fire_desc"] = "Fire damage +{0}",
                ["staff_lightning_desc"] = "Lightning damage +{0}",
                ["staff_luck_mana_desc"] = "{0}% chance for no Eitr cost",

                // Mace Expert Tree (additional)
                ["mace_expert_desc2"] = "Mace damage +{0}%, {1}% chance to stun for {2}s on hit",
                ["mace_stun_boost_desc2"] = "Stun chance +{0}%, Duration +{1}s",
                ["mace_guard_boost_desc2"] = "Secondary attack damage +{0}%, AoE range {1}m, knockback {2}m",
                ["mace_heavy_strike_desc2"] = "Heavy attack blunt +{0}",
                ["mace_knockback_desc2"] = "When not blocking, {0}% chance to push attacker on hit",
                ["mace_tank_desc2"] = "Health +{0}%, Damage taken -{1}%",
                ["mace_dps_desc2"] = "Damage +{0}%",
                ["mace_grandmaster_desc2"] = "Attack speed +{0}%",

                // === Producer Job Keys (EN) ===
                ["job_producer"] = "Producer",
                ["job_producer_short"] = "Crafter",
                ["job_change_announce"] = "{0} has changed their job to {1}.",
                ["producer_buff_desc"] = "{0}s buff for allies in 15m: Attack+{1}%, Max HP+{2}%",
                ["producer_buff_applied"] = "✨ Artisan's Blessing activated!",
                ["producer_passive_lv1"] = "Durability+{0}%, Craft Success+{1}%",
                ["producer_passive_lv2"] = "Durability+{0}%, Material-{1}%, Craft Success+{2}%",
                ["producer_passive_lv3"] = "Durability+{0}%, Material-{1}%, Enchant {2}% chance, Craft Success+{3}%",
                ["producer_passive_lv4"] = "Durability+{0}%, Material-{1}%, Enchant {2}% chance, Craft Success+{3}%",
                ["producer_passive_lv5"] = "Durability+{0}%, Material-{1}%, Enchant {2}% chance, Craft Success+{3}%",
                ["producer_enchant_detail_lv3"] = "  └ Weapon: Attack+5% or Speed+5%\n  └ Armor: Defense+5% or HP+2% or Stamina+5%",
                ["producer_enchant_detail_lv4"] = "  └ Weapon: Attack+7~9% or Speed+7~9%\n  └ Armor: Defense+7~9% or HP+4~5% or Stamina+6~8%",
                ["producer_enchant_detail_lv5"] = "  └ Weapon: Attack+10~12% or Speed+10~12%\n  └ Armor: Defense+10~12% or HP+6~8% or Stamina+9~12%",
                ["producer_enchant_weapon_dmg"] = "✨ Crafting Blessing: Attack +{0}%",
                ["producer_enchant_armor"] = "✨ Crafting Blessing: Armor +{0}%",
                ["producer_enchant_hp"] = "✨ Crafting Blessing: Max HP +{0}%",
                ["producer_enchant_notify"] = "✨ Crafting Blessing!",
                ["producer_level_req_items"] = "Lv{0} Required Items",
                ["producer_max_level"] = "★ Max Level Reached!",
                ["requirement_job_producer"] = "Job: Producer",
                ["item_trophy_bear"] = "Bear Trophy",
                ["farmgrid_planted"] = "{0} seeds additionally planted",
                ["farmgrid_no_seeds"] = "Not enough seeds",
                ["farmgrid_spacing"] = "Grid spacing: {0}",
                ["farmgrid_rotation"] = "Farm grid angle: {0}",
                ["producer_enchant_weapon_spd"] = "✨ Crafting Blessing: ATK SPD +{0}%",
                ["producer_enchant_stamina"]    = "✨ Crafting Blessing: Stamina +{0}",
                // New enchant keys (v1.2.095)
                ["producer_enchant_stamina_pct"]     = "✨ Crafting Blessing: Stamina +{0}%",
                ["producer_enchant_bow_crit"]         = "✨ Crafting Blessing: Bow Crit +{0}%",
                ["producer_enchant_crossbow_reload"]  = "✨ Crafting Blessing: Reload Speed +{0}%",
                ["producer_enchant_cooldown_reduce"]  = "✨ Crafting Blessing: Skill CD -{0}%",
                ["producer_enchant_dodge_roll"]       = "✨ Crafting Blessing: Dodge Stamina -{0}%",
                ["producer_enchant_move_speed"]       = "✨ Crafting Blessing: Move Speed +{0}%",
                ["producer_enchant_eitr"]             = "✨ Crafting Blessing: Eitr +{0}",
                ["producer_enchant_inv_weight"]       = "✨ Crafting Blessing: Carry Weight +{0}",
                ["producer_enchant_eitr_regen"]       = "✨ Crafting Blessing: Eitr Regen +{0}%",
                ["producer_enchant_jump_force"]       = "✨ Crafting Blessing: Jump Force +{0}%",
                ["producer_enchant_block_power"]      = "✨ Crafting Blessing: Guard Power +{0}%",

                // === Prerequisite Text ===
                ["prerequisite_label"] = "🔗 Required",
                ["prerequisite_connector_or"] = " or ",
                ["prerequisite_labor_craft"] = "Labor Expert + Crafting Expert",
                ["or_separator"] = "or",
                ["skill_prerequisite_any_required"] = "Requires at least one: {0}",

                // === Weapon Requirement Conditions ===
                ["requirement_bow_effect"] = "Bow equipped",
                ["requirement_crossbow_effect"] = "Crossbow equipped",
                ["requirement_staff_effect"] = "Staff equipped",
                ["requirement_sword_effect"] = "Sword equipped",
                ["requirement_axe_effect"] = "Axe equipped",
                ["requirement_knife_effect"] = "Knife equipped",
                ["requirement_spear_effect"] = "Spear equipped",
                ["requirement_mace_effect"] = "Mace equipped",
                ["requirement_one_hand_melee_effect"] = "One-handed melee weapon equipped",

                // === MMO Bridge Messages ===
                ["mmo_level_recovery_complete"] = "Level data recovery complete!",
                ["mmo_level_recovery_detail"] = "Lv.{0} → Lv.{1}",
                ["mmo_captain_to_epic_complete"] = "Captain -> EpicMMO migration complete!",
                ["mmo_captain_to_epic_detail"] = "Lv.{0} -> Lv.{1}",
                ["mmo_skillpoint_sync_complete"] = "Skill Points -> EpicMMO sync complete!",
                ["mmo_skillpoint_sync_detail"] = "Lv.{0} -> Lv.{1}",
                ["mmo_epic_to_captain_complete"] = "EpicMMO -> Captain data recovery complete!",
                ["mmo_epic_to_captain_detail"] = "Lv.{0}",
                ["level_up_message"] = "<color=green>LEVEL UP!</color>\n+{0} Skill Points (Lv.{1})",
                ["mmo_level_sync_message"] = "<color=#00BFFF>Lv.{0} / Skill Point. {1}</color>",

                // === Job Skill Messages ===
                ["job_no_job_selected"] = "No job selected.",
                ["job_one_hand_melee_required"] = "One-handed melee weapon required!",
                ["job_holy_heal_cooldown"] = "Holy Heal cooldown: {0}s",
                ["job_stamina_required"] = "Not enough stamina ({0} required)",
                ["job_eitr_required"] = "Not enough Eitr ({0} required)",
                ["job_self_heal"] = "✨ Self Heal: +{0} HP",
                ["job_paladin_heal_success"] = "⭐ Paladin Holy Heal! (Self heal + {0} allies DoT heal)",
                ["job_continuous_heal_start"] = "🌟 Continuous healing started!",
                ["job_continuous_heal_tick"] = "💚 Continuous heal: +{0} HP",
                ["job_continuous_heal_progress"] = "💚 Continuous heal: +{0} HP ({1}/{2})",
                ["job_continuous_heal_complete"] = "✨ Continuous healing complete!",
                ["job_skill_error"] = "Error during skill cast.",

                // === Paladin Level System ===
                ["paladin_upgrade_msg"] = "⚔️ Upgraded to Paladin Lv{0}!",
                ["paladin_level_req_items"] = "Lv{0} Required Items",
                ["paladin_level_item_required"] = "Not enough trophies for Paladin Lv{0} upgrade",
                ["paladin_max_level"] = "★ Max Level Reached!",
                ["paladin_missing_items"] = "Missing items: {0}",
                ["item_deficit_fmt"] = "{0} is required",
                ["coin_deficit_fmt"] = "Need {0} Coins",
                ["paladin_upgrade_title"] = "⚔️ Paladin Level Up",
                ["paladin_upgrade_confirm"] = "Upgrade Paladin to Lv{0}?\nTrophies will be consumed.",
                ["paladin_lv2_skill_required"] = "Requires 1 of: Fury Hammer or Rush Slash",
                ["paladin_active_desc"] = "Self-heal {0}% instantly, nearby allies {1}%/tick x{2}s heal",
                ["paladin_passive_lv1"] = "Enemy Damage Taken +{0}%",
                ["paladin_passive_lv2"] = "Max stamina +{0}, Enemy Damage Taken +{1}%, bonus skill use within 30s",
                ["paladin_passive_lv3"] = "Max stamina +{0}, Enemy Damage Taken +{1}%",
                ["paladin_passive_lv4"] = "Max stamina +{0}, Enemy Damage Taken +{1}%",
                ["paladin_passive_lv5"] = "Max stamina +{0}, Enemy Damage Taken +{1}%",

                // === Rogue Skill Messages ===
                ["rogue_shadow_strike_cooldown"] = "Shadow Strike cooldown: {0}s",
                ["rogue_stamina_insufficient"] = "Not enough stamina.",
                ["rogue_shadow_strike_success"] = "🗡️ Shadow Strike! (Poison Blast x8 + {1}% damage for {0}s)",
                ["rogue_shadow_strike_end"] = "Shadow Strike ended",
                ["rogue_shadow_strike_activate"] = "💥 Shadow Strike!",
                ["rogue_dagger_required"] = "Dagger or Claw required",
                ["rogue_buff_end"] = "Shadow Strike buff ended!",
                ["rogue_smoke"] = "Smoke!",
                ["rogue_shadow_strike_no_enemy"] = "Shadow Strike! (No enemies nearby)",

                // === Mage Skill Messages ===
                ["mage_explosion_cooldown"] = "Magic Explosion cooldown: {0}s",
                ["mage_eitr_insufficient"] = "Not enough Eitr.",
                ["mage_explosion_success"] = "🔮 Magic Explosion! (+{1}% magic damage, +{2}m range for {0}s)",
                ["mage_explosion_end"] = "Magic Explosion ended",

                // === Archer Skill Messages ===
                ["archer_multishot_cooldown"] = "Multi-Shot cooldown: {0}s",
                ["archer_stamina_insufficient"] = "Not enough stamina",
                ["archer_multishot_success"] = "🏹 Multi-Shot! ({0} arrows fired)",
                ["archer_bow_required"] = "Bow required!",
                ["archer_no_arrow"] = "No arrows!",
                ["archer_job_required"] = "Archer job required!",
                ["archer_cooldown"] = "Cooldown: {0}s",

                // === Berserker Skill Messages ===
                ["berserker_rage_end"] = "Berserker Rage ended",

                // === Tanker Level-Up System ===
                ["tanker_upgrade_title"] = "Tanker Upgrade",
                ["tanker_upgrade_confirm"] = "Upgrade to Lv{0}?",
                ["tanker_max_level"] = "★ Tanker Max Level!",
                ["tanker_level_item_required"] = "Insufficient materials for Tanker Lv{0} upgrade",
                ["tanker_missing_items"] = "Missing items: {0}",
                ["tanker_lv2_skill_prereq_required"] = "Must learn one of: Fury Hammer, Rush Slash, Parry Charge, Shield Charge, Spear Pierce, Spear Combo, or Pierce Charge",
                ["tanker_lv2_skill_required"] = "Requires 1 of: Fury Hammer/Rush Slash/Parry Charge/Shield Charge/Spear Pierce/Spear Combo/Pierce Charge — learn it and use within 30s",
                ["tanker_lv2_recent_use_required"] = "Use the learned skill within 30 seconds before upgrading",
                ["tanker_level_req_items"] = "Lv{0} Required Items",
                ["tanker_taunt_effect"] = "Taunt {0}m, {1}s",
                ["tanker_passive_lv1"] = "HP +{0}%, Dmg taken -{1}%, {2}s Reflect Accumulation ({3}%·{4}m Explosion)",
                ["tanker_passive_lv2"] = "HP +{0}%, Dmg taken -{1}%, Shield Block +{2}, {3}s Reflect Accumulation ({4}%·{5}m Explosion), Learned prereq skills (Pierce/Combo/FuryHammer/RushSlash/ParryCharge/ShieldCharge/PierceCharge) +1 use in 30s",
                ["tanker_passive_lv3"] = "HP +{0}%, Dmg taken -{1}%, Shield Block +{2}, {3}s Reflect Accumulation ({4}%·{5}m Explosion)",

                // === Sword Active Skill Messages ===
                ["sword_or_shield_required"] = "You must equip a sword or shield",

                // === Level Up Message ===
                ["level_up"] = "LEVEL UP!",

                // === Speed Expert Tree - Skill Names ===
                ["speed_root_name"] = "Speed Expert",
                ["speed_base_name"] = "Agility Foundation",
                ["melee_combo_name"] = "Flow of Combo",
                ["crossbow_reload2_name"] = "Crossbow Mastery",
                ["bow_speed2_name"] = "Bow Mastery",
                ["moving_cast_name"] = "Moving Cast",
                ["speed_ex1_name"] = "Apprentice I",
                ["speed_ex2_name"] = "Apprentice II",
                ["speed_master_name"] = "Energizer",
                ["ship_master_name"] = "Captain",
                ["agility_peak_name"] = "Jump Master",
                ["speed_1_name"] = "Agility",
                ["speed_2_name"] = "Endurance",
                ["speed_3_name"] = "Intelligence",
                ["all_master_name"] = "Master",
                ["melee_speed1_name"] = "Melee Acceleration",
                ["crossbow_draw1_name"] = "Crossbow Acceleration",
                ["bow_draw1_name"] = "Bow Acceleration",
                ["staff_speed1_name"] = "Cast Acceleration",

                // === Speed Expert Tree - Skill Descriptions ===
                ["speed_root_desc"] = "Move speed +{0}%",
                ["speed_base_desc"] = "Attack speed +{0}%, Move speed +{2}% for {1}s after dodge",
                ["melee_combo_desc"] = "On melee 2-hit combo: Attack speed +{1}%, Stamina -{2}% for {0}s",
                ["crossbow_reload2_desc"] = "On crossbow hit: Move speed +{0}% ({1}s), Reload +{2}% during buff",
                ["bow_speed2_desc"] = "On bow 2-hit combo: Stamina -{0}%, Next draw +{1}%",
                ["moving_cast_desc"] = "Move speed +{0}% during cast, Eitr cost -{1}%",
                ["speed_ex1_desc"] = "Melee skill +{0}, Crossbow skill +{1}",
                ["speed_ex2_desc"] = "Magic skill +{0}, Bow skill +{1}",
                ["speed_master_desc"] = "Food consumption rate -{0}%",
                ["ship_master_desc"] = "Ship speed +{0}%",
                ["agility_peak_desc"] = "Jump skill +{0}, Jump stamina -{1}%",
                ["speed_1_desc"] = "Melee attack speed +{0}%, Move speed +{1}%",
                ["speed_2_desc"] = "Max stamina +{0}",
                ["speed_3_desc"] = "Max Eitr +{0}",
                ["all_master_desc"] = "Run skill +{0}, Jump skill +{1}",
                ["melee_speed1_desc"] = "Melee attack speed +{0}%, Next attack speed +{1}% on 3-hit combo",
                ["crossbow_draw1_desc"] = "Crossbow reload +{0}%, Move speed +{1}% during reload",
                ["bow_draw1_desc"] = "Bow draw +{0}%, Move speed +{1}% during draw",
                ["staff_speed1_desc"] = "Magic attack speed +{0}%, Recover {1}% max Eitr on 3-hit combo",

                // === Speed Expert Tree - Effect Texts (English) ===
                ["speed_root_effect"] = "🏃 Speed Expert Invested! (+{0}% Move Speed)",
                ["speed_base_effect"] = "🏃 Agility Foundation Learned!\nAttack Speed +{0}%\nMove Speed +{1}% after dodge",
                ["speed_ex1_effect"] = "⚔️ Trainee 1 Learned! Melee/Crossbow Proficiency +{0}",
                ["speed_ex2_effect"] = "🏹 Trainee 2 Learned! Staff/Bow Proficiency +{0}",
                ["all_master_effect"] = "🏃 Master Learned! Run/Jump Proficiency +{0}",
                ["agility_peak_effect"] = "🦘 Jump Master Learned! Jump Proficiency +{0}",

                // === Archer Tooltip Keys ===
                ["archer_level_req_items"] = "Lv{0} Required Items",
                ["archer_preview_arrows_damage"] = "+{0} projectiles, {1}% damage per arrow",
                ["archer_preview_charges"] = "+{0} additional charges",
                ["archer_job_requirement"] = "Bow equipped, Archer job",

                // === UI Messages ===
                ["skill_acquired_count"] = "✅ {0} skill(s) acquired!",
                ["skill_acquired_name"]  = "🌟 {0} acquired!",

                // === Item Display Names ===
                ["item_coins"] = "Coins",

                // === Active Skill Restriction Messages ===
                ["active_skill_job_only_one"] = "Only one job active skill can be selected",
                ["active_skill_ranged_only_one"] = "Only one ranged active skill can be selected",
                ["active_skill_weapon_conflict"] = "An active skill for a different weapon is already selected",
                ["cannot_learn_with"] = "Cannot learn together with {0}",
                ["job_class_one_only"] = "Only one job class can be selected",

                // === Speed / Agility Expert Effect Messages ===
                ["agility_base"] = "Agility Foundation! (+{0}% Move Speed)",
                ["cast_triple_combo"] = "Cast Triple Combo! (+{0} Eitr)",
                ["melee_triple_combo"] = "Melee Triple Combo! (+{0}% Attack Speed)",
                ["energizer"] = "Energizer!",
                ["knockback_effect"] = "Knockback!",

                // === Combat Notifications ===
                ["attack_expert"] = "Attack Expert!",
                ["attack_expert_acquired"] = "Attack Expert Acquired!",
                ["attack_increased"] = "Attack Increased!",
                ["consecutive_attack"] = "Consecutive Attack!",
                ["consecutive_flow"] = "Consecutive Flow!",
                ["consecutive_melee_master"] = "Consecutive Melee Master!",
                ["cooldown_remaining"] = "Cooldown: {0}s",
                ["critical_strike"] = "Critical Strike!",
                ["enhanced_strike"] = "Enhanced Strike! (+{0}%)",
                ["precision_attack"] = "Precision Attack!",
                ["rage_bonus"] = "Bonus Damage +{0}%",
                ["skill_activated"] = "{0} activated!",

                // === Specialization Messages ===
                ["bow_expert_mastery"] = "Bow Expert!",
                ["bow_specialization"] = "Bow Specialization!",
                ["crossbow_expert_mastery"] = "Crossbow Expert!",
                ["crossbow_specialization"] = "Crossbow Specialization!",
                ["melee_enhance"] = "Melee Enhanced!",
                ["melee_specialization"] = "Melee Specialization!",
                ["ranged_enhance"] = "Ranged Enhanced!",
                ["staff_specialization"] = "Staff Specialization!",
                ["spear_expert_damage"] = "Spear Expert Damage! (+{0}%)",
                ["elemental_attack"] = "Elemental Attack!",

                // === Bow / Archer Skills ===
                ["basic_bow_damage"] = "Basic Bow Damage +{0}!",
                ["focus_fire_crit"] = "Focus Fire Critical x{0}!",
                ["one_shot"] = "One Shot! +{0}%",
                ["archer_multishot_fired"] = "Multishot! ({0} arrows fired)",
                ["explosive_arrow_fire"] = "Explosive Arrow Fired!",
                ["explosive_arrow_ready"] = "Explosive Arrow Ready!",
                ["explosive_arrow_skill_required"] = "Explosive Arrow skill required",
                ["multishot_end"] = "Multishot End",
                ["multishot_skill"] = "Multishot {0}! (+{1} arrows)",

                // === Berserker Skills ===
                ["already_rage_state"] = "Already in Rage state!",
                ["berserker_cooldown"] = "Cooldown ({0}s)",
                ["berserker_rage"] = "Berserker Rage!",
                ["death_ignore"] = "Death Ignored",

                // === Charge / Rush Skills ===
                ["charge_complete"] = "Charge Complete",
                ["evasion_thrust"] = "Evasion Thrust! (+{0}%)",
                ["evasion_thrust_end"] = "Evasion Thrust End",
                ["evasion_thrust_ready"] = "Evasion Thrust Ready!",
                ["pierce_charge"] = "Pierce Charge!",
                ["pierce_charge_damage"] = "Pierce Charge! (+{0}%)",
                ["pierce_charge_in_progress"] = "Pierce Charge in Progress",
                ["rush_slash_1st_attack"] = "⚔️ 1st Slash! ({0}%)",
                ["rush_slash_2nd_attack"] = "⚔️ 2nd Slash! ({0}%)",
                ["rush_slash_activate"] = "Rush Slash!",
                ["rush_slash_canceled"] = "Rush Slash Canceled",
                ["rush_slash_complete"] = "Rush Slash Complete! ({0} hits)",
                ["rush_slash_default"] = "⚔️ Slash! ({0}%)",
                ["rush_slash_finisher"] = "💥 Finisher! ({0}%)",
                ["rush_slash_in_progress"] = "Rush Slash in Progress",
                ["rush_slash_return"] = "Returning to position!",
                ["rush_slash_skill_required"] = "Rush Slash skill required",

                // === Parry / Shield Skills ===
                ["parry_rush_activate"] = "Parry Rush! ({0}s)",
                ["parry_rush_already_active"] = "Parry Rush already active",
                ["parry_rush_buff_name"] = "Parry Rush",
                ["parry_rush_damage"] = "Parry Rush! (+{0}%)",
                ["parry_rush_skill_required"] = "Parry Rush skill required",
                ["shield_required"] = "Shield must be equipped",
                ["reflect_damage"] = "Reflect Damage {0}!",

                // === Polearm Skills ===
                ["polearm_area_combo"] = "Area Strike! 2-hit Attack +{0}%",
                ["polearm_cooldown_remaining"] = "Cooldown: {0}s remaining",
                ["polearm_required"] = "Polearm must be equipped!",
                ["polearm_stamina_insufficient"] = "Stamina Insufficient!",

                // === Explosion / Ground Stomp ===
                ["explosion_damage"] = "Explosion! +{0}",
                ["explosion_spear"] = "Quick Spear! Attack Speed +{0}%",
                ["ground_stomp_effect"] = "Ground Stomp! ({0} pushed)",
                ["shockwave_30sec_remaining"] = "⚡ Shockwave ready in 30s!",
                ["shockwave_ready"] = "⚡ Shockwave Ready!",
                ["stomp_30sec_remaining"] = "🦶 Ground Stomp ready in 30s!",
                ["stomp_ready"] = "🦶 Ground Stomp Ready!",

                // === Healer / Staff Skills ===
                ["heal_cooldown"] = "Heal Cooldown: {0}s",
                ["luck_magic_activated"] = "✨ Lucky Magic Activated!",
                ["no_heal_target"] = "No target to heal",
                ["sacred_heal"] = "Sacred Heal! ({0} healed)",
                ["staff_wand_required"] = "❌ Staff or Wand must be equipped!",

                // === Tanker Skills ===
                ["tanker_defense_buff_activated"] = "<color=#FFD700>⚔ Defense Buff Activated! ⚔</color>",
                ["tanker_shield_required"] = "Shield must be equipped",
                ["taunt_ready"] = "Taunt Ready!",

                // === Misc Combat ===
                ["equipment_consumed"] = "Equipment Consumed: {0}",
                ["hero_strike_stagger"] = "Hero Strike! (Stagger)",
                ["material_consumed"] = "Material Consumed: {0}",
                ["stamina_insufficient"] = "Stamina is insufficient",
                ["stamina_insufficient_short"] = "Stamina Insufficient!",
                ["sword_required"] = "Sword must be equipped",
                ["wheel_attack"] = "Wheel Attack +{0}%!",
            };
        }
    }
}
