using System.Collections.Generic;

namespace CaptainSkillTree.Localization
{
    public static partial class DefaultLanguages
    {
        private static Dictionary<string, string> GetKorean_AttackProduction()
        {
            return new Dictionary<string, string>
            {
                // === Attack Expert Tree - Skill Names ===
                ["attack_root_name"] = "공격 전문가",
                ["atk_base_name"] = "기본 공격",
                ["atk_melee_bonus_name"] = "근접 특화",
                ["atk_bow_bonus_name"] = "활 특화",
                ["atk_crossbow_bonus_name"] = "석궁 특화",
                ["atk_staff_bonus_name"] = "지팡이 특화",
                ["atk_twohand_drain_name"] = "공격 증가",
                ["atk_melee_crit_name"] = "근접 강화",
                ["atk_crit_chance_name"] = "정밀 공격",
                ["atk_ranged_enhance_name"] = "원거리 강화",
                ["atk_special_name"] = "특수화 스탯",
                ["atk_crit_dmg_name"] = "약점 공격",
                ["atk_finisher_melee_name"] = "연속 근접의 대가",
                ["atk_twohand_crush_name"] = "양손 분쇄",
                ["atk_staff_mage_name"] = "속성 공격",

                // === Attack Expert Tree - Skill Descriptions ===
                ["atk_base_desc"] = "관통 공격 +{0}, 화염 속성 +1",
                ["atk_twohand_drain_desc"] = "물리 공격력 +{0}%, 속성 공격력 +{1}%",
                ["atk_ranged_enhance_desc"] = "원거리 무기 공격력 +{0}% (석궁, 활, 지팡이)",
                ["atk_special_desc"] = "치명타 확률 +{0}%",

                // === Attack Expert Tree - Effect Texts ===
                ["atk_base_effect"] = "💪 기본 공격 습득!",
                ["atk_melee_bonus_effect"] = "⚔️ 근접 특화 습득!",
                ["atk_twohand_drain_effect"] = "💪 공격 증가!",
                ["atk_ranged_enhance_effect"] = "🏹 원거리 강화!",
                ["atk_special_effect"] = "⭐ 특수화 스탯! 치명타 확률 +{0}%",
                ["atk_staff_mage_effect"] = "🔥 속성 공격!",

                // === Paladin Skill ===
                ["paladin_name"] = "성기사",
                ["paladin_desc"] = "신성한 치유: 자신 및 {0}m 범위 아군 치유",
                ["paladin_passive_desc"] = "한손 근접무기 데미지 +{0}%, 자신 및 주변 아군 힐링 (Y키)",
                ["paladin_tooltip_desc"] = "범위 아군 체력 {0}%/{1}초 ({2}초), 자가 {3}% 즉시",
                ["paladin_passive_resistance"] = "물리 및 속성 저항 -{0}%",
                ["paladin_requirement"] = "한손 근접무기 착용, 성기사 직업",
                ["paladin_required_item"] = "에이크쉬르 트로피",
                ["paladin_tooltip_error"] = "성기사 스킬 정보를 불러올 수 없음",

                // === Common Tooltip Labels ===
                ["tooltip_description"] = "설명",
                ["tooltip_range"] = "범위",
                ["tooltip_cost"] = "소모",
                ["tooltip_stamina"] = "스태미나",
                ["tooltip_eitr"] = "에이트르",
                ["tooltip_skill_type"] = "스킬유형",
                ["tooltip_job_active_y"] = "직업 액티브 스킬 - Y키",
                ["tooltip_passive"] = "패시브",
                ["tooltip_cooldown"] = "쿨타임",
                ["tooltip_seconds"] = "초",
                ["tooltip_requirement"] = "필요조건",
                ["tooltip_confirmation"] = "확인사항",
                ["tooltip_job_limit"] = "직업은 1개만 선택가능, 레벨 10 이상",
                ["tooltip_required_item"] = "필요 아이템",
                ["tooltip_max_targets"] = "최대 타겟",
                ["tooltip_targets_unit"] = "마리",

                // === Melee Root Skill ===
                ["melee_skill_expert"] = "근접 전문가",
                ["melee_desc_expert"] = "근접무기 공격력 +3 (고정값)",
                ["melee_root_effect"] = "⚔️ 근접 전문가 습득! 근접무기 공격력 +3",

                // === Ranged Root Skill ===
                ["ranged_skill_expert"] = "원거리 전문가",
                ["ranged_desc_expert"] = "활/석궁 관통 +2, 지팡이/완드 화염 공격 +2",

                // === Production Skills ===
                ["production_skill_expert"] = "생산 전문가",
                ["production_desc_expert"] = "50% 확률로 나무+1",
                ["novice_worker_name"] = "초보 일꾼",
                ["novice_worker_desc"] = "25% 확률로 나무+1",
                ["woodcutting_lv2_name"] = "벌목 Lv2",
                ["woodcutting_lv2_desc"] = "25% 확률로 나무+1",
                ["woodcutting_lv3_name"] = "벌목 Lv3",
                ["woodcutting_lv3_desc"] = "35% 확률로 나무+2",
                ["woodcutting_lv4_name"] = "벌목 Lv4",
                ["woodcutting_lv4_desc"] = "45% 확률로 나무+2",
                ["gathering_lv2_name"] = "채집 Lv2",
                ["gathering_lv2_desc"] = "25% 확률로 채집(나무제외)+1",
                ["gathering_lv3_name"] = "채집 Lv3",
                ["gathering_lv3_desc"] = "35% 확률로 채집(나무제외)+1",
                ["gathering_lv4_name"] = "채집 Lv4",
                ["gathering_lv4_desc"] = "40% 확률로 채집(나무제외)+1",
                ["mining_lv2_name"] = "채광 Lv2",
                ["mining_lv2_desc"] = "25% 확률로 광석+1",
                ["mining_lv3_name"] = "채광 Lv3",
                ["mining_lv3_desc"] = "25% 확률로 광석+1",
                ["mining_lv4_name"] = "채광 Lv4",
                ["mining_lv4_desc"] = "25% 확률로 광석+1",
                ["crafting_lv2_name"] = "제작 Lv2",
                ["crafting_lv2_desc"] = "25% 확률로 강화+1, 내구도 최대치 25% 증가",
                ["crafting_lv3_name"] = "제작 Lv3",
                ["crafting_lv3_desc"] = "25% 확률로 강화+1, 내구도 최대치 25% 증가",
                ["crafting_lv4_name"] = "제작 Lv4",
                ["crafting_lv4_desc"] = "25% 확률로 강화+1, 내구도 최대치 25% 증가",

                // === Production Skills - Effect Texts ===
                ["production_root_effect"] = "🌲 생산 전문가 습득!",
                ["novice_worker_effect"] = "🔧 초보 일꾼 습득!",
                ["woodcutting_lv2_effect"] = "🪓 벌목 Lv2 습득!",
                ["woodcutting_lv3_effect"] = "🪓 벌목 Lv3 습득! 35% 확률로 나무+2",
                ["woodcutting_lv4_effect"] = "🪓 벌목 Lv4 습득! 45% 확률로 나무+2",
                ["gathering_lv2_effect"] = "🍄 채집 Lv2 습득!",
                ["gathering_lv3_effect"] = "🍄 채집 Lv3 습득! 35% 확률로 채집+1!",
                ["gathering_lv4_effect"] = "🍄 채집 Lv4 습득! 40% 확률로 채집+1!",
                ["mining_lv2_effect"] = "⛏️ 채광 Lv2 습득!",
                ["mining_lv3_effect"] = "⛏️ 채광 Lv3 습득!",
                ["mining_lv4_effect"] = "⛏️ 채광 Lv4 습득! 은 25개 소모 시 광석 추가 획득!",
                ["crafting_lv2_effect"] = "🔨 제작 Lv2 습득!",
                ["crafting_lv3_effect"] = "🔨 제작 Lv3 습득!",
                ["crafting_lv4_effect"] = "🔨 제작 Lv4 습득! 은 검+헬멧 보유 시 제작 강화 효과!",

                // === Crossbow Skills ===
                ["crossbow_skill_expert"] = "석궁 전문가",
                ["crossbow_rapid_fire_lv1_name"] = "연속 발사 Lv1",
                ["crossbow_balance_name"] = "균형 조준",
                ["crossbow_rapid_name"] = "고속 장전",
                ["crossbow_mark_name"] = "정직한 한 발",
                ["crossbow_auto_reload_name"] = "자동 장전",
                ["crossbow_rapid_fire_lv2_name"] = "연속 발사 Lv2",
                ["crossbow_final_strike_name"] = "결전의 일격",
                ["crossbow_oneshot_name"] = "단 한 발",

                // === Bow Skills ===
                ["bow_skill_expert"] = "활 전문가",
                ["bow_focus_name"] = "집중 사격",
                ["bow_multishot_lv1_name"] = "멀티샷 Lv1",
                ["bow_proficiency_name"] = "활 숙련",
                ["bow_basic_attack_name"] = "기본 활공격",
                ["bow_multishot_lv2_name"] = "멀티샷 Lv2",
                ["bow_instinct_name"] = "사냥 본능",
                ["bow_precision_name"] = "정조준",
                ["bow_penetration_name"] = "침묵의 일격",
                ["bow_penetration_desc"] = "데미지 +{0}",
                ["bow_explosive_name"] = "폭발 화살",

                // === Staff Skills ===
                ["staff_skill_expert_name"] = "지팡이 전문가",
                ["staff_focus_name"] = "정신 집중",
                ["staff_stream_name"] = "마법 흐름",
                ["staff_amp_name"] = "마법 증폭",
                ["staff_frost_name"] = "냉기 속성",
                ["staff_fire_name"] = "화염 속성",
                ["staff_lightning_name"] = "번개 속성",
                ["staff_luck_mana_name"] = "행운 마력",
                ["staff_dual_cast_name"] = "연속 발사",
                ["staff_heal_name"] = "힐",

                // === Ranged/Crossbow/Bow Descriptions ===
                ["ranged_root_desc"] = "활/석궁 관통 +2, 지팡이/완드 화염 공격 +2",
                ["weapon_effect_note"] = "※ {0} 착용시 효과발동",
                ["crossbow_expert_desc"] = "석궁 공격력 +{0}%",
                ["crossbow_rapid_fire_desc"] = "{0}% 확률로 {1}발 연속 발사 (각 {2}% 데미지, 볼트 {3}발 소모)",
                ["crossbow_balance_desc"] = "명중 시 {0}% 확률로 넉백 ({1}m)",
                ["crossbow_rapid_desc"] = "장전속도 +{0}%",
                ["crossbow_mark_desc"] = "치명타 확률 0% 고정, 대신 석궁 공격력 +{0}%",
                ["crossbow_auto_reload_desc"] = "명중 시 {0}% 확률로 다음 1회 장전 속도 200%",
                ["crossbow_final_desc"] = "크리티컬 데미지 +{0}%",
                ["crossbow_oneshot_desc"] = "석궁 데미지 +{0}%, 다음 사격까지 {1}초 장전 지연",
                ["bow_expert_desc"] = "활 공격력 +{0}%",
                ["bow_focus_desc"] = "치명타 확률 +{0}%",
                ["bow_multishot_lv1_desc"] = "{0}% 확률로 추가 화살 1발 발사 (+3도 각도)",
                ["bow_proficiency_desc"] = "활 기술(숙련도) +{0}",
                ["bow_proficiency_note"] = "※ 사망해도 보너스 유지",
                ["bow_basic_attack_desc"] = "활 공격력 +{0}",
                ["bow_multishot_lv2_desc"] = "{0}% 확률로 추가 화살 2발 발사 (+3도 각도)",
                ["bow_instinct_desc"] = "치명타 확률 +{0}%",
                ["bow_precision_desc"] = "크리티컬 데미지 +{0}%",

                // === Crossbow Additional Descriptions ===
                ["crossbow_rapid_fire_lv2_desc"] = "{0}% 확률로 {1}발 연속 발사 (각 {2}% 데미지, 볼트 {3}발 소모)",
                ["crossbow_rapid_fire_lv2_note"] = "※ Lv1과 확률 합산",
                ["crossbow_final_strike_desc"] = "체력 {0}% 이상 적에게 추가 {1}% 피해",

                // === Crossbow Skill Effect Messages ===
                ["crossbow_auto_reload_activated"] = "자동 장전! (+{0}% 속도)",
                ["crossbow_auto_reload_and_rapid_fire"] = "자동 장전 + 연속 발사 모두 발동~! ({0}발)",
                ["crossbow_rapid_fire_activated"] = "연속 발사! ({0}발)",

                // === Staff Full Descriptions ===
                ["staff_expert_full_desc"] = "지팡이 속성 공격력 +{0}% 증가\n지팡이와 완드 사용법을 익혀 마법 공격력을 높입니다\n필요조건: 지팡이 또는 완드 착용",
                ["staff_focus_full_desc"] = "지팡이 사용 시 에이트르 소모량 -{0}% 감소\n정신력 집중으로 마나 효율성을 높입니다\n필요조건: 지팡이 또는 완드 착용",
                ["staff_stream_full_desc"] = "최대 에이트르 +{0} 증가\n마법의 흐름을 익혀 더 많은 마나를 보유할 수 있습니다\n필요조건: 지팡이 또는 완드 착용",
                ["staff_amp_full_desc"] = "{0}% 확률로 속성 공격 +{1}%\n에이트르 소모 +{2}% (디버프)\n에이트르 부족 시 일반 공격으로 전환\n필요조건: 지팡이 또는 완드 착용",
                ["staff_amp_activated"] = "마법 증폭 발동!",
                ["staff_frost_full_desc"] = "냉기 공격 +{0}\n필요조건: 지팡이 또는 완드 착용",
                ["staff_fire_full_desc"] = "화염 공격 +{0}\n필요조건: 지팡이 또는 완드 착용",
                ["staff_lightning_full_desc"] = "번개 공격 +{0}\n필요조건: 지팡이 또는 완드 착용",
                ["staff_luck_mana_full_desc"] = "{0}% 확률로 에이트르 소모 없음\n행운의 마력이 깃들어 공짜로 마법을 시전합니다\n필요조건: 지팡이 또는 완드 착용",
                ["staff_dual_cast_full_desc"] = "R키 활성화 후 마법 공격 시 0.25초 간격으로 {0}발 추가 발사\n공격력: 지팡이/완드의 {1:F0}%\n소모: Eitr {2:F0}\n스킬유형: 액티브 R키\n무기타입: 지팡이\n쿨타임: {3:F0}초\n필요조건: 지팡이 또는 완드 착용",
                ["staff_heal_full_desc"] = "H키로 시전자 중심 {0:F0}m 범위 즉시 힐링\n아군 최대체력의 {1}% 즉시 회복\n소모: Eitr {2:F0}\n스킬유형: 액티브 H키\n무기타입: 지팡이\n쿨타임: {3:F0}초\n필요조건: 지팡이 또는 완드 착용",

                // === Ranged Skills - Effect Texts ===
                ["ranged_root_effect"] = "🏹 원거리 전문가 습득!",
                ["bow_multishot_lv1_effect"] = "🏹 멀티샷 Lv1 습득!",
                ["bow_multishot_lv2_effect"] = "🏹🏹 멀티샷 Lv2 습득!",
                ["bow_proficiency_effect"] = "🏹 활 숙련 습득! 활 숙련도 +{0}",
                ["bow_explosive_desc"] = "폭발 화살 발사\n데미지: 활 공격력의 {0}%\n스태미나 {1}% 소모\n쿨타임: {2}초",

                // === Skill Activation Messages ===
                ["bow_equip_required"] = "활을 착용해야 합니다!",
                ["no_arrows"] = "화살이 없습니다!",
                ["cooldown_format"] = "쿨다운: {0}초",
                ["multishot_remaining_charges"] = "멀티샷! (남은 충전: {0}회)",
                ["multishot_cooldown_remaining"] = "멀티샷 쿨타임: {0}초",
                ["multishot_completed"] = "멀티샷 완료!",
                ["multishot_ready"] = "멀티샷 준비완료! ({0}회 사용 가능)",
                ["archer_job_required"] = "아처 직업이 필요합니다!",
                ["spear_penetrate_cooldown"] = "꿰뚫는 창 쿨타임 ({0}초)",
                ["spear_penetrate_activated"] = "꿰뚫는 창 발동! ({0}초)",
                ["staff_dual_cast_activated"] = "연속 발사 발동! {0}발 추가 발사",
                ["knife_assassin_heart_activated"] = "암살자의 심장 발동!",

                // === Sword Skill Messages ===
                ["sword_combo_3hit"] = "검술 연계 3단!",
                ["sword_expert_combo"] = "검 전문가 2연속! (+{0}%)",
                ["sword_combo_slash"] = "연속베기! 3연속 공격력 +{0}%",
                ["sword_counter_stance"] = "반격 자세! ({0}초간 방어력 +{1}%)",
                ["sword_blade_counter"] = "칼날 되치기! ({0}초간 공격력 +{1}%)",
                ["sword_offense_defense"] = "공방일체! (공격력 +{0}%, 방어력 +{1})",
                ["sword_dodge_counter"] = "회피 후 반격!",

                // === Spear Skill Messages ===
                ["spear_dual_strike"] = "이연창! ({0}초간 공격력 +{1}%)",
                ["spear_lightning_shock"] = "번개 충격! ({0})",

                // === Staff Skill Messages ===
                ["staff_dual_cast_cooldown"] = "연속 발사 쿨타임: {0}초",
                ["staff_eitr_insufficient"] = "에이트르가 부족합니다 ({0} 필요)",
                ["staff_dual_cast_ready"] = "연속 발사 준비! ({0}초간)",
                ["staff_dual_cast_remaining"] = "연속 발사 준비됨 ({0}초)",
                ["staff_dual_cast_expired"] = "연속 발사 버프 만료",

                // ===== Config Descriptions =====
                // Sword Tree
                ["config_tier0_swordexpert_requiredpoints"] = "Tier 0: 검 전문가 (sword_expert) - 필요 포인트",
                ["config_tier0_swordexpert_damagebonus"] = "Tier 0: 검 전문가 (sword_expert) - 공격력 보너스 (%)",
                ["config_tier1_fastslash_requiredpoints"] = "Tier 1: 빠른 베기 (sword_step1_fastslash) - 필요 포인트",
                ["config_tier1_counterstance_requiredpoints"] = "Tier 1: 반격 자세 (sword_step1_counter) - 필요 포인트",
                ["config_tier1_fastslash_attackspeedbonus"] = "Tier 1: 빠른 베기 (sword_step1_fastslash) - 공격 속도 보너스 (%)",
                ["config_tier2_comboslash_requiredpoints"] = "Tier 2: 연속 베기 (sword_step2_comboslash) - 필요 포인트",
                ["config_tier2_comboslash_damagebonus"] = "Tier 2: 연속 베기 (sword_step2_comboslash) - 공격력 보너스 (%)",
                ["config_tier2_comboslash_buffduration"] = "Tier 2: 연속 베기 (sword_step2_comboslash) - 버프 지속시간 (초)",
                ["config_tier3_riposte_requiredpoints"] = "Tier 3: 칼날 되치기 (sword_step3_riposte) - 필요 포인트",
                ["config_tier3_riposte_damagebonus"] = "Tier 3: 칼날 되치기 (sword_step3_riposte) - 공격력 보너스 (고정값)",
                ["config_tier4_allinone_requiredpoints"] = "Tier 4: 공방일체 (sword_step3_allinone) - 필요 포인트",
                ["config_tier4_trueduel_requiredpoints"] = "Tier 4: 진검승부 (sword_step4_trueduel) - 필요 포인트",
                ["config_tier4_trueduel_attackspeedbonus"] = "Tier 4: 진검승부 (sword_step4_trueduel) - 공격 속도 보너스 (%)",
                ["config_tier5_parryrush_requiredpoints"] = "Tier 5: 패링 돌격 (sword_step5_defswitch) - 필요 포인트",
                ["config_tier5_parryrush_buffduration"] = "Tier 5: 패링 돌격 (sword_step5_defswitch) - 버프 지속시간 (초)",
                ["config_tier5_parryrush_damagebonus"] = "Tier 5: 패링 돌격 (sword_step5_defswitch) - 공격력 보너스 (%)",
                ["config_tier5_parryrush_pushdistance"] = "Tier 5: 패링 돌격 (sword_step5_defswitch) - 밀쳐내기 거리 (미터)",
                ["config_tier5_parryrush_staminacost"] = "Tier 5: 패링 돌격 (sword_step5_defswitch) - 스태미나 소모",
                ["config_tier5_parryrush_cooldown"] = "Tier 5: 패링 돌격 (sword_step5_defswitch) - 쿨타임 (초)",
                ["config_tier6_rushslash_requiredpoints"] = "Tier 6: 돌진 연속 베기 (sword_step5_finalcut) - 필요 포인트",
                ["config_tier6_rushslash_hit1damageratio"] = "Tier 6: 돌진 연속 베기 (sword_step5_finalcut) - 1타 데미지 배율 (%)",
                ["config_tier6_rushslash_hit2damageratio"] = "Tier 6: 돌진 연속 베기 (sword_step5_finalcut) - 2타 데미지 배율 (%)",
                ["config_tier6_rushslash_hit3damageratio"] = "Tier 6: 돌진 연속 베기 (sword_step5_finalcut) - 3타 데미지 배율 (%)",
                ["config_tier6_rushslash_initialdistance"] = "Tier 6: 돌진 연속 베기 (sword_step5_finalcut) - 초기 돌진 거리 (미터)",
                ["config_tier6_rushslash_sidedistance"] = "Tier 6: 돌진 연속 베기 (sword_step5_finalcut) - 측면 이동 거리 (미터)",
                ["config_tier6_rushslash_staminacost"] = "Tier 6: 돌진 연속 베기 (sword_step5_finalcut) - 스태미나 소모",
                ["config_tier6_rushslash_cooldown"] = "Tier 6: 돌진 연속 베기 (sword_step5_finalcut) - 쿨타임 (초)",
                ["config_tier6_rushslash_movespeed"] = "Tier 6: 돌진 연속 베기 (sword_step5_finalcut) - 이동 속도 (m/s)",
                ["config_tier6_rushslash_attackspeedbonus"] = "Tier 6: 돌진 연속 베기 (sword_step5_finalcut) - 공격 속도 보너스 (%)",

                // Bow Tree
                ["config_tier0_bowexpert_requiredpoints"] = "Tier 0: 활 전문가 (bow_expert) - 필요 포인트",
                ["config_tier1_focusedshot_requiredpoints"] = "Tier 1: 집중 사격 (bow_step2_focus) - 필요 포인트",
                ["config_tier2_multishotlv1_requiredpoints"] = "Tier 2: 멀티샷 Lv1 (bow_step2_multishot) - 필요 포인트",
                ["config_tier3_bowmastery_requiredpoints"] = "Tier 3: 활 숙련 (bow_step3_speedshot) - 필요 포인트",
                ["config_tier4_multishotlv2_requiredpoints"] = "Tier 4: 멀티샷 Lv2 (bow_step4_multishot_lv2) - 필요 포인트",
                ["config_tier5_precisionaim_requiredpoints"] = "Tier 5: 정밀 조준 (bow_step5_precision) - 필요 포인트",
                ["config_tier6_explosivearrow_requiredpoints"] = "Tier 6: 폭발 화살 (bow_step6_explosive) - 필요 포인트",
                ["config_tier2_multishotlv1_activationchance"] = "Tier 2: 멀티샷 Lv1 (bow_step2_multishot) - 발동 확률 (%)",
                ["config_tier4_multishotlv2_activationchance"] = "Tier 4: 멀티샷 Lv2 (bow_step4_multishot_lv2) - 발동 확률 (%)",
                ["config_tier2_multishot_additionalarrows"] = "Tier 2: 멀티샷 - 추가 화살 개수",
                ["config_tier2_multishot_arrowconsumption"] = "Tier 2: 멀티샷 - 화살 소비량 (0=추가 소비 없음)",
                ["config_tier2_multishot_damageperarrow"] = "Tier 2: 멀티샷 - 추가 화살당 데미지 (%)",
                ["config_tier0_bowexpert_damagebonus"] = "Tier 0: 활 전문가 (bow_expert) - 공격력 보너스 (%)",
                ["config_tier1_focusedshot_critbonus"] = "Tier 1: 집중 사격 (bow_step2_focus) - 치명타 보너스 (%)",
                ["config_tier3_speedshot_skillbonus"] = "Tier 3: 빠른 사격 (bow_step3_speedshot) - 활 스킬 보너스",
                ["config_tier3_silentshot_damagebonus"] = "Tier 3: 은밀한 사격 (bow_step3_silentshot) - 공격력 보너스 (고정값)",
                ["config_tier3_specialarrow_chance"] = "Tier 3: 특수 화살 (bow_step3_special) - 발동 확률 (%)",
                ["config_tier4_powershot_knockbackchance"] = "Tier 4: 강력한 사격 (bow_step4_powershot) - 넉백 확률 (%)",
                ["config_tier4_powershot_knockbackdistance"] = "Tier 4: 강력한 사격 (bow_step4_powershot) - 넉백 거리 (미터)",
                ["config_tier5_arrowrain_chance"] = "Tier 5: 화살비 (bow_step5_arrowrain) - 발동 확률 (%)",
                ["config_tier5_arrowrain_arrowcount"] = "Tier 5: 화살비 (bow_step5_arrowrain) - 추가 화살 개수",
                ["config_tier5_backstepshot_critbonus"] = "Tier 5: 백스텝 사격 (bow_step5_backstep) - 치명타 보너스 (%)",
                ["config_tier5_backstepshot_duration"] = "Tier 5: 백스텝 사격 (bow_step5_backstep) - 버프 지속시간 (초)",
                ["config_tier5_huntinginstinct_critbonus"] = "Tier 5: 사냥 본능 (bow_step5_instinct) - 치명타 보너스 (%)",
                ["config_tier5_precisionaim_critdamage"] = "Tier 5: 정밀 조준 (bow_step5_precision) - 치명타 데미지 (%)",
                ["config_tier6_critboost_damagebonus"] = "Tier 6: 크리티컬 부스트 (bow_step6_critboost) - 공격력 보너스 (%)",
                ["config_tier6_critboost_critchance"] = "Tier 6: 크리티컬 부스트 (bow_step6_critboost) - 치명타 확률 (%)",
                ["config_tier6_critboost_arrowcount"] = "Tier 6: 크리티컬 부스트 (bow_step6_critboost) - 화살 개수",
                ["config_tier6_critboost_cooldown"] = "Tier 6: 크리티컬 부스트 (bow_step6_critboost) - 쿨타임 (초)",
                ["config_tier6_critboost_staminacost"] = "Tier 6: 크리티컬 부스트 (bow_step6_critboost) - 스태미나 소모",
                ["config_tier6_explosivearrow_damagemultiplier"] = "Tier 6: 폭발 화살 (bow_step6_explosive) - 데미지 배율 (%)",
                ["config_tier6_explosivearrow_cooldown"] = "Tier 6: 폭발 화살 (bow_step6_explosive) - 쿨타임 (초)",
                ["config_tier6_explosivearrow_staminacost"] = "Tier 6: 폭발 화살 (bow_step6_explosive) - 스태미나 소모",
                ["config_tier6_explosivearrow_radius"] = "Tier 6: 폭발 화살 (bow_step6_explosive) - 폭발 범위 (미터)",

                // === Attack Tree (공격 전문가 트리) ===
                ["config_attack_tier0_required_points"] = "Tier 0: 공격 전문가 (attack_root) - 필요 포인트",
                ["config_attack_tier1_required_points"] = "Tier 1: 기본 공격 (atk_base) - 필요 포인트",
                ["config_attack_tier2_required_points"] = "Tier 2: 무기 특화 스킬 - 필요 포인트",
                ["config_attack_tier3_required_points"] = "Tier 3: 공격 강화 (atk_twohand_drain) - 필요 포인트",
                ["config_attack_tier4_required_points"] = "Tier 4: 세부 강화 (근접/정밀) - 필요 포인트",
                ["config_attack_tier4_ranged_required_points"] = "Tier 4: 원거리 강화 (atk_ranged_enhance) - 필요 포인트",
                ["config_attack_tier5_required_points"] = "Tier 5: 특수 스탯 (atk_special) - 필요 포인트",
                ["config_attack_tier6_required_points"] = "Tier 6: 최종 특화 스킬 - 필요 포인트",
                ["config_attack_tier0_damage_bonus"] = "[서버 동기화] Tier 0: 공격 전문가 (attack_root) - 모든 데미지 보너스 (%)",
                ["config_attack_tier2_melee_chance"] = "Tier 2: 근접 특화 (attack_step2_melee) - 보너스 발동 확률 (%)",
                ["config_attack_tier2_melee_damage"] = "Tier 2: 근접 특화 (attack_step2_melee) - 근접 데미지 (%)",
                ["config_attack_tier2_bow_chance"] = "Tier 2: 활 특화 (attack_step2_bow) - 보너스 발동 확률 (%)",
                ["config_attack_tier2_bow_damage"] = "Tier 2: 활 특화 (attack_step2_bow) - 활 데미지 (%)",
                ["config_attack_tier2_crossbow_chance"] = "Tier 2: 석궁 특화 (attack_step2_crossbow) - 강화 발동 확률 (%)",
                ["config_attack_tier2_crossbow_damage"] = "Tier 2: 석궁 특화 (attack_step2_crossbow) - 석궁 데미지 (%)",
                ["config_attack_tier2_staff_chance"] = "Tier 2: 지팡이 특화 (attack_step2_staff) - 속성 발동 확률 (%)",
                ["config_attack_tier2_staff_damage"] = "Tier 2: 지팡이 특화 (attack_step2_staff) - 지팡이 데미지 (%)",
                ["config_attack_tier3_physical_damage"] = "Tier 3: 기본 공격 (attack_step3_base) - 물리 데미지 보너스",
                ["config_attack_tier3_elemental_damage"] = "Tier 3: 기본 공격 (attack_step3_base) - 속성 데미지 보너스",
                ["config_attack_tier3_stat_bonus"] = "Tier 3: 공격 강화 (atk_twohand_drain) - 힘 & 지능 보너스",
                ["config_attack_tier3_twohand_physical"] = "Tier 3: 공격 강화 (atk_twohand_drain) - 물리 데미지 보너스",
                ["config_attack_tier3_twohand_elemental"] = "Tier 3: 공격 강화 (atk_twohand_drain) - 속성 데미지 보너스",
                ["config_attack_tier4_crit_chance"] = "Tier 4: 정밀 공격 (attack_step4_crit) - 크리티컬 확률 (%)",
                ["config_attack_tier4_melee_combo"] = "Tier 4: 근접 강화 (attack_step4_melee_enhance) - 2연타 콤보 보너스 (%)",
                ["config_attack_tier4_ranged_damage"] = "Tier 4: 원거리 강화 (attack_step4_ranged_enhance) - 원거리 데미지 보너스 (%)",
                ["config_attack_tier5_special_stat"] = "Tier 5: 특수 스탯 (attack_step5_special) - 특화 보너스",
                ["config_attack_tier6_crit_damage"] = "Tier 6: 약점 공격 (attack_step6_crit_damage) - 크리티컬 데미지 보너스 (%)",
                ["config_attack_tier6_twohand_bonus"] = "Tier 6: 양손 분쇄 (attack_step6_twohanded) - 양손 무기 데미지 보너스 (%)",
                ["config_attack_tier6_elemental"] = "Tier 6: 속성 공격 (attack_step6_elemental) - 속성 보너스 (활, 지팡이) (%)",
                ["config_attack_tier6_finisher"] = "Tier 6: 콤보 피니셔 (attack_step6_finisher) - 3연타 콤보 보너스 (%)"
            };
        }

        private static Dictionary<string, string> GetEnglish_AttackProduction()
        {
            return new Dictionary<string, string>
            {
                // === Attack Expert Tree - Skill Names ===
                ["attack_root_name"] = "Attack Expert",
                ["atk_base_name"] = "Basic Attack",
                ["atk_melee_bonus_name"] = "Melee Specialization",
                ["atk_bow_bonus_name"] = "Bow Specialization",
                ["atk_crossbow_bonus_name"] = "Crossbow Specialization",
                ["atk_staff_bonus_name"] = "Staff Specialization",
                ["atk_twohand_drain_name"] = "Attack Boost",
                ["atk_melee_crit_name"] = "Melee Enhancement",
                ["atk_crit_chance_name"] = "Precision Strike",
                ["atk_ranged_enhance_name"] = "Ranged Enhancement",
                ["atk_special_name"] = "Specialized Stats",
                ["atk_crit_dmg_name"] = "Weak Point Strike",
                ["atk_finisher_melee_name"] = "Combo Finisher",
                ["atk_twohand_crush_name"] = "Two-Hand Crush",
                ["atk_staff_mage_name"] = "Elemental Strike",

                // === Attack Expert Tree - Skill Descriptions (English) ===
                ["atk_base_desc"] = "Pierce attack +{0}, Fire attribute +1",
                ["atk_twohand_drain_desc"] = "Physical attack +{0}%, Elemental attack +{1}%",
                ["atk_ranged_enhance_desc"] = "Ranged weapon damage +{0}% (Crossbow, Bow, Staff)",
                ["atk_special_desc"] = "Crit chance +{0}%",

                // === Attack Expert Tree - Effect Texts (English) ===
                ["atk_base_effect"] = "💪 Basic Attack Learned!",
                ["atk_melee_bonus_effect"] = "⚔️ Melee Specialization Learned!",
                ["atk_twohand_drain_effect"] = "💪 Attack Boost!",
                ["atk_ranged_enhance_effect"] = "🏹 Ranged Enhancement!",
                ["atk_special_effect"] = "⭐ Specialized Stats! Crit chance +{0}%",
                ["atk_staff_mage_effect"] = "🔥 Elemental Strike!",

                // === Paladin Skill ===
                ["paladin_name"] = "Paladin",
                ["paladin_desc"] = "Holy Heal: Heal self and allies within {0}m",
                ["paladin_passive_desc"] = "One-handed melee damage +{0}%, Heal self and nearby allies (Y Key)",
                ["paladin_tooltip_desc"] = "Area ally HP {0}%/{1}s ({2}s), Self {3}% instant",
                ["paladin_passive_resistance"] = "Physical & Elemental resistance -{0}%",
                ["paladin_requirement"] = "One-handed melee equipped, Paladin class",
                ["paladin_required_item"] = "Eikthyr Trophy",
                ["paladin_tooltip_error"] = "Failed to load Paladin skill info",

                // === Common Tooltip Labels ===
                ["tooltip_description"] = "Description",
                ["tooltip_range"] = "Range",
                ["tooltip_cost"] = "Cost",
                ["tooltip_stamina"] = "Stamina",
                ["tooltip_eitr"] = "Eitr",
                ["tooltip_skill_type"] = "Skill Type",
                ["tooltip_job_active_y"] = "Job Active Skill - Y Key",
                ["tooltip_passive"] = "Passive",
                ["tooltip_cooldown"] = "Cooldown",
                ["tooltip_seconds"] = "s",
                ["tooltip_requirement"] = "Requirement",
                ["tooltip_confirmation"] = "Note",
                ["tooltip_job_limit"] = "Only 1 job selectable, Level 10+",
                ["tooltip_required_item"] = "Required Item",
                ["tooltip_max_targets"] = "Max Targets",
                ["tooltip_targets_unit"] = " targets",

                // === Melee Root Skill ===
                ["melee_skill_expert"] = "Melee Expert",
                ["melee_desc_expert"] = "Melee weapon damage +3 (fixed)",
                ["melee_root_effect"] = "Melee Expert acquired! Melee weapon damage +3",

                // === Ranged Root Skill ===
                ["ranged_skill_expert"] = "Ranged Expert",
                ["ranged_desc_expert"] = "Bow/Crossbow pierce +2, Staff/Wand fire attack +2",

                // === Production Skills ===
                ["production_skill_expert"] = "Production Expert",
                ["production_desc_expert"] = "50% chance +1 wood",
                ["novice_worker_name"] = "Novice Worker",
                ["novice_worker_desc"] = "25% chance +1 wood",
                ["woodcutting_lv2_name"] = "Woodcutting Lv2",
                ["woodcutting_lv2_desc"] = "25% chance +1 wood",
                ["woodcutting_lv3_name"] = "Woodcutting Lv3",
                ["woodcutting_lv3_desc"] = "35% chance +2 wood",
                ["woodcutting_lv4_name"] = "Woodcutting Lv4",
                ["woodcutting_lv4_desc"] = "45% chance +2 wood",
                ["gathering_lv2_name"] = "Gathering Lv2",
                ["gathering_lv2_desc"] = "25% chance +1 gathering (except wood)",
                ["gathering_lv3_name"] = "Gathering Lv3",
                ["gathering_lv3_desc"] = "35% chance +1 gathering (except wood)",
                ["gathering_lv4_name"] = "Gathering Lv4",
                ["gathering_lv4_desc"] = "40% chance +1 gathering (except wood)",
                ["mining_lv2_name"] = "Mining Lv2",
                ["mining_lv2_desc"] = "25% chance +1 ore",
                ["mining_lv3_name"] = "Mining Lv3",
                ["mining_lv3_desc"] = "25% chance +1 ore",
                ["mining_lv4_name"] = "Mining Lv4",
                ["mining_lv4_desc"] = "25% chance +1 ore",
                ["crafting_lv2_name"] = "Crafting Lv2",
                ["crafting_lv2_desc"] = "25% chance +1 upgrade, Max durability +25%",
                ["crafting_lv3_name"] = "Crafting Lv3",
                ["crafting_lv3_desc"] = "25% chance +1 upgrade, Max durability +25%",
                ["crafting_lv4_name"] = "Crafting Lv4",
                ["crafting_lv4_desc"] = "25% chance +1 upgrade, Max durability +25%",

                // === Production Skills - Effect Texts ===
                ["production_root_effect"] = "Production Expert acquired!",
                ["novice_worker_effect"] = "Novice Worker acquired!",
                ["woodcutting_lv2_effect"] = "Woodcutting Lv2 acquired!",
                ["woodcutting_lv3_effect"] = "Woodcutting Lv3 acquired! 35% chance +2 wood",
                ["woodcutting_lv4_effect"] = "Woodcutting Lv4 acquired! 45% chance +2 wood",
                ["gathering_lv2_effect"] = "Gathering Lv2 acquired!",
                ["gathering_lv3_effect"] = "Gathering Lv3 acquired! 35% chance +1 gathering!",
                ["gathering_lv4_effect"] = "Gathering Lv4 acquired! 40% chance +1 gathering!",
                ["mining_lv2_effect"] = "Mining Lv2 acquired!",
                ["mining_lv3_effect"] = "Mining Lv3 acquired!",
                ["mining_lv4_effect"] = "Mining Lv4 acquired! Bonus ore when using 25 silver!",
                ["crafting_lv2_effect"] = "Crafting Lv2 acquired!",
                ["crafting_lv3_effect"] = "Crafting Lv3 acquired!",
                ["crafting_lv4_effect"] = "Crafting Lv4 acquired! Crafting boost with silver sword+helmet!",

                // === Crossbow Skills ===
                ["crossbow_skill_expert"] = "Crossbow Expert",
                ["crossbow_rapid_fire_lv1_name"] = "Rapid Fire Lv1",
                ["crossbow_balance_name"] = "Balanced Aim",
                ["crossbow_rapid_name"] = "Quick Reload",
                ["crossbow_mark_name"] = "True Shot",
                ["crossbow_auto_reload_name"] = "Auto Reload",
                ["crossbow_rapid_fire_lv2_name"] = "Rapid Fire Lv2",
                ["crossbow_final_strike_name"] = "First Strike",
                ["crossbow_oneshot_name"] = "One Shot",

                // === Bow Skills ===
                ["bow_skill_expert"] = "Bow Expert",
                ["bow_focus_name"] = "Focused Shot",
                ["bow_multishot_lv1_name"] = "Multi-Shot Lv1",
                ["bow_proficiency_name"] = "Bow Proficiency",
                ["bow_basic_attack_name"] = "Basic Bow Attack",
                ["bow_multishot_lv2_name"] = "Multi-Shot Lv2",
                ["bow_instinct_name"] = "Hunter's Instinct",
                ["bow_precision_name"] = "Precision Aim",
                ["bow_penetration_name"] = "Silent Shot",
                ["bow_penetration_desc"] = "Damage +{0}",
                ["bow_explosive_name"] = "Explosive Arrow",

                // === Staff Skills ===
                ["staff_skill_expert_name"] = "Staff Expert",
                ["staff_focus_name"] = "Mental Focus",
                ["staff_stream_name"] = "Magic Flow",
                ["staff_amp_name"] = "Magic Amplification",
                ["staff_frost_name"] = "Frost Element",
                ["staff_fire_name"] = "Fire Element",
                ["staff_lightning_name"] = "Lightning Element",
                ["staff_luck_mana_name"] = "Lucky Mana",
                ["staff_dual_cast_name"] = "Rapid Barrage",
                ["staff_heal_name"] = "Heal",

                // === Ranged/Crossbow/Bow Descriptions ===
                ["ranged_root_desc"] = "Bow/Crossbow piercing +2, Staff/Wand fire attack +2",
                ["weapon_effect_note"] = "※ Active when {0} equipped",
                ["crossbow_expert_desc"] = "Crossbow damage +{0}%",
                ["crossbow_rapid_fire_desc"] = "{0}% chance to fire {1} shots (each {2}% damage, {3} bolts consumed)",
                ["crossbow_balance_desc"] = "On hit, {0}% chance to knockback ({1}m)",
                ["crossbow_rapid_desc"] = "Reload speed +{0}%",
                ["crossbow_mark_desc"] = "Critical chance fixed at 0%, but crossbow damage +{0}%",
                ["crossbow_auto_reload_desc"] = "On hit, {0}% chance for next reload 200% faster",
                ["crossbow_final_desc"] = "Critical damage +{0}%",
                ["crossbow_oneshot_desc"] = "Crossbow damage +{0}%, {1}s reload delay until next shot",
                ["bow_expert_desc"] = "Bow damage +{0}%",
                ["bow_focus_desc"] = "Critical chance +{0}%",
                ["bow_multishot_lv1_desc"] = "{0}% chance to fire 1 extra arrow (+3° angle)",
                ["bow_proficiency_desc"] = "Bow skill (proficiency) +{0}",
                ["bow_proficiency_note"] = "※ Bonus persists through death",
                ["bow_basic_attack_desc"] = "Bow damage +{0}",
                ["bow_multishot_lv2_desc"] = "{0}% chance to fire 2 extra arrows (+3° angle)",
                ["bow_instinct_desc"] = "Critical chance +{0}%",
                ["bow_precision_desc"] = "Critical damage +{0}%",

                // === Crossbow Additional Descriptions ===
                ["crossbow_rapid_fire_lv2_desc"] = "{0}% chance to fire {1} consecutive shots (each {2}% damage, {3} bolts consumed)",
                ["crossbow_rapid_fire_lv2_note"] = "※ Stacks with Lv1 chance",
                ["crossbow_final_strike_desc"] = "Extra {1}% damage to enemies with {0}%+ HP",

                // === Crossbow Skill Effect Messages ===
                ["crossbow_auto_reload_activated"] = "Auto Reload! (+{0}% speed)",
                ["crossbow_auto_reload_and_rapid_fire"] = "Auto Reload + Rapid Fire! ({0} shots)",
                ["crossbow_rapid_fire_activated"] = "Rapid Fire! ({0} shots)",

                // === Staff Full Descriptions ===
                ["staff_expert_full_desc"] = "Staff elemental damage +{0}%\nMaster staff and wand usage for higher magic damage\nRequirement: Staff or Wand equipped",
                ["staff_focus_full_desc"] = "Staff Eitr consumption -{0}%\nMental focus increases mana efficiency\nRequirement: Staff or Wand equipped",
                ["staff_stream_full_desc"] = "Max Eitr +{0}\nMaster magic flow to hold more mana\nRequirement: Staff or Wand equipped",
                ["staff_amp_full_desc"] = "{0}% chance: Elemental damage +{1}%\nEitr consumption +{2}% (debuff)\nFalls back to normal attack when Eitr is insufficient\nRequirement: Staff or Wand equipped",
                ["staff_amp_activated"] = "Magic Amplification activated!",
                ["staff_frost_full_desc"] = "Frost damage +{0}\nRequirement: Staff or Wand equipped",
                ["staff_fire_full_desc"] = "Fire damage +{0}\nRequirement: Staff or Wand equipped",
                ["staff_lightning_full_desc"] = "Lightning damage +{0}\nRequirement: Staff or Wand equipped",
                ["staff_luck_mana_full_desc"] = "{0}% chance for no Eitr cost\nLucky magic grants free spell casting\nRequirement: Staff or Wand equipped",
                ["staff_dual_cast_full_desc"] = "After R key buff, fires {0} additional magic projectiles (0.25s interval) on magic attack\nDamage: {1:F0}% of staff/wand\nCost: Eitr {2:F0}\nSkill Type: Active R Key\nWeapon: Staff\nCooldown: {3:F0}s\nRequirement: Staff or Wand equipped",
                ["staff_heal_full_desc"] = "Press H for instant healing in {0:F0}m radius from caster\nRestore {1}% of ally max HP instantly\nCost: Eitr {2:F0}\nSkill Type: Active H Key\nWeapon: Staff\nCooldown: {3:F0}s\nRequirement: Staff or Wand equipped",

                // === Ranged Skills - Effect Texts ===
                ["ranged_root_effect"] = "Ranged Expert acquired!",
                ["bow_multishot_lv1_effect"] = "Multi-Shot Lv1 acquired!",
                ["bow_multishot_lv2_effect"] = "Multi-Shot Lv2 acquired!",
                ["bow_proficiency_effect"] = "Bow Proficiency acquired! Bow skill +{0}",
                ["bow_explosive_desc"] = "Fire explosive arrow\nDamage: {0}% of bow damage\nStamina cost: {1}%\nCooldown: {2}s",

                // === Skill Activation Messages ===
                ["bow_equip_required"] = "You must equip a bow!",
                ["no_arrows"] = "No arrows!",
                ["cooldown_format"] = "Cooldown: {0}s",
                ["multishot_remaining_charges"] = "Multishot! (Charges left: {0})",
                ["multishot_cooldown_remaining"] = "Multishot cooldown: {0}s",
                ["multishot_completed"] = "Multishot completed!",
                ["multishot_ready"] = "Multishot ready! ({0} uses available)",
                ["archer_job_required"] = "Archer job required!",
                ["spear_penetrate_cooldown"] = "Piercing Spear cooldown ({0}s)",
                ["spear_penetrate_activated"] = "Piercing Spear activated! ({0}s)",
                ["staff_dual_cast_activated"] = "Rapid Barrage! Firing {0} additional projectiles",
                ["knife_assassin_heart_activated"] = "Assassin's Heart activated!",

                // === Sword Skill Messages ===
                ["sword_combo_3hit"] = "Sword Combo 3-Hit!",
                ["sword_expert_combo"] = "Sword Expert 2-Combo! (+{0}%)",
                ["sword_combo_slash"] = "Combo Slash! 3-Hit damage +{0}%",
                ["sword_counter_stance"] = "Counter Stance! ({0}s defense +{1}%)",
                ["sword_blade_counter"] = "Blade Counter! ({0}s damage +{1}%)",
                ["sword_offense_defense"] = "Offense-Defense! (Damage +{0}%, Defense +{1})",
                ["sword_dodge_counter"] = "Dodge Counter!",

                // === Spear Skill Messages ===
                ["spear_dual_strike"] = "Dual Strike! ({0}s damage +{1}%)",
                ["spear_lightning_shock"] = "Lightning Shock! ({0})",

                // === Staff Skill Messages ===
                ["staff_dual_cast_cooldown"] = "Rapid Barrage cooldown: {0}s",
                ["staff_eitr_insufficient"] = "Not enough Eitr ({0} required)",
                ["staff_dual_cast_ready"] = "Rapid Barrage ready! ({0}s)",
                ["staff_dual_cast_remaining"] = "Rapid Barrage ready ({0}s)",
                ["staff_dual_cast_expired"] = "Rapid Barrage buff expired",

                // ===== Config Descriptions =====
                // Sword Tree
                ["config_tier0_swordexpert_requiredpoints"] = "Tier 0: Sword Expert (sword_expert) - Required Points",
                ["config_tier0_swordexpert_damagebonus"] = "Tier 0: Sword Expert (sword_expert) - Damage Bonus (%)",
                ["config_tier1_fastslash_requiredpoints"] = "Tier 1: Fast Slash (sword_step1_fastslash) - Required Points",
                ["config_tier1_counterstance_requiredpoints"] = "Tier 1: Counter Stance (sword_step1_counter) - Required Points",
                ["config_tier1_fastslash_attackspeedbonus"] = "Tier 1: Fast Slash (sword_step1_fastslash) - Attack Speed Bonus (%)",
                ["config_tier2_comboslash_requiredpoints"] = "Tier 2: Combo Slash (sword_step2_comboslash) - Required Points",
                ["config_tier2_comboslash_damagebonus"] = "Tier 2: Combo Slash (sword_step2_comboslash) - Damage Bonus (%)",
                ["config_tier2_comboslash_buffduration"] = "Tier 2: Combo Slash (sword_step2_comboslash) - Buff Duration (sec)",
                ["config_tier3_riposte_requiredpoints"] = "Tier 3: Riposte (sword_step3_riposte) - Required Points",
                ["config_tier3_riposte_damagebonus"] = "Tier 3: Riposte (sword_step3_riposte) - Damage Bonus (flat)",
                ["config_tier4_allinone_requiredpoints"] = "Tier 4: All-In-One (sword_step3_allinone) - Required Points",
                ["config_tier4_trueduel_requiredpoints"] = "Tier 4: True Duel (sword_step4_trueduel) - Required Points",
                ["config_tier4_trueduel_attackspeedbonus"] = "Tier 4: True Duel (sword_step4_trueduel) - Attack Speed Bonus (%)",
                ["config_tier5_parryrush_requiredpoints"] = "Tier 5: Parry Rush (sword_step5_defswitch) - Required Points",
                ["config_tier5_parryrush_buffduration"] = "Tier 5: Parry Rush (sword_step5_defswitch) - Buff Duration (sec)",
                ["config_tier5_parryrush_damagebonus"] = "Tier 5: Parry Rush (sword_step5_defswitch) - Damage Bonus (%)",
                ["config_tier5_parryrush_pushdistance"] = "Tier 5: Parry Rush (sword_step5_defswitch) - Push Distance (meters)",
                ["config_tier5_parryrush_staminacost"] = "Tier 5: Parry Rush (sword_step5_defswitch) - Stamina Cost",
                ["config_tier5_parryrush_cooldown"] = "Tier 5: Parry Rush (sword_step5_defswitch) - Cooldown (sec)",
                ["config_tier6_rushslash_requiredpoints"] = "Tier 6: Rush Slash (sword_step5_finalcut) - Required Points",
                ["config_tier6_rushslash_hit1damageratio"] = "Tier 6: Rush Slash (sword_step5_finalcut) - Hit 1 Damage Ratio (%)",
                ["config_tier6_rushslash_hit2damageratio"] = "Tier 6: Rush Slash (sword_step5_finalcut) - Hit 2 Damage Ratio (%)",
                ["config_tier6_rushslash_hit3damageratio"] = "Tier 6: Rush Slash (sword_step5_finalcut) - Hit 3 Damage Ratio (%)",
                ["config_tier6_rushslash_initialdistance"] = "Tier 6: Rush Slash (sword_step5_finalcut) - Initial Dash Distance (meters)",
                ["config_tier6_rushslash_sidedistance"] = "Tier 6: Rush Slash (sword_step5_finalcut) - Side Movement Distance (meters)",
                ["config_tier6_rushslash_staminacost"] = "Tier 6: Rush Slash (sword_step5_finalcut) - Stamina Cost",
                ["config_tier6_rushslash_cooldown"] = "Tier 6: Rush Slash (sword_step5_finalcut) - Cooldown (sec)",
                ["config_tier6_rushslash_movespeed"] = "Tier 6: Rush Slash (sword_step5_finalcut) - Movement Speed (m/s)",
                ["config_tier6_rushslash_attackspeedbonus"] = "Tier 6: Rush Slash (sword_step5_finalcut) - Attack Speed Bonus (%)",

                // Bow Tree
                ["config_tier0_bowexpert_requiredpoints"] = "Tier 0: Bow Expert (bow_expert) - Required Points",
                ["config_tier1_focusedshot_requiredpoints"] = "Tier 1: Focused Shot (bow_step2_focus) - Required Points",
                ["config_tier2_multishotlv1_requiredpoints"] = "Tier 2: Multishot Lv1 (bow_step2_multishot) - Required Points",
                ["config_tier3_bowmastery_requiredpoints"] = "Tier 3: Bow Mastery (bow_step3_speedshot) - Required Points",
                ["config_tier4_multishotlv2_requiredpoints"] = "Tier 4: Multishot Lv2 (bow_step4_multishot_lv2) - Required Points",
                ["config_tier5_precisionaim_requiredpoints"] = "Tier 5: Precision Aim (bow_step5_precision) - Required Points",
                ["config_tier6_explosivearrow_requiredpoints"] = "Tier 6: Explosive Arrow (bow_step6_explosive) - Required Points",
                ["config_tier2_multishotlv1_activationchance"] = "Tier 2: Multishot Lv1 (bow_step2_multishot) - Activation Chance (%)",
                ["config_tier4_multishotlv2_activationchance"] = "Tier 4: Multishot Lv2 (bow_step4_multishot_lv2) - Activation Chance (%)",
                ["config_tier2_multishot_additionalarrows"] = "Tier 2: Multishot - Additional Arrows Count",
                ["config_tier2_multishot_arrowconsumption"] = "Tier 2: Multishot - Arrow Consumption (0=no extra consumption)",
                ["config_tier2_multishot_damageperarrow"] = "Tier 2: Multishot - Damage Per Additional Arrow (%)",
                ["config_tier0_bowexpert_damagebonus"] = "Tier 0: Bow Expert (bow_expert) - Damage Bonus (%)",
                ["config_tier1_focusedshot_critbonus"] = "Tier 1: Focused Shot (bow_step2_focus) - Critical Bonus (%)",
                ["config_tier3_speedshot_skillbonus"] = "Tier 3: Speed Shot (bow_step3_speedshot) - Bow Skill Bonus",
                ["config_tier3_silentshot_damagebonus"] = "Tier 3: Silent Shot (bow_step3_silentshot) - Damage Bonus (flat)",
                ["config_tier3_specialarrow_chance"] = "Tier 3: Special Arrow (bow_step3_special) - Activation Chance (%)",
                ["config_tier4_powershot_knockbackchance"] = "Tier 4: Power Shot (bow_step4_powershot) - Knockback Chance (%)",
                ["config_tier4_powershot_knockbackdistance"] = "Tier 4: Power Shot (bow_step4_powershot) - Knockback Distance (meters)",
                ["config_tier5_arrowrain_chance"] = "Tier 5: Arrow Rain (bow_step5_arrowrain) - Activation Chance (%)",
                ["config_tier5_arrowrain_arrowcount"] = "Tier 5: Arrow Rain (bow_step5_arrowrain) - Additional Arrows Count",
                ["config_tier5_backstepshot_critbonus"] = "Tier 5: Backstep Shot (bow_step5_backstep) - Critical Bonus (%)",
                ["config_tier5_backstepshot_duration"] = "Tier 5: Backstep Shot (bow_step5_backstep) - Buff Duration (sec)",
                ["config_tier5_huntinginstinct_critbonus"] = "Tier 5: Hunting Instinct (bow_step5_instinct) - Critical Bonus (%)",
                ["config_tier5_precisionaim_critdamage"] = "Tier 5: Precision Aim (bow_step5_precision) - Critical Damage (%)",
                ["config_tier6_critboost_damagebonus"] = "Tier 6: Crit Boost (bow_step6_critboost) - Damage Bonus (%)",
                ["config_tier6_critboost_critchance"] = "Tier 6: Crit Boost (bow_step6_critboost) - Critical Chance (%)",
                ["config_tier6_critboost_arrowcount"] = "Tier 6: Crit Boost (bow_step6_critboost) - Arrow Count",
                ["config_tier6_critboost_cooldown"] = "Tier 6: Crit Boost (bow_step6_critboost) - Cooldown (sec)",
                ["config_tier6_critboost_staminacost"] = "Tier 6: Crit Boost (bow_step6_critboost) - Stamina Cost",
                ["config_tier6_explosivearrow_damagemultiplier"] = "Tier 6: Explosive Arrow (bow_step6_explosive) - Damage Multiplier (%)",
                ["config_tier6_explosivearrow_cooldown"] = "Tier 6: Explosive Arrow (bow_step6_explosive) - Cooldown (sec)",
                ["config_tier6_explosivearrow_staminacost"] = "Tier 6: Explosive Arrow (bow_step6_explosive) - Stamina Cost",
                ["config_tier6_explosivearrow_radius"] = "Tier 6: Explosive Arrow (bow_step6_explosive) - Explosion Radius (meters)",

                // === Attack Tree ===
                ["config_attack_tier0_required_points"] = "Tier 0: Attack Expert (attack_root) - Required Points",
                ["config_attack_tier1_required_points"] = "Tier 1: Base Attack (atk_base) - Required Points",
                ["config_attack_tier2_required_points"] = "Tier 2: Weapon Specialization Skills - Required Points",
                ["config_attack_tier3_required_points"] = "Tier 3: Attack Boost (atk_twohand_drain) - Required Points",
                ["config_attack_tier4_required_points"] = "Tier 4: Detail Enhancement (Melee/Precision) - Required Points",
                ["config_attack_tier4_ranged_required_points"] = "Tier 4: Ranged Enhancement (atk_ranged_enhance) - Required Points",
                ["config_attack_tier5_required_points"] = "Tier 5: Specialized Stats (atk_special) - Required Points",
                ["config_attack_tier6_required_points"] = "Tier 6: Final Specialization Skills - Required Points",
                ["config_attack_tier0_damage_bonus"] = "[Server Sync] Tier 0: Attack Expert (attack_root) - All Damage Bonus (%)",
                ["config_attack_tier2_melee_chance"] = "Tier 2: Melee Spec (attack_step2_melee) - Bonus Trigger Chance (%)",
                ["config_attack_tier2_melee_damage"] = "Tier 2: Melee Spec (attack_step2_melee) - Melee Damage (%)",
                ["config_attack_tier2_bow_chance"] = "Tier 2: Bow Spec (attack_step2_bow) - Bonus Trigger Chance (%)",
                ["config_attack_tier2_bow_damage"] = "Tier 2: Bow Spec (attack_step2_bow) - Bow Damage (%)",
                ["config_attack_tier2_crossbow_chance"] = "Tier 2: Crossbow Spec (attack_step2_crossbow) - Enhance Trigger Chance (%)",
                ["config_attack_tier2_crossbow_damage"] = "Tier 2: Crossbow Spec (attack_step2_crossbow) - Crossbow Damage (%)",
                ["config_attack_tier2_staff_chance"] = "Tier 2: Staff Spec (attack_step2_staff) - Elemental Trigger Chance (%)",
                ["config_attack_tier2_staff_damage"] = "Tier 2: Staff Spec (attack_step2_staff) - Staff Damage (%)",
                ["config_attack_tier3_physical_damage"] = "Tier 3: Base Attack (attack_step3_base) - Physical Damage Bonus",
                ["config_attack_tier3_elemental_damage"] = "Tier 3: Base Attack (attack_step3_base) - Elemental Damage Bonus",
                ["config_attack_tier3_stat_bonus"] = "Tier 3: Attack Boost (atk_twohand_drain) - Strength & Intelligence Bonus",
                ["config_attack_tier3_twohand_physical"] = "Tier 3: Attack Boost (atk_twohand_drain) - Physical Damage Bonus",
                ["config_attack_tier3_twohand_elemental"] = "Tier 3: Attack Boost (atk_twohand_drain) - Elemental Damage Bonus",
                ["config_attack_tier4_crit_chance"] = "Tier 4: Precision Attack (attack_step4_crit) - Crit Chance (%)",
                ["config_attack_tier4_melee_combo"] = "Tier 4: Melee Enhancement (attack_step4_melee_enhance) - 2-Hit Combo Bonus (%)",
                ["config_attack_tier4_ranged_damage"] = "Tier 4: Ranged Enhancement (attack_step4_ranged_enhance) - Ranged Damage Bonus (%)",
                ["config_attack_tier5_special_stat"] = "Tier 5: Specialized Stats (attack_step5_special) - Specialization Bonus",
                ["config_attack_tier6_crit_damage"] = "Tier 6: Weak Point Attack (attack_step6_crit_damage) - Crit Damage Bonus (%)",
                ["config_attack_tier6_twohand_bonus"] = "Tier 6: Two-Hand Crush (attack_step6_twohanded) - Two-Handed Weapon Damage Bonus (%)",
                ["config_attack_tier6_elemental"] = "Tier 6: Elemental Attack (attack_step6_elemental) - Elemental Bonus (Bow, Staff) (%)",
                ["config_attack_tier6_finisher"] = "Tier 6: Combo Finisher (attack_step6_finisher) - 3-Hit Combo Bonus (%)"
            };
        }
    }
}
