using System.Collections.Generic;

namespace CaptainSkillTree.Localization
{
    public static partial class DefaultLanguages
    {
        private static Dictionary<string, string> GetKorean_JobExpert()
        {
            return new Dictionary<string, string>
            {
                // === Expert Tree Skill Descriptions ===
                // Attack Expert Tree
                ["attack_root_desc"] = "모든 공격력 +{0}% (물리, 속성)",
                ["atk_melee_bonus_desc"] = "근접 무기 사용 시 공격 +{0}%",
                ["atk_bow_bonus_desc"] = "활 사용 시 공격력 +{0}%",
                ["atk_crossbow_bonus_desc"] = "석궁 사용 시 공격 +{0}%",
                ["atk_staff_bonus_desc"] = "지팡이 또는 완드 사용 시 공격 +{0}%",
                ["atk_crit_chance_desc"] = "치명타 확률 +{0}%",
                ["atk_melee_crit_desc"] = "한손 근접무기 2연속 공격 시 +{0}% 추가 피해",
                ["atk_twohand_crush_desc"] = "양손 무기 공격력 +{0}%",
                ["atk_staff_mage_desc"] = "지팡이 공격 시 속성 공격 +{0}%",
                ["atk_finisher_melee_desc"] = "한손 무기 공격력 +{0}%",

                // Defense Expert Tree - Names
                ["defense_root_name"] = "방어 전문가",
                ["defense_survival_name"] = "피부경화",
                ["defense_dodge_name"] = "심신단련",
                ["defense_health_name"] = "체력단련",
                ["defense_breath_name"] = "단전호흡",
                ["defense_agile_name"] = "회피단련",
                ["defense_boost_name"] = "체력증강",
                ["defense_shield_name"] = "막기훈련",
                ["defense_mental_name"] = "충격파방출",
                ["defense_mental_desc"] = "생명력 45% 이하 시 {0}m 이내 적 {1}초간 기절 (쿨타임 {2}초)",
                ["defense_instant_name"] = "발구르기",
                ["defense_instant_desc"] = "생명력 35% 이하 시 주변 적 {0}m 밀어냄 (쿨타임 {1}초)",
                ["defense_tanker_name"] = "바위피부",
                ["defense_focus_name"] = "지구력",
                ["defense_stamina_name"] = "기민함",
                ["defense_heal_name"] = "트롤의 재생력",
                ["defense_parry_name"] = "막기달인",
                ["defense_mind_name"] = "마인드쉴드",
                ["defense_mind_short_desc"] = "에이트르 최대치만큼 피해를 흡수하는 보호막 활성화",
                ["defense_mind_desc"] = "G키로 에이트르 최대치만큼 피해를 흡수하는 보호막 활성화\n보호막 유지 시간: {0}초\n소모: Eitr {1}\n스킬유형: 액티브 G키\n무기타입: 지팡이 또는 완드\n쿨타임: {2:F0}초\n필요조건: 지팡이 또는 완드 착용",
                ["defense_mind_full_desc"] = "G키로 에이트르 최대치만큼 피해를 흡수하는 보호막 활성화\n보호막 유지 시간: {0}초\n소모: Eitr {1}\n스킬유형: 액티브 G키\n무기타입: 지팡이 또는 완드\n쿨타임: {2:F0}초\n필요조건: 지팡이 또는 완드 착용",
                ["defense_mind_effect"] = "마인드쉴드 습득!",
                ["mind_shield_activate"] = "마인드쉴드 발동!",
                ["mind_shield_eitr_insufficient"] = "에이트르가 부족합니다.",
                ["mind_shield_cooldown"] = "마인드쉴드 쿨타임 중",
                ["defense_attack_name"] = "신경강화",
                ["defense_double_jump_name"] = "이단점프",
                ["defense_double_jump_desc"] = "공중에서 추가로 {0}회 점프",
                ["defense_body_name"] = "요툰의 생명력",

                // Defense Expert Tree - Descriptions
                ["defense_root_desc"] = "체력 +{0}, 투구 방어력 +{1}, 공격력 -{2}%",
                ["defense_survival_desc"] = "체력 +{0}, 흉갑 방어력 +{1}",
                ["defense_health_desc"] = "체력 +{0}, 각반 방어력 +{1}",
                ["defense_dodge_desc"] = "스태미나 최대치 +{0}, 에이트르 최대치 +{1}",
                ["defense_breath_desc"] = "에이트르 최대치 +{0}",
                ["defense_agile_desc"] = "회피 +{0}%, 구르기 무적시간 +{1}%",
                ["defense_boost_desc"] = "체력 +{0}",
                ["defense_shield_desc"] = "방패 방어력 +{0}\n패링 성공 시 막기력 x{1}% 타격 + {2}m 밀어내기\n쿨타임 없음 / 스태미나 소모 없음",
                ["defense_tanker_desc"] = "방어력 +{0}%",
                ["defense_focus_desc"] = "달리기 스태미나 -{0}%, 점프 스태미나 -{1}%",
                ["defense_stamina_desc"] = "회피 +{0}%, 구르기 스태미나 -{1}%",
                ["defense_heal_desc"] = "{0}초마다 체력 +{1}",
                ["defense_parry_desc"] = "패링 +{0}초, 방패 방어력 +{1}",
                ["defense_attack_desc"] = "30초 동안 피격 회피 미발동 시 회피 +{0}%",
                ["defense_body_desc"] = "체력 최대치 +{0}%, 물리/속성 저항 +{1}%",

                // Defense Expert Tree - Effect Texts
                ["defense_root_effect"] = "🛡️ 방어 전문가! 체력 +{0}, 방어 +{1}, 공격력 -{2}%",
                ["defense_shield_effect"] = "🛡️ 막기훈련! 방패 방어력 +{0}",
                ["defense_shield_parry_counter"] = "⚔️ 패링 반격! ({0} 타격)",
                ["defense_parry_effect"] = "🛡️ 막기달인! 패링 +{0}초, 방패 방어력 +{1}",
                ["defense_body_effect"] = "🛡️ 요툰의 생명력! 체력 +{0}%, 저항 +{1}%",

                // Staff Expert Tree
                ["staff_expert_desc"] = "속성 공격 +{0}%",
                ["staff_focus_desc"] = "에이트르 소모 -{0}%",
                ["staff_stream_desc"] = "최대 에이트르 +{0}",
                ["staff_frost_desc"] = "냉기 공격 +{0}",
                ["staff_fire_desc"] = "화염 공격 +{0}",
                ["staff_lightning_desc"] = "번개 공격 +{0}",
                ["staff_luck_mana_desc"] = "{0}% 확률로 에이트르 소모 없음",

                // Mace Expert Tree (additional)
                ["mace_expert_desc2"] = "둔기 피해 +{0}%, 공격 시 {1}% 확률로 {2}초 기절",
                ["mace_stun_boost_desc2"] = "기절 확률 +{0}%, 지속시간 +{1}초",
                ["mace_guard_boost_desc2"] = "세컨드 공격 시 공격력 +{0}%, 범위 {1}m, 넉백 {2}m",
                ["mace_heavy_strike_desc2"] = "무거운 공격 타격 +{0}",
                ["mace_knockback_desc2"] = "둔기로 공격 시 {0}% 확률로 대상의 이동속도와 공격속도를 1.5초간 30% 감소",
                ["mace_tank_desc2"] = "체력 +{0}%, 받는 데미지 -{1}%",
                ["mace_dps_desc2"] = "공격력 +{0}%",
                ["mace_grandmaster_desc2"] = "공격속도 +{0}%",

                // === Producer Job Keys ===
                ["job_producer"] = "제작 전문가",
                ["job_producer_short"] = "제작사",
                ["job_change_announce"] = "{0}님이 {1}(으)로 전직하였습니다.",
                ["producer_buff_desc"] = "{0}초간 공격력+{1}%, 최대체력+{2}% 버프 (15m 내 파티원)",
                ["producer_buff_applied"] = "✨ 장인의 축복 발동!",
                ["producer_passive_lv1"] = "내구도+{0}%, 제작 마법부여 {1}% 확률",
                ["producer_passive_lv2"] = "내구도+{0}%, 재료-{1}%, 제작 마법부여 {2}% 확률",
                ["producer_passive_lv3"] = "내구도+{0}%, 재료-{1}%, 제작 마법부여 {2}% 확률",
                ["producer_passive_lv4"] = "내구도+{0}%, 재료-{1}%, 제작 마법부여 {2}% 확률",
                ["producer_passive_lv5"] = "내구도+{0}%, 재료-{1}%, 제작 마법부여 {2}% 확률",
                ["producer_enchant_detail_lv3"] = "  └ 무기: 공격력+5% 또는 공속+5%\n  └ 방어구: 방어력+5% 또는 체력+2% 또는 스테미나+5%",
                ["producer_enchant_detail_lv4"] = "  └ 무기: 공격력+7~9% 또는 공속+7~9%\n  └ 방어구: 방어력+7~9% 또는 체력+4~5% 또는 스테미나+6~8%",
                ["producer_enchant_detail_lv5"] = "  └ 무기: 공격력+10~12% 또는 공속+10~12%\n  └ 방어구: 방어력+10~12% 또는 체력+6~8% 또는 스테미나+9~12%",
                ["producer_enchant_weapon_dmg"] = "✨ 제작 축복: 공격력 +{0}%",
                ["producer_enchant_armor"] = "✨ 제작 축복: 방어력 +{0}%",
                ["producer_enchant_hp"] = "✨ 제작 축복: 체력 +{0}%",
                ["producer_enchant_notify"] = "✨ 제작 축복 적용!",
                ["producer_level_req_items"] = "Lv{0} 달성 재료",
                ["producer_level_item_required"] = "제작 전문가 Lv{0} 전직 트로피가 부족합니다",
                ["producer_max_level"] = "★ 최대 레벨 달성!",
                ["requirement_job_producer"] = "직업: 제작 전문가",
                ["item_trophy_bear"] = "곰 트로피",
                ["farmgrid_planted"] = "씨앗 {0}개 추가 식재",
                ["farmgrid_no_seeds"] = "씨앗 부족",
                ["farmgrid_spacing"] = "격자 간격: {0}",
                ["farmgrid_rotation"] = "경작 각도: {0}",
                ["producer_enchant_weapon_spd"] = "✨ 제작 축복: 공격속도 +{0}%",
                ["producer_enchant_stamina"]    = "✨ 제작 축복: 스태미나 +{0}",
                // 신규 마법부여 키 (v1.2.095)
                ["producer_enchant_stamina_pct"]     = "✨ 제작 축복: 스태미나 +{0}%",
                ["producer_enchant_bow_crit"]         = "✨ 제작 축복: 활 치명타 +{0}%",
                ["producer_enchant_crossbow_reload"]  = "✨ 제작 축복: 재장전 속도 +{0}%",
                ["producer_enchant_cooldown_reduce"]  = "✨ 제작 축복: 스킬 쿨타임 -{0}%",
                ["producer_enchant_dodge_roll"]       = "✨ 제작 축복: 회피 스태미나 -{0}%",
                ["producer_enchant_move_speed"]       = "✨ 제작 축복: 이동속도 +{0}%",
                ["producer_enchant_eitr"]             = "✨ 제작 축복: 에이트르 +{0}",
                ["producer_enchant_inv_weight"]       = "✨ 제작 축복: 인벤 무게 +{0}",
                ["producer_enchant_eitr_regen"]       = "✨ 제작 축복: 에이트르 회복 +{0}%",
                ["producer_enchant_jump_force"]       = "✨ 제작 축복: 점프력 +{0}%",
                ["producer_enchant_block_power"]      = "✨ 제작 축복: 가드 방어력 +{0}%",
                // 무기별 차별화 마법부여 키 (속성 확률 피해)
                ["producer_enchant_fire_proc"]         = "✨ 제작 축복: 화염 피해 확률 +{0}%",
                ["producer_enchant_spirit_proc"]       = "✨ 제작 축복: 영혼 피해 확률 +{0}%",
                ["producer_enchant_poison_proc"]       = "✨ 제작 축복: 독 피해 확률 +{0}%",
                ["producer_enchant_lightning_proc"]    = "✨ 제작 축복: 번개 피해 확률 +{0}%",
                ["producer_enchant_frost_proc"]        = "✨ 제작 축복: 냉기 피해 확률 +{0}%",
                ["producer_enchant_polearm_range"]     = "✨ 제작 축복: 사거리 +{0}%",

                // === Prerequisite Text ===
                ["prerequisite_label"] = "🔗 필요",
                ["prerequisite_connector_or"] = " 또는 ",
                ["prerequisite_labor_craft"] = "노가다 전문가 + 제작 전문가",
                ["or_separator"] = "또는",
                ["skill_prerequisite_any_required"] = "선행 스킬 중 하나 이상 필요: {0}",

                // === Weapon Requirement Conditions ===
                ["requirement_bow_effect"] = "활 착용",
                ["requirement_crossbow_effect"] = "석궁 착용",
                ["requirement_staff_effect"] = "지팡이 착용",
                ["requirement_sword_effect"] = "검 착용",
                ["requirement_axe_effect"] = "도끼 착용",
                ["requirement_knife_effect"] = "단검 착용",
                ["requirement_spear_effect"] = "창 착용",
                ["requirement_mace_effect"] = "둔기 착용",
                ["requirement_one_hand_melee_effect"] = "한손 근접무기 착용",

                // === MMO Bridge Messages ===
                ["mmo_level_recovery_complete"] = "레벨 데이터 복구 완료!",
                ["mmo_level_recovery_detail"] = "Lv.{0} → Lv.{1}",
                ["mmo_captain_to_epic_complete"] = "Captain -> EpicMMO 마이그레이션 완료!",
                ["mmo_captain_to_epic_detail"] = "Lv.{0} -> Lv.{1}",
                ["mmo_skillpoint_sync_complete"] = "스킬포인트 -> EpicMMO 동기화 완료!",
                ["mmo_skillpoint_sync_detail"] = "Lv.{0} -> Lv.{1}",
                ["mmo_epic_to_captain_complete"] = "EpicMMO -> Captain 데이터 복구 완료!",
                ["mmo_epic_to_captain_detail"] = "Lv.{0}",
                ["level_up_message"] = "<color=green>레벨 업!</color>\n+{0} 스킬포인트 (Lv.{1})",
                ["mmo_level_sync_message"] = "<color=#00BFFF>Lv.{0} / 스킬포인트. {1}</color>",

                // === Job Skill Messages ===
                ["job_no_job_selected"] = "직업을 선택하지 않았습니다.",
                ["job_one_hand_melee_required"] = "한손 근접무기를 착용해야 합니다!",
                ["job_holy_heal_cooldown"] = "신성한 치유 쿨타임: {0}초",
                ["job_stamina_required"] = "스태미나가 부족합니다 ({0} 필요)",
                ["job_eitr_required"] = "에이트르가 부족합니다 ({0} 필요)",
                ["job_self_heal"] = "✨ 자가 치유: +{0} HP",
                ["job_paladin_heal_success"] = "⭐ 성기사 신성한 치유! (자가치유 + {0}명 지속힐)",
                ["job_continuous_heal_start"] = "🌟 지속 치유 시작!",
                ["job_continuous_heal_tick"] = "💚 지속 치유: +{0} HP",
                ["job_continuous_heal_progress"] = "💚 지속 치유: +{0} HP ({1}/{2})",
                ["job_continuous_heal_complete"] = "✨ 지속 치유 완료!",
                ["job_skill_error"] = "스킬 시전 중 오류가 발생했습니다.",

                // === Paladin Level System ===
                ["paladin_upgrade_msg"] = "⚔️ 성기사 Lv{0}로 업그레이드 하였습니다.",
                ["paladin_level_req_items"] = "Lv{0} 달성 재료",
                ["paladin_level_item_required"] = "성기사 Lv{0} 전직 트로피가 부족합니다",
                ["paladin_max_level"] = "★ 최대 레벨 달성!",
                ["paladin_missing_items"] = "부족한 재료: {0}",
                ["item_deficit_fmt"] = "{0}가 부족합니다",
                ["coin_deficit_fmt"] = "코인 x{0}이 부족합니다",
                ["paladin_upgrade_title"] = "⚔️ 성기사 레벨업",
                ["paladin_upgrade_confirm"] = "성기사 Lv{0}으로 업그레이드합니까?\n트로피가 소모됩니다.",
                ["paladin_lv2_skill_required"] = "분노의 망치 또는 돌진베기 스킬을 배워야 합니다",
                ["paladin_active_desc"] = "자가 {0}% 즉시 회복, 주변 아군 {1}%/틱 x{2}초 치유",
                ["paladin_passive_lv1"] = "적이 받는 데미지 +{0}% 증가",
                ["paladin_passive_lv2"] = "최대 스태미나 +{0}, 적이 받는 데미지 +{1}% 증가, 보유 스킬 30초 내 추가 사용",
                ["paladin_passive_lv3"] = "최대 스태미나 +{0}, 적이 받는 데미지 +{1}% 증가",
                ["paladin_passive_lv4"] = "최대 스태미나 +{0}, 적이 받는 데미지 +{1}% 증가",
                ["paladin_passive_lv5"] = "최대 스태미나 +{0}, 적이 받는 데미지 +{1}% 증가",

                // === Rogue Skill Messages ===
                ["rogue_shadow_strike_cooldown"] = "그림자 일격 쿨타임: {0}초",
                ["rogue_stamina_insufficient"] = "스태미나가 부족합니다.",
                ["rogue_shadow_strike_success"] = "🗡️ 그림자 일격! (독성 폭발 8회 + {0}초간 데미지 +{1}%)",
                ["rogue_shadow_strike_end"] = "그림자 일격 종료",
                ["rogue_dagger_required"] = "단검 또는 발톱이 필요합니다",
                ["rogue_buff_end"] = "그림자 일격 버프 종료!",
                ["rogue_smoke"] = "연막!",
                ["rogue_shadow_strike_no_enemy"] = "그림자 일격! (주변에 적 없음)",

                // === Mage Skill Messages ===
                ["mage_explosion_cooldown"] = "마법 폭발 쿨타임: {0}초",
                ["mage_eitr_insufficient"] = "에이트르가 부족합니다.",
                ["mage_explosion_success"] = "🔮 마법 폭발! ({0}초간 마법 데미지 +{1}%, 범위 +{2}m)",
                ["mage_explosion_end"] = "마법 폭발 종료",
                // === Fire Rain (불의 비) ===
                ["mage_firerain_cast"] = "🔥 불의 비 시전! 타겟: {0}",
                ["mage_desc_firerain"] = "전방 타겟팅 불의 비(Fire Rain)로 공격한다.",
                ["mage_firerain_damage"] = "파이어볼 {0}개 × 3버스트 (무기 공격력 {1}%)",
                ["mage_firerain_range"] = "낙하 반경 {0}m, 적중 범위 {1}m",
                ["mage_dungeon_buff_desc"] = "던전 안에서는 불의 비 대신 공격력 {0}%를 {1}초 동안 강화하는 버프로 발동됩니다",
                ["mage_dungeon_buff_cast"] = "공격력 강화! (+{0}%, {1}초)",
                // === Mage Level System ===
                ["mage_passive_lv1"] = "AOE 데미지 {0}%, 쿨타임 {2}초, 속성 저항 {1}%",
                ["mage_passive_lv2"] = "AOE 데미지 {0}%, 쿨타임 {2}초, 다중시전 +1회 (30초 이내), 속성 저항 {1}%",
                ["mage_level_req_items"] = "Lv{0} 달성 재료",
                ["mage_level_item_required"] = "메이지 Lv{0} 전직 트로피가 부족합니다",
                ["mage_missing_items"] = "부족한 재료: {0}",
                ["mage_max_level"] = "★ 최대 레벨 달성!",
                ["mage_upgrade_msg"] = "🔮 메이지 Lv{0}로 업그레이드 하였습니다.",
                ["mage_upgrade_title"] = "🔮 메이지 레벨업",
                ["mage_upgrade_confirm"] = "메이지 Lv{0}으로 업그레이드합니까?\n트로피가 소모됩니다.",
                ["item_missing_msg"] = "{0}이 부족합니다",
                ["item_trophy_surtling"] = "슈르트링 트로피",
                ["item_trophy_wraith"] = "망령 트로피",

                // === Archer Skill Messages ===
                ["archer_multishot_cooldown"] = "멀티샷 쿨타임: {0}초",
                ["archer_stamina_insufficient"] = "스태미나 부족",
                ["archer_multishot_success"] = "🏹 멀티샷! ({0}발 발사)",
                ["archer_bow_required"] = "활을 착용해야 합니다!",
                ["archer_no_arrow"] = "화살이 없습니다!",
                ["archer_job_required"] = "아처 직업이 필요합니다!",
                ["archer_cooldown"] = "쿨다운: {0}초",

                // === Berserker Skill Messages ===
                ["berserker_rage_end"] = "버서커의 분노 종료",

                // === Tanker Skill Messages ===
                ["tanker_defense_buff_activated"] = "<color=#FFD700>⚔ 방어 버프 활성화! ⚔</color>",
                ["tanker_shield_required"] = "방패 착용이 필요합니다",
                ["stamina_insufficient"] = "스태미나가 부족합니다",

                // === Tanker Level-Up System ===
                ["tanker_upgrade_title"] = "탱커 업그레이드",
                ["tanker_upgrade_confirm"] = "Lv{0}으로 업그레이드합니까?",
                ["tanker_max_level"] = "★ 탱커 최대 레벨 달성!",
                ["tanker_level_item_required"] = "탱커 Lv{0} 업그레이드 재료가 부족합니다",
                ["tanker_missing_items"] = "부족한 재료: {0}",
                ["tanker_lv2_skill_prereq_required"] = "분노의 망치 / 돌진베기 / 패링돌격 / 방패돌진 / 꿰뚫는창 / 연공창 / 관통 돌격 중 1개를 배워야 합니다",
                ["tanker_lv2_skill_required"] = "분노의 망치 / 돌진베기 / 패링돌격 / 방패돌진 / 꿰뚫는창 / 연공창 / 관통 돌격 중 1개 배우고 30초 이내 사용 필요",
                ["tanker_lv2_recent_use_required"] = "배운 스킬을 30초 이내 1회 사용 후 업그레이드 할 수 있습니다",
                ["tanker_level_req_items"] = "Lv{0} 필요 아이템",
                ["tanker_taunt_effect"] = "도발 {0}m, {1}초",
                ["tanker_passive_lv1"] = "생명력 +{0}%, 피해감소 {1}%, 피격시 {2}초간 반사 누적({3}%·{4}m 폭발)",
                ["tanker_passive_lv2"] = "추가 체력 +{0}%, 피해감소 {1}%, 방패 막기 방어력 +{2}, 피격시 {3}초간 반사 누적({4}%·{5}m 폭발), 배운 선행 스킬(꿰뚫는창/연공창/분노의 망치/돌진베기/패링돌격/방패돌진/관통돌격) 30초 내 +1회 사용",
                ["tanker_passive_lv3"] = "생명력 +{0}%, 피해감소 {1}%, 방패 막기 방어력 +{2}, 피격시 {3}초간 반사 누적({4}%·{5}m 폭발)",
                ["tanker_reflect_activated"] = "🛡️ 분노 누적 시작!",
                ["tanker_reflect_damage"] = "🛡️ 도발 반사: {0}",
                ["tanker_reflect_info"] = "버프 종료 시 누적 피해의 {0}% 화염 폭발 ({1}m)",
                ["tanker_reflect_explosion"] = "🔥 분노 폭발: {0} x{1}적",

                // === Rogue Active Skill Messages ===
                ["rogue_shadow_strike_activate"] = "💥 그림자 일격!",

                // === Skill Effect Messages ===
                ["skill_activated"] = "{0} 발동!",
                ["ground_stomp_effect"] = "발구르기! ({0}명 밀어냄)",
                ["stomp_30sec_remaining"] = "🦶 발구르기 30초 후 준비!",
                ["stomp_ready"] = "🦶 발구르기 준비완료!",
                ["shockwave_30sec_remaining"] = "⚡ 충격파방출 30초 후 준비!",
                ["shockwave_ready"] = "⚡ 충격파방출 준비완료!",
                ["luck_magic_activated"] = "✨ 행운 마력 발동!",
                ["staff_wand_required"] = "❌ 지팡이나 완드를 착용해야 합니다!",

                // === Combat Effect Messages ===
                ["consecutive_attack"] = "연속 공격!",
                ["critical_strike"] = "치명적 일격!",
                ["enhanced_strike"] = "강화된 일격! (+{0}%)",
                ["reflect_damage"] = "반사 데미지 {0}!",
                ["explosion_damage"] = "폭발! +{0}",

                // === Spear Effect Messages ===
                ["spear_expert_damage"] = "창 전문가 공격력! (+{0}%)",
                ["evasion_thrust"] = "회피 찌르기! (+{0}%)",
                ["evasion_thrust_ready"] = "회피 찌르기 준비!",
                ["evasion_thrust_end"] = "회피 찌르기 종료",
                ["explosion_spear"] = "빠른창! 공격 속도 +{0}%",

                // === Polearm Effect Messages ===
                ["polearm_area_combo"] = "광역 강타! 2연속 공격력 +{0}%",
                ["polearm_cooldown_remaining"] = "쿨타임: {0}초 남음",
                ["polearm_stamina_insufficient"] = "스태미나 부족!",
                ["polearm_required"] = "폴암을 착용해야 합니다!",
                ["pierce_charge_in_progress"] = "관통 돌격 실행 중",
                ["pierce_charge"] = "관통 돌격!",
                ["pierce_charge_damage"] = "관통 돌격! (+{0}%)",
                ["charge_complete"] = "돌진 완료",
                ["hero_strike_stagger"] = "영웅 타격! (스태거)",
                ["wheel_attack"] = "휠 공격 +{0}%!",

                // === Sword Effect Messages ===
                ["rush_slash_skill_required"] = "돌진 연속 베기 스킬이 필요합니다",
                ["sword_required"] = "검을 착용해야 합니다",
                ["cooldown_remaining"] = "쿨타임: {0}초",
                ["rush_slash_in_progress"] = "돌진 연속 베기 실행 중",
                ["rush_slash_activate"] = "돌진 연속 베기!",
                ["rush_slash_return"] = "원래 위치로 복귀!",
                ["rush_slash_complete"] = "돌진 연속 베기 완료! ({0}타격)",
                ["rush_slash_canceled"] = "돌진 연속 베기 중단됨",
                ["rush_slash_1st_attack"] = "⚔️ 1차 베기! ({0}%)",
                ["rush_slash_2nd_attack"] = "⚔️ 2차 베기! ({0}%)",
                ["rush_slash_finisher"] = "💥 피니셔! ({0}%)",
                ["rush_slash_default"] = "⚔️ 베기! ({0}%)",
                ["parry_rush_skill_required"] = "회전베기 스킬이 필요합니다",
                ["shield_required"] = "방패를 착용해야 합니다",
                ["sword_or_shield_required"] = "검 또는 방패를 착용해야 합니다",
                ["parry_rush_already_active"] = "회전베기가 이미 시전 중입니다",
                ["parry_rush_activate"] = "패링 돌격! ({0}초)",
                ["parry_rush_buff_name"] = "패링 돌격",
                ["parry_rush_damage"] = "⚔️ 회전베기 {0}차! (+{1}%)",

                // === Berserker Effect Messages ===
                ["berserker_cooldown"] = "쿨다운 중 ({0}초)",
                ["stamina_insufficient_short"] = "스태미나 부족!",
                ["already_rage_state"] = "이미 분노 상태!",
                ["berserker_rage"] = "버서커 분노!",
                ["death_ignore"] = "죽음의 무시",
                ["berserker_ranged_30pct"] = "(원거리 공격력은 30%만 적용)",

                // === Berserker Lv1~5 레벨업 시스템 ===
                ["berserker_upgrade_msg"] = "버서커 Lv{0} 달성!",
                ["berserker_active_desc"] = "분노: 쿨{0}초, 지속{1}초, 줄어든 HP 1%당 공격력 {2}%증가",
                ["berserker_passive_lv1"] = "죽음의 무시: 체력+{0}, 스태미나 리젠+20%, {1}% 이하 {2}초 무적({3}분 쿨)",
                ["berserker_passive_lv2"] = "체력+{0}, Lv1 + 분노의 망치/돌진베기/관통 돌격 30초 추가 사용 가능",
                ["berserker_passive_lv3"] = "체력+{0}, Lv2 + 분노 쿨타임·지속시간 추가 개선",
                ["berserker_passive_lv4"] = "체력+{0}, Lv3 + 분노 쿨타임·지속시간 추가 개선",
                ["berserker_passive_lv5"] = "체력+{0}, Lv4 + 분노 쿨타임·지속시간 추가 개선",
                ["berserker_max_level"] = "★ 최대 레벨 달성!",
                ["berserker_level_req_items"] = "Lv{0} 달성 재료",
                ["berserker_level_item_required"] = "버서커 Lv{0} 업그레이드 재료가 부족합니다",
                ["berserker_lv2_skill_prereq_required"] = "Lv2 조건 미충족: 분노의 망치 / 돌진 연속 베기 / 관통 돌격 중 1개 이상 필요",
                ["berserker_missing_items"] = "부족한 재료: {0}",
                ["berserker_rage_damage_display"] = "🔥 추가 데미지 +{0}% 🔥",
                ["berserker_passive_cd_ms"] = "🛡️ 패시브 무적 쿨타임: {0}분 {1:00}초",
                ["berserker_passive_cd_s"] = "🛡️ 패시브 무적 쿨타임: {0}초",
                ["berserker_upgrade_title"] = "🪓 버서커 레벨업",
                ["berserker_upgrade_confirm"] = "버서커 Lv{0}으로 업그레이드합니까?\n트로피가 소모됩니다.",

                // === Staff Heal Effect Messages ===
                ["heal_cooldown"] = "힐 쿨타임: {0}초",
                ["sacred_heal"] = "지팡이 신성한 치유! ({0}명 치료)",
                ["no_heal_target"] = "치료할 대상이 없습니다",

                // === Resource Consumption Messages ===
                ["equipment_consumed"] = "장비 소모: {0}",
                ["material_consumed"] = "재료 소모: {0}",

                // === Skill Tree Manager Messages ===
                ["cannot_learn_with"] = "{0}과(와) 동시에 배울 수 없습니다",
                ["active_skill_ranged_only_one"] = "원거리 액티브 스킬은 1개만 선택 가능합니다",
                ["active_skill_weapon_conflict"] = "다른 무기의 액티브 스킬이 이미 선택되어 있습니다",
                ["active_skill_job_only_one"] = "직업 액티브 스킬은 1개만 선택 가능합니다",
                ["job_class_one_only"] = "직업은 1개만 선택 가능합니다",
                ["multishot_end"] = "멀티샷 종료",

                // === Taunt Messages ===
                ["taunt_ready"] = "도발 준비 완료!",

                // === Attack Expert Tree Effect Messages ===
                ["rage_bonus"] = "추가 데미지 +{0}%",
                ["melee_specialization"] = "근접 특화!",
                ["bow_specialization"] = "활 특화!",
                ["focus_fire_crit"] = "집중 사격 치명타 x{0}!",
                ["basic_bow_damage"] = "기본 활공격 +{0}!",
                ["crossbow_specialization"] = "석궁 특화!",
                ["one_shot"] = "단 한 발! +{0}%",
                ["staff_specialization"] = "지팡이 특화!",
                ["precision_attack"] = "정밀 공격!",
                ["elemental_attack"] = "속성 공격!",
                ["ranged_enhance"] = "원거리 강화!",
                ["attack_expert"] = "공격 전문가!",
                ["melee_enhance"] = "근접 강화!",
                ["consecutive_melee_master"] = "연속 근접의 대가!",
                ["energizer"] = "에너자이져!",
                ["attack_increased"] = "공격 증가!",
                ["attack_expert_acquired"] = "공격 전문가 습득!",

                // === Speed Tree Effect Messages ===
                ["consecutive_flow"] = "연속의 흐름!",
                ["bow_expert_mastery"] = "활 숙련자!",
                ["crossbow_expert_mastery"] = "석궁 숙련자!",
                ["agility_base"] = "민첩함의 기초! (+{0}% 이동속도)",
                ["melee_triple_combo"] = "근접 가속 3연속! (+{0}% 공격속도)",
                ["cast_triple_combo"] = "시전 가속 3연속! (+{0} 에이트르)",
                ["knockback_effect"] = "넉백!",

                // === Bow/Crossbow Effect Messages ===
                ["multishot_skill"] = "멀티샷 {0}! (+{1}발)",
                ["explosive_arrow_skill_required"] = "폭발 화살 스킬이 필요합니다",
                ["explosive_arrow_ready"] = "폭발 화살 준비 완료!",
                ["explosive_arrow_fire"] = "폭발 화살 발사!",

                // === JobSkills Messages ===
                ["archer_multishot_cooldown"] = "멀티샷 쿨타임: {0}초",
                ["archer_multishot_fired"] = "멀틴샷! ({0}발 발사)",

                // === Level Up Message ===
                ["level_up"] = "LEVEL UP!",

                // === Speed Expert Tree - Skill Names ===
                ["speed_root_name"] = "속도 전문가",
                ["speed_base_name"] = "민첩함의 기초",
                ["melee_combo_name"] = "연속의 흐름",
                ["crossbow_reload2_name"] = "석궁 숙련자",
                ["bow_speed2_name"] = "활 숙련자",
                ["moving_cast_name"] = "이동 시전",
                ["speed_ex1_name"] = "수련자1",
                ["speed_ex2_name"] = "수련자2",
                ["speed_master_name"] = "에너자이져",
                ["ship_master_name"] = "선 장",
                ["agility_peak_name"] = "점프 숙련자",
                ["speed_1_name"] = "민첩",
                ["speed_2_name"] = "지구력",
                ["speed_3_name"] = "지능",
                ["all_master_name"] = "숙련자",
                ["melee_speed1_name"] = "근접 가속",
                ["crossbow_draw1_name"] = "석궁 가속",
                ["bow_draw1_name"] = "활 가속",
                ["staff_speed1_name"] = "시전 가속",

                // === Speed Expert Tree - Skill Descriptions ===
                ["speed_root_desc"] = "이동속도 +{0}%/레벨 (최대 Lv7)",
                ["speedroot_item_required"] = "Lv{0} 강화에 트로피가 필요합니다",
                ["speedroot_missing_items"] = "부족한 재료: {0}",
                ["speedroot_max_level"] = "최대 레벨 도달",
                ["speedroot_trophy_required"] = "강화 필요: {0} x5",
                ["speedroot_upgrade_requires"] = "Lv{0} 강화 재료",
                ["speed_root_stat_preview"] = "이동속도 +{0}%",
                ["speed_base_desc"] = "공격속도 +{0}%, 구르기 후 {1}초간 이동속도 +{2}%",
                ["melee_combo_desc"] = "근접 2연속 적중 시 {0}초간 공격속도 +{1}%, 스태미나 -{2}%",
                ["crossbow_reload2_desc"] = "석궁 적중 시 이동속도 +{0}%({1}초), 버프 중 재장전 +{2}%",
                ["bow_speed2_desc"] = "활 2연속 적중 시 스태미나 -{0}%, 다음 장전 +{1}%",
                ["moving_cast_desc"] = "마법 시전 중 이동속도 +{0}%, 에이트르 소모 -{1}%",
                ["speed_ex1_desc"] = "근접무기 숙련 +{0}, 석궁 숙련 +{1}",
                ["speed_ex2_desc"] = "마법 숙련 +{0}, 활 숙련 +{1}",
                ["speed_master_desc"] = "음식 소모 속도 -{0}%",
                ["ship_master_desc"] = "배 운전시 속도 +{0}%",
                ["agility_peak_desc"] = "점프 숙련 +{0}, 점프 스태미나 -{1}%",
                ["speed_1_desc"] = "근접 공격속도 +{0}%, 이동속도 +{1}%",
                ["speed_2_desc"] = "스태미나 최대치 +{0}",
                ["speed_3_desc"] = "에이트르 최대치 +{0}",
                ["all_master_desc"] = "달리기 숙련 +{0}, 점프 숙련 +{1}",
                ["melee_speed1_desc"] = "근접 공격속도 +{0}%, 3연속 공격 시 공격속도 +{1}%",
                ["crossbow_draw1_desc"] = "석궁 재장전 +{0}%, 재장전 중 이동속도 +{1}%",
                ["bow_draw1_desc"] = "활 장전 +{0}%, 장전 중 이동속도 +{1}%",
                ["staff_speed1_desc"] = "마법 공격속도 +{0}%, 3연속 적중 시 에이트르 최대치의 {1}% 회복",

                // === Speed Expert Tree - Effect Texts ===
                ["speed_root_effect"] = "🏃 속도 전문가 투자 완료! (+{0}% 이동속도)",
                ["speed_base_effect"] = "🏃 민첩함의 기초 습득!\n공격속도 +{0}%\n구르기 후 이동속도 +{1}%",
                ["speed_ex1_effect"] = "⚔️ 수련자1 습득! 근접/석궁 숙련도 +{0}",
                ["speed_ex2_effect"] = "🏹 수련자2 습득! 지팡이/활 숙련도 +{0}",
                ["all_master_effect"] = "🏃 숙련자 습득! 달리기/점프 숙련도 +{0}",
                ["agility_peak_effect"] = "🦘 점프 숙련자 습득! 점프 숙련도 +{0}",

                // === Archer Tooltip Keys ===
                ["archer_level_req_items"] = "Lv{0} 필요아이템",
                ["archer_preview_arrows_damage"] = "추가 발사체 +{0}, 1발당 공격력 {1}%",
                ["archer_preview_charges"] = "추가 발사 회수 +{0}",
                ["archer_job_requirement"] = "활 착용, 아처 직업",

                // === Rogue Job ===
                ["rogue_desc_shadow_strike"] = "독폭발 {0}회, 범위 {1}m",
                ["rogue_desc_attack_bonus"] = "{0}초간 공격력 +{1}%",
                ["rogue_passive_desc"] = "공격 속도 +{0}%, 스태미나 사용 -{1}%, 회피율 +{2}%",
                ["requirement_rogue"] = "단검 또는 발톱 장착, 로그 직업",
                ["rogue_passive_lv1"] = "공격속도 +{0}%, 스태미나 -{1}%, 회피율 +{2}%, 이동속도 +{3}%",
                ["rogue_passive_lv2"] = "공격속도 +{0}%, 스태미나 -{1}%, 회피율 +{2}%, 이동속도 +{3}%",
                ["rogue_passive_lv3"] = "공격속도 +{0}%, 스태미나 -{1}%, 회피율 +{2}%, 이동속도 +{3}%",
                ["rogue_passive_lv4"] = "공격속도 +{0}%, 스태미나 -{1}%, 회피율 +{2}%, 이동속도 +{3}%",
                ["rogue_passive_lv5"] = "공격속도 +{0}%, 스태미나 -{1}%, 회피율 +{2}%, 이동속도 +{3}%",
                ["rogue_effect_strike"] = "공격력버프 {0}% ({1}초), 독폭발 {2}회",
                ["rogue_preview_attack"] = "공격력버프 +{0}%, 독폭발 +{1}회",
                ["rogue_tooltip_title"] = "로그 - 그림자의 일격",
                ["rogue_preview_charges"] = "그림자 일격 충전 +{0}회",
                ["rogue_preview_poison"] = "독데미지: 즉시 +{0}%, DoT +{1}%/s",
                ["rogue_poison_info"] = "독 범위 {0}m │ 즉시 {1}% │ 초당 {2}%",
                ["rogue_preview_cd"] = "쿨다운 {1}초 (lv1 -{0}초)",
                ["rogue_max_level"] = "★ 최대 레벨 달성!",
                ["rogue_level_req_items"] = "Lv{0} 필요아이템",
                ["rogue_charges_display"] = "{0}회 충전",
                ["rogue_lv2_unlock_cond"] = "암살자의 심장 스킬 해금 필요",
                ["archer_lv2_unlock_cond"] = "단 한 발 또는 폭발화살 스킬 중 하나 필요",
                ["archer_lv2_extra_charge_effect"] = "단 한 발/폭발화살: 30초 이내 1회 추가 사용",
                ["mage_lv2_unlock_cond"] = "다중시전 스킬 해금 필요",
                ["rogue_level_item_required"] = "로그 Lv{0} 업그레이드 재료가 부족합니다",

                // === UI 메시지 ===
                ["skill_acquired_count"] = "✅ {0}개 스킬 습득 완료!",
                ["skill_acquired_name"]  = "🌟 {0} 습득!",

                // === 아이템 표시명 ===
                ["item_coins"] = "코인",
            };
        }

    }
}
