using System.Collections.Generic;

namespace CaptainSkillTree.Localization
{
    public static partial class DefaultLanguages
    {
        private static Dictionary<string, string> GetEnglish_Quest()
        {
            return new Dictionary<string, string>
            {
                ["quest_button_label"] = "Quest",
                ["quest_panel_title"] = "Quests",
                ["quest_completed_title"] = "Quest Objective Complete!",
                ["quest_completed_detail_kill"] = "Defeated {0} x{1} — quest complete! Claim your reward in the Quest window.",
                ["quest_completed_detail_gather"] = "Gathered {0} x{1} — quest complete! Claim your reward in the Quest window.",
                ["quest_completed_detail_plant"] = "Planted {0} crops — quest complete! Claim your reward in the Quest window.",
                ["quest_completed_detail_plant_distinct"] = "Planted {0} different crop types — quest complete! Claim your reward in the Quest window.",
                ["quest_completed_detail_cook"] = "Cooked {0} meals — quest complete! Claim your reward in the Quest window.",
                ["quest_completed_detail_cook_distinct"] = "Cooked {0} different meal types — quest complete! Claim your reward in the Quest window.",
                ["quest_completed_detail_fish"] = "Caught {0} fish — quest complete! Claim your reward in the Quest window.",
                ["quest_completed_detail_fish_distinct"] = "Caught {0} different fish species — quest complete! Claim your reward in the Quest window.",
                ["quest_reward_jump_proficiency"] = "Jump Proficiency +10 (Permanent)",
                ["quest_reward_tame_wolf"] = "Tamed Wolf Cub",
                ["quest_reward_stamina_bonus"] = "Max Stamina +10 (Permanent)",
                ["quest_reward_elemental_damage"] = "Elemental Damage +2% (Permanent)",
                ["quest_reward_physical_damage"] = "Physical Damage +1% (Permanent)",
                ["quest_reward_farming_skill"] = "Farming Skill +{0}",
                ["quest_reward_cooking_skill"] = "Cooking Skill +{0}",
                ["quest_reward_fishing_skill"] = "Fishing Skill +{0}",
                ["quest_reward_melee_weapon_skill"] = "Melee Weapon Skill +{0} (Permanent)",
                ["quest_reward_ranged_weapon_skill"] = "Bow/Crossbow Skill +{0} (Permanent)",
                ["quest_status_completed"] = "Complete",
                ["quest_status_claimed"] = "Claimed",
                ["quest_claim_button"] = "Reward",
                ["quest_coin_label"] = "Coin",
                ["quest_tooltip_progress"] = "Progress",
                ["quest_reward_tame_lox"] = "Tamed Lox Calf",
                ["quest_reward_random_item"] = "1 of: {0}",
                ["quest_type_gather"] = "Gather",
                ["quest_type_kill"] = "Kill",
                ["quest_type_kill_boss"] = "Boss",
                ["quest_type_special"] = "Special",
                ["quest_type_farm"] = "Farm",
                ["quest_type_cook"] = "Cook",
                ["quest_type_fish"] = "Fish",
                ["quest_label_farm_count"] = "Plant {0} Crops",
                ["quest_label_farm_distinct"] = "Plant {0} Different Crop Types",
                ["quest_label_cook_count"] = "Cook {0} Meals",
                ["quest_label_cook_distinct"] = "Cook {0} Different Meal Types",
                ["quest_label_fish_count"] = "Catch {0} Fish",
                ["quest_label_fish_distinct"] = "Catch {0} Different Fish Species",
                ["quest_label_mountain_melee_only"] = "Defeat Moder Using Only Melee Weapons",
                ["quest_label_mountain_ranged_only"] = "Defeat Moder Using Only Ranged Weapons (Bow, Crossbow, Magic)",
                ["quest_biome_Life"] = "Life",
                ["quest_biome_Meadows"] = "Meadows",
                ["quest_biome_BlackForest"] = "Black Forest",
                ["quest_biome_Swamp"] = "Swamp",
                ["quest_biome_Mountain"] = "Mountain",
                ["quest_biome_Plains"] = "Plains",
                ["quest_biome_Mistlands"] = "Mistlands",
                ["quest_biome_Ashlands"] = "Ashlands",

                // Per-quest flavor description (mouse-hover tooltip only)
                ["quest_desc_Meadows_Quest1"] = "Deer have overrun the Meadows, and hunters are coming up empty-handed. Thin the herd for hide and meat.",
                ["quest_desc_Meadows_Quest2"] = "Necks are swarming the riverbanks, scaring off every fisherman in sight. Clear them out and keep the flint.",
                ["quest_desc_Meadows_Quest3"] = "A pack of wild boars keeps trampling the farmland. Hunt them down for their leather scraps.",
                ["quest_desc_Meadows_Quest4"] = "Eikthyr, guardian of the Meadows, has grown restless. Prove yourself against the forest's first power.",
                ["quest_desc_Meadows_Quest5"] = "Word is that a fresh batch of ripe raspberries could be traded for a new queen bee.",
                ["quest_desc_Meadows_Quest6"] = "Face Eikthyr without eating a single bite of food and without taking a single hit. Only a true master can pull this off.",
                ["quest_desc_BlackForest_Quest1"] = "Greydwarves swarm the edge of the Black Forest. Thin them out and gather some fine wood.",
                ["quest_desc_BlackForest_Quest2"] = "The Greydwarf infestation has gotten out of hand. A larger cull will earn you troll hide.",
                ["quest_desc_BlackForest_Quest3"] = "A troll is uprooting trees and hurling them through the forest. Take it down and recover its surtling cores.",
                ["quest_desc_BlackForest_Quest4"] = "Bjorn the bear is prowling the hunting grounds, scaring off every other beast. Hunt it for tin ore.",
                ["quest_desc_BlackForest_Quest5"] = "The Elder, guardian of the Black Forest, has spread its roots too far. Bring the ancient tree down.",
                ["quest_desc_BlackForest_Quest7"] = "Set aside your bow, crossbow, and magic — approach the Elder with nothing but a melee weapon.",
                ["quest_desc_Swamp_Quest1"] = "An Abomination stomps through the swamp, crushing anyone in its path. Take it down for an iron pickaxe.",
                ["quest_desc_Swamp_Quest2"] = "Draugr risen from the crypts have overrun the swamp. A massive purge will yield plenty of guck.",
                ["quest_desc_Swamp_Quest3"] = "Wraiths stalk the swamp after dark, hunting anything still breathing. Hunt them down and recover their cores.",
                ["quest_desc_Swamp_Quest4"] = "Blobs spreading across the swamp are fouling the water. Clear them out for their surtling cores.",
                ["quest_desc_Swamp_Quest5"] = "Deep in the swamp, the rotting mass known as Bonemass has stirred. Put the corrupted guardian down.",
                ["quest_desc_Swamp_Quest7"] = "Set aside your blade and arrows — bring down Bonemass using magic alone.",
                ["quest_desc_Mountain_Quest1"] = "A Stone Golem is smashing boulders and blocking the mountain pass. Bring it down and recover its silver ore.",
                ["quest_desc_Mountain_Quest2"] = "Wolf packs have overrun the mountains, threatening every traveler. A large hunt will toughen your stamina.",
                ["quest_desc_Mountain_Quest3"] = "Frost-bitten Fenrings stalk prey through the blizzards. Hunt them down and collect their cores.",
                ["quest_desc_Mountain_Quest4"] = "Moder reigns from the mountain peak, breathing frost over all below. Slay the dragon for its silver ore.",
                ["quest_desc_Mountain_Quest5"] = "Fear neither frost breath nor claws. Face Moder with nothing but sword, axe, club, spear, polearm, or knife. Using a ranged weapon or magic even once during the fight will fail the challenge.",
                ["quest_desc_Mountain_Quest6"] = "Keep your distance. Bring Moder down from the sky using only bow, crossbow, or magic. Using a melee weapon even once during the fight will fail the challenge.",
                ["quest_desc_Plains_Quest1"] = "Fuling Shamans are casting curses across the Plains. Cut them down and absorb their elemental power.",
                ["quest_desc_Plains_Quest2"] = "Goblins have set up camps all across the Plains. A large-scale purge will yield their totems.",
                ["quest_desc_Plains_Quest3"] = "A Goblin Brute is leading a wolf pack while swinging its club. Defeat it and you may tame a wolf cub.",
                ["quest_desc_Plains_Quest4"] = "Lox herds shake the ground as they roam the Plains. Hunt enough of them and you may tame a calf.",
                ["quest_desc_Plains_Quest5"] = "Yagluth, king of the goblins, seeks to rule the Plains. End his last stand for good.",
                ["quest_desc_Mistlands_Quest1"] = "Seeker Soldiers patrol the Mistlands, driving off any intruder. Cut them down and recover their soft tissue.",
                ["quest_desc_Mistlands_Quest2"] = "Seekers leap from the mist to ambush travelers. Hunt them down to hone your physical strength.",
                ["quest_desc_Mistlands_Quest3"] = "A Gjall drifts overhead, scattering explosive spores below. Shoot it down and recover its tissue.",
                ["quest_desc_Mistlands_Quest4"] = "Deep in the Mistlands, the Seeker Queen breeds an endless swarm. Put an end to her reign.",
                ["quest_desc_Ashlands_Quest1"] = "Fallen Valkyries slice through the ashen sky, hunting intruders. Bring them down and recover their cores.",
                ["quest_desc_Ashlands_Quest2"] = "Asksvin roam the lava fields, carrying bell fragments on their hides. Hunt them down and collect the pieces.",
                ["quest_desc_Ashlands_Quest3"] = "Morgens lurk in the shadows, waiting to ambush travelers. Hunt them down for their black cores.",
                ["quest_desc_Ashlands_Quest4"] = "Fader, the last calamity of the Ashlands, has awakened. Claim victory in this final battle.",

                // Monster/resource names (item_wood already exists in DefaultLanguages_WeaponSkills.cs)
                ["item_neck"] = "Neck",
                ["item_boar"] = "Boar",
                ["item_eikthyr"] = "Eikthyr",
                ["item_raspberry"] = "Raspberry",
                ["item_copperore"] = "Copper Ore",
                ["item_greydwarf"] = "Greydwarf",
                ["item_greydwarf_elite"] = "Greydwarf Brute",
                ["item_troll"] = "Troll",
                ["item_helmettrollleather"] = "Troll Leather Helmet",
                ["item_armortrollleatherchest"] = "Troll Leather Chest",
                ["item_armortrollleatherlegs"] = "Troll Leather Legs",
                ["item_helmetbronze"] = "Bronze Helmet",
                ["item_armorbronzechest"] = "Bronze Chest",
                ["item_armorbronzelegs"] = "Bronze Legs",
                ["item_helmetiron"] = "Iron Helmet",
                ["item_armorironchest"] = "Iron Chest",
                ["item_armorironlegs"] = "Iron Legs",
                ["item_helmetdrake"] = "Drake Helmet",
                ["item_armorwolfchest"] = "Wolf Chest",
                ["item_armorwolflegs"] = "Wolf Legs",
                ["item_bjorn"] = "Bjorn",
                ["item_gd_king"] = "The Elder",
                ["item_ironscrap"] = "Iron Scrap",
                ["item_draugr"] = "Draugr",
                ["item_wraith"] = "Wraith",
                ["item_blob"] = "Blob",
                ["item_bonemass"] = "Bonemass",
                ["item_silverore"] = "Silver Ore",
                ["item_wolf"] = "Wolf",
                ["item_fenring"] = "Fenring",
                ["item_dragon"] = "Moder",
                ["item_barley"] = "Barley",
                ["item_goblin"] = "Goblin",
                ["item_goblinbrute"] = "Goblin Brute",
                ["item_lox"] = "Lox",
                ["item_goblinking"] = "Yagluth",
                ["item_blackmetalscrap"] = "Black Metal Scrap",
                ["item_seeker"] = "Seeker",
                ["item_gjall"] = "Gjall",
                ["item_seekerqueen"] = "Seeker Queen",
                ["item_flametalore"] = "Flametal Ore",
                ["item_asksvin"] = "Asksvin",
                ["item_morgen"] = "Morgen",
                ["item_fader"] = "Fader",

                // New items added for the quest-target content update
                ["item_trophydeer"] = "Deer Trophy",
                ["item_trophygreydwarf"] = "Greydwarf Trophy",
                ["item_abomination"] = "Abomination",
                ["item_stonegolem"] = "Stone Golem",
                ["item_goblinshaman"] = "Fuling Shaman",
                ["item_seekerbrute"] = "Seeker Soldier",
                ["item_fallenvalkyrie"] = "Fallen Valkyrie",

                // Quest reward item names (item_silverore already exists above)
                ["item_cookeddeermeat"] = "Cooked Deer Meat",
                ["item_deerhide"] = "Deer Hide",
                ["item_flint"] = "Flint",
                ["item_leatherscraps"] = "Leather Scraps",
                ["item_surtlingcore"] = "Surtling Core",
                ["item_queenbee"] = "Queen Bee",
                ["item_finewood"] = "Fine Wood",
                ["item_greydwarfeye"] = "Greydwarf Eye",
                ["item_tinore"] = "Tin Ore",
                ["item_pickaxebronze"] = "Bronze Pickaxe",
                ["item_pickaxeiron"] = "Iron Pickaxe",
                ["item_guck"] = "Guck",
                ["item_trollhide"] = "Troll Hide",
                ["item_deer"] = "Deer",
                ["item_bellfragment"] = "Bell Fragment",
                ["item_wolfhairbundle"] = "Wolf Hair Bundle",
                ["item_wolffang"] = "Wolf Fang",
                ["item_loxpelt"] = "Lox Pelt",
                ["item_goblintotem"] = "Goblin Totem",
                ["item_linenthread"] = "Linen Thread",
                ["item_softtissue"] = "Soft Tissue",
                ["item_yggdrasilwood"] = "Yggdrasil Wood",
                ["item_charcoalresin"] = "Charcoal Resin",
                ["item_morgensinew"] = "Morgen Sinew",
                ["item_blackcore"] = "Black Core",

                // MMO XP items (WackyEpicMMOSystem Magic Orbs / XP Potions) - granted as quest rewards
                ["item_mmo_orb1"] = "Magic Orb Lvl 1",
                ["item_mmo_orb2"] = "Magic Orb Lvl 2",
                ["item_mmo_orb3"] = "Magic Orb Lvl 3",
                ["item_mmo_orb4"] = "Magic Orb Lvl 4",
                ["item_mmo_orb5"] = "Magic Orb Lvl 5",
                ["item_mmo_orb6"] = "Magic Orb Lvl 6",
                ["item_mmo_orb7"] = "Magic Orb Lvl 7",
                ["item_mmo_xp_drink1"] = "XP Potion Minor",
                ["item_mmo_xp_drink2"] = "XP Potion Medium",
                ["item_mmo_xp_drink3"] = "XP Potion Greater",
            };
        }
    }
}
