using System.Collections.Generic;

namespace CaptainSkillTree.Localization
{
    public static partial class DefaultLanguages
    {
        private static Dictionary<string, string> GetKorean_Quest()
        {
            return new Dictionary<string, string>
            {
                ["quest_button_label"] = "퀘스트",
                ["quest_panel_title"] = "퀘스트",
                ["quest_completed_title"] = "퀘스트 목표 달성!",
                ["quest_completed_detail_kill"] = "{0} {1}마리 처치를 완료했습니다! 퀘스트 창에서 보상을 수령하세요.",
                ["quest_completed_detail_gather"] = "{0} {1}개 채집을 완료했습니다! 퀘스트 창에서 보상을 수령하세요.",
                ["quest_completed_detail_plant"] = "작물 {0}개 심기를 완료했습니다! 퀘스트 창에서 보상을 수령하세요.",
                ["quest_completed_detail_plant_distinct"] = "서로 다른 작물 {0}종을 심어 완료했습니다! 퀘스트 창에서 보상을 수령하세요.",
                ["quest_completed_detail_cook"] = "요리 {0}개 만들기를 완료했습니다! 퀘스트 창에서 보상을 수령하세요.",
                ["quest_completed_detail_cook_distinct"] = "서로 다른 요리 {0}종을 만들어 완료했습니다! 퀘스트 창에서 보상을 수령하세요.",
                ["quest_completed_detail_fish"] = "물고기 {0}마리 잡기를 완료했습니다! 퀘스트 창에서 보상을 수령하세요.",
                ["quest_completed_detail_fish_distinct"] = "서로 다른 물고기 {0}종을 낚아 완료했습니다! 퀘스트 창에서 보상을 수령하세요.",
                ["quest_reward_jump_proficiency"] = "점프 숙련도 +10 (영구)",
                ["quest_reward_tame_wolf"] = "길들여진 새끼 늑대",
                ["quest_reward_stamina_bonus"] = "스테미나 최대치 +10 (영구)",
                ["quest_reward_elemental_damage"] = "속성 공격력 +2% (영구)",
                ["quest_reward_physical_damage"] = "물리 공격력 +1% (영구)",
                ["quest_reward_farming_skill"] = "농사 기술 +{0}",
                ["quest_reward_cooking_skill"] = "요리 기술 +{0}",
                ["quest_reward_fishing_skill"] = "낚시 기술 +{0}",
                ["quest_reward_melee_weapon_skill"] = "근접 무기 숙련도 +{0} (영구)",
                ["quest_reward_ranged_weapon_skill"] = "활/석궁 숙련도 +{0} (영구)",
                ["quest_status_completed"] = "완료",
                ["quest_status_claimed"] = "수령완료",
                ["quest_claim_button"] = "보상",
                ["quest_coin_label"] = "코인",
                ["quest_tooltip_progress"] = "진행상황",
                ["quest_reward_tame_lox"] = "테이밍된 록스 새끼",
                ["quest_reward_random_item"] = "{0} 중 1개",
                ["quest_type_gather"] = "채집",
                ["quest_type_kill"] = "처치",
                ["quest_type_kill_boss"] = "보스",
                ["quest_type_special"] = "특수",
                ["quest_type_farm"] = "농사",
                ["quest_type_cook"] = "요리",
                ["quest_type_fish"] = "낚시",
                ["quest_label_farm_count"] = "작물 {0}개 심기",
                ["quest_label_farm_distinct"] = "서로 다른 종류 {0}가지 심기",
                ["quest_label_cook_count"] = "{0}개 만들기",
                ["quest_label_cook_distinct"] = "서로 다른 종류 {0}가지 만들기",
                ["quest_label_fish_count"] = "물고기 {0}마리 잡기",
                ["quest_label_fish_distinct"] = "서로 다른 종류 물고기 {0}종 잡기",
                ["quest_label_mountain_melee_only"] = "근접 무기만으로 모더 처치",
                ["quest_label_mountain_ranged_only"] = "원거리(활,석궁,마법) 무기만으로 모더 처치",
                ["quest_biome_Life"] = "생활",
                ["quest_biome_Meadows"] = "목초지",
                ["quest_biome_BlackForest"] = "검은숲",
                ["quest_biome_Swamp"] = "늪지",
                ["quest_biome_Mountain"] = "산",
                ["quest_biome_Plains"] = "평원",
                ["quest_biome_Mistlands"] = "안개숲",
                ["quest_biome_Ashlands"] = "잿빛땅",

                // 퀘스트별 플레이버 설명 (마우스오버 툴팁 전용)
                ["quest_desc_Meadows_Quest1"] = "목초지를 뛰노는 사슴들이 늘어나면서 사냥꾼들의 몫도 줄었다. 가죽과 고기를 위해 사슴을 사냥하라.",
                ["quest_desc_Meadows_Quest2"] = "강가의 넥이 자꾸 늘어나 낚시꾼들을 위협하고 있다. 넥을 처치해 부싯돌을 챙겨라.",
                ["quest_desc_Meadows_Quest3"] = "야생 멧돼지 떼가 농경지를 망치고 있다. 가죽 조각을 위해 멧돼지를 사냥하라.",
                ["quest_desc_Meadows_Quest4"] = "목초지의 수호자 에이크시르가 날뛰고 있다. 최초의 숲의 힘을 시험하라.",
                ["quest_desc_Meadows_Quest5"] = "잘 익은 라즈베리를 모아오면 여왕벌을 새로 들여올 수 있다는 소문이 있다.",
                ["quest_desc_Meadows_Quest6"] = "음식의 힘을 빌리지 않고, 상처 하나 입지 않은 채로 에이크시르를 쓰러뜨려라. 진정한 실력자만이 해낼 수 있는 도전이다.",
                ["quest_desc_BlackForest_Quest1"] = "검은숲 초입에 그레이드워프들이 우글거린다. 숫자를 줄이고 질 좋은 나무를 챙겨라.",
                ["quest_desc_BlackForest_Quest2"] = "그레이드워프 무리가 도를 넘었다. 대규모 토벌로 트롤 가죽을 얻어내라.",
                ["quest_desc_BlackForest_Quest3"] = "숲 속 트롤이 나무를 뽑아 던지며 행패를 부리고 있다. 놈을 처치하고 슈트링을 회수하라.",
                ["quest_desc_BlackForest_Quest4"] = "곰 비외른이 사냥터를 어슬렁거리며 짐승들을 쫓아내고 있다. 놈을 사냥해 주석 원석을 얻어라.",
                ["quest_desc_BlackForest_Quest5"] = "검은숲의 수호자, 늙은이가 뿌리를 뻗쳐 숲을 옥죄고 있다. 엘더를 쓰러뜨려라.",
                ["quest_desc_BlackForest_Quest7"] = "활과 석궁, 마법의 힘을 모두 내려놓고 오직 근접 무기만으로 엘더에게 다가가라.",
                ["quest_desc_Swamp_Quest1"] = "늪지의 어보미네이션이 나무뿌리를 흔들며 지나가는 이들을 짓밟는다. 놈을 처치하고 철 곡괭이를 챙겨라.",
                ["quest_desc_Swamp_Quest2"] = "무덤에서 되살아난 드라우그가 늪 전역에 넘쳐난다. 대규모 소탕으로 찌꺼기를 모아라.",
                ["quest_desc_Swamp_Quest3"] = "밤이 되면 레이스들이 늪을 배회하며 산 자를 노린다. 놈들을 처치하고 슈트링을 회수하라.",
                ["quest_desc_Swamp_Quest4"] = "늪 표면에 퍼진 블롭들이 오염을 확산시키고 있다. 놈들을 처치해 슈트링을 얻어라.",
                ["quest_desc_Swamp_Quest5"] = "늪 깊은 곳에서 썩은 살덩이, 본메스가 깨어났다. 오염된 수호자를 처단하라.",
                ["quest_desc_Swamp_Quest7"] = "검과 화살을 내려놓고 오직 마법만으로 본메스를 처단하라.",
                ["quest_desc_Mountain_Quest1"] = "산맥의 스톤골렘이 바위를 부수며 길을 막고 있다. 놈을 쓰러뜨리고 은 원석을 회수하라.",
                ["quest_desc_Mountain_Quest2"] = "늑대 무리가 산맥을 뒤덮으며 여행자들을 위협한다. 대규모 사냥으로 스테미나를 단련하라.",
                ["quest_desc_Mountain_Quest3"] = "얼어붙은 펜링이 눈보라 속에서 사냥감을 노린다. 놈들을 처치하고 슈트링을 챙겨라.",
                ["quest_desc_Mountain_Quest4"] = "산 정상에서 모더가 얼음숨결을 내뿜으며 군림하고 있다. 용을 잡아 은 원석을 얻어라.",
                ["quest_desc_Mountain_Quest5"] = "얼음숨결도 발톱도 두렵지 않다. 오직 검, 도끼, 둔기, 창, 폴암, 단검만으로 모더에게 맞서라. 전투 중 원거리 무기나 마법을 한 번이라도 사용하면 실패한다.",
                ["quest_desc_Mountain_Quest6"] = "가까이 다가서지 마라. 활과 석궁, 마법만으로 모더를 하늘에서 떨어뜨려라. 전투 중 근접 무기를 한 번이라도 사용하면 실패한다.",
                ["quest_desc_Plains_Quest1"] = "풀링 샤먼이 저주를 퍼부으며 평원을 지배하려 한다. 놈들을 처치해 속성 마력을 흡수하라.",
                ["quest_desc_Plains_Quest2"] = "고블린 무리가 평원 곳곳에 진지를 세우고 있다. 대규모 토벌로 고블린 토템을 회수하라.",
                ["quest_desc_Plains_Quest3"] = "고블린 브루트가 몽둥이를 휘두르며 늑대 무리를 이끌고 있다. 놈을 처치하면 새끼 늑대를 길들일 수 있다.",
                ["quest_desc_Plains_Quest4"] = "록스 무리가 평원을 배회하며 땅을 뒤흔든다. 충분히 사냥하면 록스 새끼를 길들일 기회를 얻는다.",
                ["quest_desc_Plains_Quest5"] = "고블린들의 왕, 야글루스가 평원을 지배하려 한다. 마지막 저항을 끝장내라.",
                ["quest_desc_Mistlands_Quest1"] = "안개숲의 시커솔저가 병사들을 이끌고 침입자를 몰아낸다. 놈들을 처치해 말랑한 조직을 회수하라.",
                ["quest_desc_Mistlands_Quest2"] = "시커 떼가 안개 속에서 튀어나와 여행자를 습격한다. 놈들을 사냥해 물리적 힘을 얻어라.",
                ["quest_desc_Mistlands_Quest3"] = "하늘을 나는 걀이 폭발하는 포자를 흩뿌리며 위협하고 있다. 놈을 격추하고 조직을 회수하라.",
                ["quest_desc_Mistlands_Quest4"] = "안개숲 깊은 곳, 시커 여왕이 알을 낳으며 군단을 늘리고 있다. 여왕을 처단하라.",
                ["quest_desc_Ashlands_Quest1"] = "타락한 발키리들이 잿빛 하늘을 가르며 침입자를 노린다. 놈들을 처치하고 슈트링을 회수하라.",
                ["quest_desc_Ashlands_Quest2"] = "아스크빈 무리가 용암 지대를 배회하며 종 조각을 지니고 다닌다. 놈들을 사냥해 조각을 회수하라.",
                ["quest_desc_Ashlands_Quest3"] = "그림자 속 모르겐이 은신하며 여행자를 노린다. 놈들을 처치해 검은 코어를 회수하라.",
                ["quest_desc_Ashlands_Quest4"] = "잿빛땅의 마지막 재앙, 페이더가 깨어났다. 최후의 결전에서 승리하라.",

                // 몬스터/자원 이름 (item_wood는 DefaultLanguages_GameMessages.cs에 이미 있음)
                ["item_neck"] = "넥",
                ["item_boar"] = "멧돼지",
                ["item_eikthyr"] = "에이크시르",
                ["item_raspberry"] = "라즈베리",
                ["item_copperore"] = "구리 원석",
                ["item_greydwarf"] = "난쟁이",
                ["item_greydwarf_elite"] = "난쟁이 엘리",
                ["item_troll"] = "트롤",
                ["item_helmettrollleather"] = "트롤 가죽 투구",
                ["item_armortrollleatherchest"] = "트롤 가죽 가슴",
                ["item_armortrollleatherlegs"] = "트롤 가죽 하의",
                ["item_helmetbronze"] = "청동투구",
                ["item_armorbronzechest"] = "청동상의",
                ["item_armorbronzelegs"] = "청동하의",
                ["item_helmetiron"] = "철투구",
                ["item_armorironchest"] = "철상의",
                ["item_armorironlegs"] = "철하의",
                ["item_helmetdrake"] = "드레이크투구",
                ["item_armorwolfchest"] = "늑대상의",
                ["item_armorwolflegs"] = "늑대하의",
                ["item_bjorn"] = "곰",
                ["item_gd_king"] = "엘더",
                ["item_ironscrap"] = "고철",
                ["item_draugr"] = "드라우그",
                ["item_wraith"] = "유령",
                ["item_blob"] = "블롭",
                ["item_bonemass"] = "본메스",
                ["item_silverore"] = "은 원석",
                ["item_wolf"] = "늑대",
                ["item_fenring"] = "펜링",
                ["item_dragon"] = "모더",
                ["item_barley"] = "보리",
                ["item_goblin"] = "고블린",
                ["item_goblinbrute"] = "고블린 브루트",
                ["item_lox"] = "록스",
                ["item_goblinking"] = "야글루스",
                ["item_blackmetalscrap"] = "검은금속 조각",
                ["item_seeker"] = "시커",
                ["item_gjall"] = "걀",
                ["item_seekerqueen"] = "시커 여왕",
                ["item_flametalore"] = "화염강 원석",
                ["item_asksvin"] = "아스크빈",
                ["item_morgen"] = "모르겐",
                ["item_fader"] = "페이더",

                // 퀘스트 대상 변경으로 신규 추가된 항목
                ["item_trophydeer"] = "사슴 트로피",
                ["item_trophygreydwarf"] = "회색난쟁이 트로피",
                ["item_abomination"] = "어보미네이션",
                ["item_stonegolem"] = "스톤골렘",
                ["item_goblinshaman"] = "풀링 샤먼",
                ["item_seekerbrute"] = "시커솔저",
                ["item_fallenvalkyrie"] = "폴른 발키리",

                // 퀘스트 보상 아이템 이름 (item_silverore는 위에 이미 있음)
                ["item_cookeddeermeat"] = "구운 사슴고기",
                ["item_deerhide"] = "사슴 가죽",
                ["item_flint"] = "부싯돌",
                ["item_leatherscraps"] = "가죽 조각",
                ["item_surtlingcore"] = "슈트링",
                ["item_queenbee"] = "여왕벌",
                ["item_finewood"] = "질 좋은 나무",
                ["item_greydwarfeye"] = "그레이드워프 눈",
                ["item_tinore"] = "주석 원석",
                ["item_pickaxebronze"] = "청동 곡괭이",
                ["item_pickaxeiron"] = "철 곡괭이",
                ["item_guck"] = "찌꺼기",
                ["item_trollhide"] = "트롤 가죽",
                ["item_deer"] = "사슴",
                ["item_bellfragment"] = "종 조각",
                ["item_wolfhairbundle"] = "늑대 털 뭉치",
                ["item_wolffang"] = "늑대 이빨",
                ["item_loxpelt"] = "록스 가죽",
                ["item_goblintotem"] = "고블린 토템",
                ["item_linenthread"] = "린넨 실",
                ["item_softtissue"] = "말랑한 조직",
                ["item_yggdrasilwood"] = "위그드라실 나무",
                ["item_charcoalresin"] = "숯 수지",
                ["item_morgensinew"] = "모르겐 힘줄",
                ["item_blackcore"] = "검은 코어",

                // MMO 경험치 아이템 (WackyEpicMMOSystem 마법 오브/XP 포션) - 퀘스트 보상으로 지급
                ["item_mmo_orb1"] = "마법 오브 Lv.1",
                ["item_mmo_orb2"] = "마법 오브 Lv.2",
                ["item_mmo_orb3"] = "마법 오브 Lv.3",
                ["item_mmo_orb4"] = "마법 오브 Lv.4",
                ["item_mmo_orb5"] = "마법 오브 Lv.5",
                ["item_mmo_orb6"] = "마법 오브 Lv.6",
                ["item_mmo_orb7"] = "마법 오브 Lv.7",
                ["item_mmo_xp_drink1"] = "경험치 포션(소)",
                ["item_mmo_xp_drink2"] = "경험치 포션(중)",
                ["item_mmo_xp_drink3"] = "경험치 포션(대)",
            };
        }
    }
}
