using System.Collections.Generic;

namespace CaptainSkillTree.Localization
{
    public static partial class DefaultLanguages
    {
        private static Dictionary<string, string> GetKorean_WeaponSkills()
        {
            return new Dictionary<string, string>
            {
                // === Sword Skill Names ===
                ["sword_skill_expert"] = "검 전문가",
                ["sword_skill_rush_slash"] = "돌진 연속 베기",
                ["sword_skill_fast_slash"] = "빠른 베기",
                ["sword_skill_counter"] = "반격 자세",
                ["sword_skill_combo"] = "연속베기",
                ["sword_skill_riposte"] = "칼날 되치기",
                ["sword_skill_all_in_one"] = "공방일체",
                ["sword_skill_duel"] = "진검승부",
                ["sword_skill_parry_rush"] = "회오리베기",
                ["sword_skill_ultimate"] = "궁극 베기",

                // === Sword Skill Descriptions ===
                ["sword_desc_expert"] = "검 공격력 +{0}%\n2연속 공격력 +{1}% ({2}초)",
                ["sword_desc_rush_slash"] = "전방 {0}m 돌진 후 몬스터 주변을 빠르게 이동하며 3회 연속 베기",
                ["sword_desc_rush_slash_1st"] = "1차 베기: 공격력 {0}%",
                ["sword_desc_rush_slash_2nd"] = "2차 베기: 공격력 {0}%",
                ["sword_desc_rush_slash_3rd"] = "3차 베기 (피니셔): 공격력 {0}%",
                ["sword_desc_rush_slash_path"] = "이동 경로의 모든 몬스터 적중",
                ["rush_slash_path_hit"] = "경로 베기!",
                ["sword_desc_fast_slash"] = "공격속도 +{0}%",
                ["sword_desc_counter"] = "패링 성공 후 {0}초동안 방어력 +{1}%",
                ["sword_desc_combo"] = "3연속 공격력 +{0}% ({1}초)",
                ["sword_desc_riposte"] = "베기 공격력 +{0}",
                ["sword_desc_all_in_one"] = "양손검 착용 시 공격력 +{0}%, 막기 방어력 +{1}%",
                ["sword_desc_duel"] = "공격 속도 +{0}%",
                ["sword_desc_parry_rush"] = "H키: 반경 {0}m/{1}m/{2}m 3단계 회오리베기",
                ["sword_desc_parry_rush_damage"] = "{0}차: 공격력 {1}%",
                ["requirement_two_handed_sword"] = "양손검 착용",
                ["requirement_sword_or_shield_equip"] = "검 또는 방패 착용",
                ["sword_desc_parry_rush_push"] = "{0}m 밀어내기",
                ["sword_desc_ultimate"] = "모든 검 스킬 효과 +{0}%",

                // === Sword Additional Tooltips ===
                ["tooltip_sword_effect_note"] = "※ 검 사용 시 효과 발동",
                ["tooltip_sword_damage_boost"] = "검 공격력 향상",
                ["tooltip_skill_not_found"] = "{0} 스킬 정보를 찾을 수 없음",
                ["tooltip_generation_error"] = "툴팁 생성 오류",

                // === Archer Skill ===
                ["archer_skill_multishot"] = "멀티샷",
                ["archer_desc_multishot"] = "{0}발씩 {1}회 발사, 화살 1발은 활+화살 공격력의 {2}%",
                ["archer_desc_passive"] = "점프 높이 +{0}%, 낙하 데미지 -{1}%",
                ["archer_range_arrows"] = "화살 {0}개 발사",

                // === Mace Skill Names ===
                ["mace_skill_expert"] = "둔기 전문가",
                ["mace_skill_guardian"] = "방패돌진",
                ["mace_skill_fury"] = "분노의 망치",
                ["mace_skill_damage_boost"] = "둔기 강화",
                ["mace_skill_stun_boost"] = "기절 강화",
                ["mace_skill_guard_boost"] = "회전 타격",
                ["mace_skill_heavy_strike"] = "무거운 일격",
                ["mace_skill_knockback"] = "밀어내기",
                ["mace_skill_tanker"] = "탱커",
                ["mace_skill_dps_boost"] = "데미지 강화",
                ["mace_skill_grandmaster"] = "속공",

                // === Mace Skill Descriptions ===
                ["mace_desc_expert"] = "공격력 +{0}%, 기절 확률 +{1}%, 기절 지속시간 +{2}초",
                ["mace_desc_damage_boost"] = "둔기 공격력 +{0}%",
                ["mace_desc_stun_boost"] = "기절 확률 +{0}%, 기절 지속시간 +{1}초",
                ["mace_desc_guard_boost"] = "세컨드 공격 시 공격력 +{0}%, 범위 {1}m, 넉백 {2}m",
                ["mace_desc_heavy_strike"] = "타격 +{0}",
                ["mace_desc_knockback"] = "막기 미사용 상태에서 피격 시 {0}% 확률로 공격자를 밀어냄",
                ["mace_desc_tanker"] = "체력 +{0}, 피해 감소 +{1}%",
                ["mace_desc_dps_boost"] = "공격력 +{0}%",
                ["mace_desc_grandmaster"] = "공격속도 +{0}%",
                ["spin_attack_hit"] = "🌀 회전 타격 +{0}%",
                ["mace_desc_fury_attack"] = "{0}회 연속 타격",
                ["mace_desc_fury_interval"] = "공격 간격 {0}초, 약 {1}초간 공격",
                ["mace_desc_fury_damage"] = "1~4타 {0}%, 5타(마무리) {1}%",
                ["mace_desc_guardian_buff"] = "방패 돌진하여 방패 막기력의 {0}% 데미지",
                ["mace_desc_guardian_damage"] = "방패 막기력의 {0}% 데미지",
                ["mace_desc_guardian_note"] = "방패로 적을 가격하고 주변 5m 적을 도발한다",
                ["mace_desc_guardian_multihit"] = "다단히트: VFX 발동마다 3m 반경 방패 막기력의 {0}% 추가 타격 + 크리티컬 이펙트",
                ["mace_effect_buff"] = "돌진 거리",
                ["requirement_two_hand_mace"] = "한손, 양손 둔기 착용",
                ["requirement_mace_shield"] = "방패 착용",
                ["tooltip_effect"] = "효과",
                ["tooltip_special_note"] = "특별안내",

                // === Spear Skill Names ===
                ["spear_skill_expert"] = "창 전문가",
                ["spear_skill_penetrate"] = "꿰뚫는 창",
                ["spear_skill_combo"] = "연공창",
                ["spear_skill_throw"] = "투창 전문가",
                ["spear_skill_crit"] = "급소 찌르기",
                ["spear_skill_pierce"] = "연격창",
                ["spear_skill_evasion"] = "회피 찌르기",
                ["spear_skill_explosion"] = "빠른창",
                ["spear_skill_dual"] = "이연창",

                // === Spear Skill Descriptions ===
                ["spear_desc_expert"] = "{0}% 확률로 공격 시 {1}% 공격속도로 1회 추가 공격 발동",
                ["spear_expert_proc"] = "번개 일격!",
                ["spear_desc_throw"] = "창 던지기 공격력 +{0}%",
                ["spear_desc_crit"] = "창 공격력 +{0}%",
                ["spear_desc_pierce"] = "관통 공격력 +{0}",
                ["spear_desc_evasion"] = "공격 시 5초 동안 회피 +{0}%, 공격 스태미나 -{1}%",
                ["spear_evasion_buff"] = "회피 찌르기: 회피 +{0}% (5초)",
                ["spear_throw_passive_activated"] = "✨ 투창 +{0}%!",
                ["spear_desc_explosion"] = "공격 속도 +{0}%",
                ["spear_desc_dual"] = "2연속 공격 시 {0}초 동안 공격력 +{1}%",
                ["spear_desc_penetrate"] = "{0}초간 번개 충격 모드 활성화, {1}회 연속 적중 시 번개 충격 발동",
                ["spear_desc_penetrate_mechanic"] = "1번째 공격: 전방 7m 내 몬스터 돌진 | 2번째 공격: 제자리 (반복)",
                ["spear_desc_penetrate_damage"] = "무기 공격력 +{0}%",
                ["spear_desc_combo"] = "투창을 강화하여 창을 던지고 적과 주변 몬스터를 넉백시킴",
                ["spear_desc_combo_damage"] = "+{0}%",
                ["spear_desc_combo_range"] = "주변 {0}m",
                ["requirement_one_hand_spear"] = "한손 창 착용",

                // === Polearm Skill Names ===
                ["polearm_skill_expert"] = "폴암 전문가",
                ["polearm_skill_king"] = "관통 돌격",
                ["polearm_skill_whirlwind"] = "휠윈드",
                ["polearm_skill_spin"] = "회전베기",
                ["polearm_skill_suppress"] = "제압 공격",
                ["polearm_skill_hero"] = "영웅 타격",
                ["polearm_skill_area"] = "광역 강타",
                ["polearm_skill_ground"] = "폭풍베기",
                ["polearm_skill_moon"] = "반달 베기",
                ["polearm_skill_charge"] = "폴암강화",

                // === Polearm Skill Descriptions ===
                ["polearm_desc_expert"] = "공격 범위 +{0}%",
                ["polearm_desc_spin"] = "특수(휠 마우스) 공격력 +{0}%",
                ["polearm_desc_suppress"] = "공격력 +{0}%",
                ["polearm_desc_hero"] = "{0}% 확률로 스태거",
                ["polearm_desc_area"] = "2연속 공격 시 공격력 +{0}%({1}초동안)",
                ["polearm_desc_ground"] = "1차 공격 후 4초 이내 특수(휠 마우스) 공격 시 번개속성 +{0} 추가",
                ["polearm_desc_moon"] = "공격 범위 +{0}%, 공격 스태미나 -{1}%",
                ["polearm_desc_charge"] = "관통 공격력 +{0}",
                ["polearm_desc_king"] = "전방 {0}m 돌진 (지형 추종), 3m 경로 내 적 적중, 장애물 시 멈춤",
                ["polearm_desc_king_first"] = "공격력 +{0}%",
                ["polearm_desc_king_aoe"] = "공격력 +{0}% (뒤쪽 {1}°, {2}m)",
                ["polearm_desc_king_knockback"] = "{0}m",
                ["polearm_desc_whirlwind"] = "마우스 휠 버튼을 누르고 있는 동안 카메라 방향 앞으로 이동하며 회오리 공격. 공격력 무기의 {0}%",
                ["polearm_desc_whirlwind_damage"] = "무기 공격력 {0}% (광역 6m 포함)",
                ["unit_cycle"] = "회",
                ["tooltip_first_hit"] = "첫 타격",
                ["tooltip_aoe_knockback"] = "AOE 넉백",
                ["tooltip_knockback_distance"] = "넉백 거리",

                // === Knife Skill Names ===
                ["knife_skill_expert"] = "단검 전문가",
                ["knife_skill_assassin"] = "암살자의 심장",
                ["knife_skill_evasion"] = "회피 숙련",
                ["knife_skill_move_speed"] = "빠른 움직임",
                ["knife_skill_attack_speed"] = "빠른 공격",
                ["knife_skill_crit_rate"] = "치명타 숙련",
                ["knife_skill_combat_damage"] = "치명적 피해",
                ["knife_skill_execution"] = "암살자",
                ["knife_skill_assassination"] = "암살술",
                ["knife_skill_stack_explosion"] = "약점폭발",

                // === Knife Skill Descriptions ===
                ["knife_desc_expert"] = "적의 뒤에서 공격 시 피해 +{0}%",
                ["knife_desc_evasion"] = "회피 확률 +{0}%",
                ["knife_desc_move_speed"] = "이동속도 +{0}%",
                ["knife_move_speed_buff"] = "빠른 움직임! 이동속도 +{0}%",
                ["knife_desc_attack_speed"] = "베기 공격력 +{0}, 관통 공격력 +{0}",
                ["knife_desc_crit_rate"] = "치명타 확률 +{0}%",
                ["knife_desc_attack_evasion"] = "공격 시 {1}초간 회피 +{0}%",
                ["knife_desc_combat_damage"] = "공격력 +{0}%",
                ["knife_desc_execution"] = "치명타 피해 +{0}%, 치명타 확률 +{1}%",
                ["knife_desc_assassination"] = "{1}연속 공격 시 {0}% 확률로 스태거",
                ["knife_desc_assassin_main"] = "{0}m 이내 적의 뒤로 순간이동\n대상 {2}초 스턴 + {3}회 연속 공격 (회당 {4}%)\n공격 완료 후 원래 위치로 복귀",
                ["knife_desc_assassin_note"] = "암살자의 모든 능력을 극한까지 끌어올리는 궁극기",
                ["knife_desc_assassin_note2"] = "{0}m 이내 적이 없으면 스킬 취소",
                ["knife_desc_stack_explosion"] = "공격 적중마다 1스택 (최대 {0}), {1}초 유지\nH키: 스택 폭발, 스택×무기공격력 {2}% 화염 피해",
                ["knife_desc_stack_explosion_detail"] = "공격 적중마다 1스택을 쌓으며 최대 스택이 {0}이 되면 자동 폭발 또는 휠마우스(M2) 버튼으로 수동 폭발\n스택당 {1}초 유지되며, 최대 {2}초 후 자동 폭발, 스택당 무기공격력의 {3}% 피해 + 광역피해(스택공격의 {4}%)",
                ["knife_desc_stack_explosion_note"] = "스택은 마지막 적중 후 {0}초가 지나면 초기화됩니다",
                ["stack_explosion_no_stack"] = "약점폭발: 스택이 없습니다",
                ["stack_explosion_no_target"] = "약점폭발: 유효한 타겟이 없습니다",
                ["stack_explosion_buff_start"] = "약점폭발 준비! 공격하여 스택을 쌓으세요",
                ["stack_explosion_buff_expire"] = "약점폭발 버프 만료 — 폭발!",
                ["stack_explosion_max_stack"] = "약점폭발 최대 스택 — 폭발!",
                ["requirement_knife_claw"] = "단검 또는 클로 착용",

                // === Staff Skill Names ===
                ["staff_skill_expert"] = "지팡이 전문가",
                ["staff_skill_dual_cast"] = "이중시전",
                ["staff_skill_heal"] = "힐",

                // === Staff Skill Descriptions ===
                ["staff_desc_dual_cast"] = "{0}발 추가 마법 발사체를 0.25초 간격으로 연속 발사",
                ["staff_desc_dual_cast_damage"] = "지팡이/완드 공격력의 {0}%",
                ["staff_desc_dual_cast_angle_unit"] = "±{0}°",
                ["staff_desc_dual_cast_note"] = "30초간 버프 유지, 다음 마법 공격 시 자동 발동",
                ["requirement_staff_wand"] = "지팡이 또는 완드 착용",
                ["tooltip_dispersion_angle"] = "분산 각도",

                // === Bow Skill Names ===
                ["bow_skill_explosive"] = "폭발 화살",
                ["bow_arrow_rain_tooltip_desc"] = "버프 활성화 후 활로 대상에 조준 — 200m 위에서 화살이 쏟아진다 (보스 50% 감소)",
                ["bow_arrow_rain_damage_format"] = "화살 {0}발 × (활+화살) {1}% 데미지",
                ["bow_arrow_rain_range_format"] = "낙하 반경 {0}m • 범위 3m",

                // === Crossbow Skill Names ===
                ["crossbow_skill_oneshot"] = "단 한 발",
                ["crossbow_ice_breath_tooltip_desc"] = "석궁 장착 후 H키 — 전방 10m·±35° 범위에 아이스 브레스 발사",

                // === Job Skill Names ===
                ["job_skill_archer"] = "아처",
                ["job_skill_tanker"] = "탱커",
                ["job_skill_berserker"] = "버서커",
                ["job_skill_rogue"] = "로그",
                ["job_skill_mage"] = "마법사",
                ["job_skill_paladin"] = "성기사",

                // === Job Names ===
                ["job_archer"] = "아처",
                ["job_mage"] = "마법사",
                ["job_tanker"] = "탱커",
                ["job_rogue"] = "로그",
                ["job_paladin"] = "성기사",
                ["job_berserker"] = "광전사",

                // === Weapon Types ===
                ["weapon_sword"] = "검",
                ["weapon_spear"] = "창",
                ["weapon_mace"] = "둔기",
                ["weapon_polearm"] = "폴암",
                ["weapon_knife"] = "단검",
                ["weapon_bow"] = "활",
                ["weapon_crossbow"] = "석궁",
                ["weapon_staff"] = "지팡이",

                // === Stat Names ===
                ["stat_damage"] = "공격력",
                ["stat_health"] = "체력",
                ["stat_stamina"] = "스태미나",
                ["stat_eitr"] = "에이트르",
                ["stat_armor"] = "방어력",
                ["stat_crit_chance"] = "치명타 확률",
                ["stat_crit_damage"] = "치명타 피해",
                ["stat_attack_speed"] = "공격 속도",
                ["stat_move_speed"] = "이동 속도",
                ["stat_dodge"] = "회피",

                // === UI Buttons ===
                ["ui_reset_points"] = "포인트 초기화",
                ["ui_confirm"] = "확인",
                ["ui_cancel"] = "취소",
                ["archer_upgrade_title"] = "⚔️ 아처 직업 승급",
                ["archer_upgrade_confirm"] = "아처 Lv{0}으로 승급하시겠습니까?",
                ["archer_level_item_required"] = "아처 Lv{0} 승급 트로피가 부족합니다",
                ["archer_missing_items"] = "부족한 아이템: {0}",

                // === 폭발화살 레벨 시스템 ===
                ["explosive_arrow_upgrade_title"] = "💥 폭발화살 강화",
                ["explosive_arrow_upgrade_confirm"] = "폭발화살을 Lv{0}으로 강화합니다.\n필요 트로피가 인벤토리에서 소모됩니다.\n계속하시겠습니까?",
                ["explosive_arrow_max_level"] = "폭발화살이 최대 레벨(Lv7)입니다.",
                ["explosive_arrow_level_item_required"] = "폭발화살 Lv{0} 강화에 필요한 트로피가 부족합니다.",
                ["explosive_arrow_missing_items"] = "부족한 재료: {0}",
                ["explosive_arrow_next_level_req"] = "Lv{0} 강화 조건",
                ["explosive_arrow_upgrade_ready"] = "강화 가능",
                ["item_trophy_frosttroll"] = "서리 트롤 트로피",
                ["item_trophy_sgolem"] = "돌 골렘 트로피",
                ["item_trophy_goblinshaman"] = "고블린 샤먼 트로피",
                ["item_trophy_gjall"] = "걀 트로피",
                ["item_trophy_fader"] = "파더 트로피",
                ["item_trophy_fallenvalkyrie"] = "팔른 발키리 트로피",

                // === 화살비 레벨 시스템 ===
                ["arrow_rain_upgrade_title"] = "🌧️ 화살비 강화",
                ["arrow_rain_upgrade_confirm"] = "화살비를 Lv{0}으로 강화합니다.\n필요 트로피가 인벤토리에서 소모됩니다.\n계속하시겠습니까?",
                ["arrow_rain_max_level"] = "화살비가 최대 레벨(Lv7)입니다.",
                ["arrow_rain_level_item_required"] = "화살비 Lv{0} 강화에 필요한 트로피가 부족합니다.",
                ["arrow_rain_missing_items"] = "부족한 재료: {0}",
                ["arrow_rain_next_level_req"] = "Lv{0} 강화 조건",
                ["arrow_rain_upgrade_ready"] = "강화 가능",
                ["item_trophy_greydwarfshaman"] = "그레이드워프 샤먼 트로피",
                ["item_trophy_draugrelite"] = "드로그르 엘리트 트로피",
                ["item_trophy_fenring"] = "펜링 트로피",
                ["item_trophy_lox"] = "록스 트로피",
                ["item_trophy_seekerbrute"] = "시커 브루트 트로피",
                ["item_trophy_volture"] = "볼처 트로피",
                ["oneshot_upgrade_title"] = "🎯 단 한 발 강화",
                ["oneshot_upgrade_confirm"] = "단 한 발을 Lv{0}으로 강화합니다.\n필요 트로피가 인벤토리에서 소모됩니다.\n계속하시겠습니까?",
                ["oneshot_max_level"] = "단 한 발이 최대 레벨(Lv7)입니다.",
                ["oneshot_level_item_required"] = "단 한 발 Lv{0} 강화에 필요한 트로피가 부족합니다.",
                ["oneshot_missing_items"] = "부족한 재료: {0}",
                ["oneshot_next_level_req"] = "Lv{0} 강화 조건",
                ["oneshot_upgrade_ready"] = "강화 가능",
                ["item_trophy_surtling"] = "서틀링 트로피",
                ["item_trophy_deathsquito"] = "죽음모기 트로피",
                ["item_trophy_seeker"] = "시커 트로피",
                ["item_trophy_morgen"] = "모르겐 트로피",
                ["item_trophy_greydwarfbrute"] = "그레이드워프 브루트 트로피",
                ["item_trophy_draugr"] = "드로그르 트로피",
                ["item_trophy_wolf"] = "늑대 트로피",
                ["item_trophy_goblinbrute"] = "퓰링 버서커 트로피",
                ["item_trophy_tick"] = "진드기 트로피",
                ["item_trophy_charredwarrior"] = "불타는 전사 트로피",
                ["icebreath_upgrade_title"] = "❄️ 빙결폭발탄 강화",
                ["icebreath_upgrade_confirm"] = "빙결폭발탄을 Lv{0}으로 강화합니다.\n필요 트로피가 인벤토리에서 소모됩니다.\n계속하시겠습니까?",
                ["icebreath_max_level"] = "빙결폭발탄이 최대 레벨(Lv7)입니다.",
                ["icebreath_level_item_required"] = "빙결폭발탄 Lv{0} 강화에 필요한 트로피가 부족합니다.",
                ["icebreath_missing_items"] = "부족한 재료: {0}",
                ["icebreath_next_level_req"] = "Lv{0} 강화 조건",
                ["icebreath_upgrade_ready"] = "강화 가능",
                ["item_trophy_foresttroll"] = "숲 트롤 트로피",
                ["item_trophy_draugrelite"] = "드로그르 엘리트 트로피",
                ["item_trophy_cultist"] = "컬티스트 트로피",
                ["item_trophy_goblin"] = "퓰링 트로피",
                ["item_trophy_dvergr"] = "드베르그 트로피",
                ["item_trophy_charredmage"] = "불타는 마법사 트로피",
                ["dualcast_upgrade_title"] = "✨ 이중시전 강화",
                ["dualcast_upgrade_confirm"] = "이중시전을 Lv{0}으로 강화합니다.\n필요 트로피가 인벤토리에서 소모됩니다.\n계속하시겠습니까?",
                ["dualcast_max_level"] = "이중시전이 최대 레벨(Lv7)입니다.",
                ["dualcast_level_item_required"] = "이중시전 Lv{0} 강화에 필요한 트로피가 부족합니다.",
                ["dualcast_missing_items"] = "부족한 재료: {0}",
                ["dualcast_next_level_req"] = "Lv{0} 강화 조건",
                ["dualcast_upgrade_ready"] = "강화 가능",
                ["producer_upgrade_title"] = "🛠️ 제작 전문가 승급",
                ["producer_upgrade_confirm"] = "제작 전문가 Lv{0}으로 승급하시겠습니까?",
                ["producer_missing_items"] = "부족한 아이템: {0}",
                ["ui_reset_confirm_title"] = "스킬 초기화 확인",
                ["ui_reset_confirm_message"] = "정말로 모든 스킬을 초기화하시겠습니까?\n이 작업은 되돌릴 수 없습니다.",
                ["ui_reset_production"] = "생산 초기화",
                ["ui_reset_production_confirm_title"] = "생산 전문가 초기화 확인",
                ["ui_reset_production_confirm_message"] = "생산 전문가 스킬을 초기화하시겠습니까?\n이 작업은 되돌릴 수 없습니다.",
                ["ui_selective_reset_prompt_title"] = "스킬 선택 초기화",
                ["ui_selective_reset_prompt_message"] = "초기화할 스킬을 클릭하여 선택하세요.\n선택된 스킬만큼 코인이 소모됩니다.\n진행하겠습니까?",
                ["ui_selective_reset_confirm"] = "초기화 확인",
                ["ui_selective_reset_cancel"] = "선택 취소",
                ["ui_selective_reset_cost_display"] = "선택 비용: {0} 코인",
                ["ui_selective_reset_insufficient_coins"] = "코인이 부족합니다. (필요: {0}, 보유: {1})",
                ["ui_selective_reset_no_selection"] = "초기화할 스킬을 선택하세요.",
                ["ui_selective_reset_prerequisite_required"] = "상위 스킬을 먼저 선택해야 합니다.",
                ["ui_selective_reset_success"] = "스킬 초기화 완료! -{0} 코인",
                ["ui_music_on"] = "Music On",
                ["ui_music_off"] = "Music Off",
                ["ui_escape"] = "탈출",
                ["ui_escape_cooldown"] = "{0}분 후 사용가능",
                ["ui_escape_confirm"] = "긴급 캐릭터 탈출 버튼입니다.\n시작 지점으로 이동합니다.\n3시간에 1회 사용 가능합니다.",

                // === Skill Investment Messages ===
                ["skill_insufficient_points_detail"] = "스킬 포인트가 부족합니다. (필요: {0}, 보유: {1})",
                ["skill_invest_success"] = "✅ 스킬 포인트 투자 확정!",
                ["items_insufficient"] = "필요한 아이템이 부족합니다",

                // === Additional Tooltip Keys ===
                ["tooltip_none"] = "없음",
                ["tooltip_self"] = "자신",
                ["tooltip_affect_range"] = "영향 범위",
                ["tooltip_passive_effect"] = "패시브 효과",
                ["tooltip_additional"] = "추가",
                ["tooltip_no_player"] = "플레이어 정보 없음",
                ["tooltip_calculation_error"] = "계산 오류",
                ["tooltip_simulation_error"] = "시뮬레이션 오류",
                ["tooltip_load_error"] = "스킬 정보를 불러올 수 없음",
                ["stat_arrow"] = "화살",
                ["item_eikthyr_trophy"] = "에이크쉬르 트로피",
                ["confirmation_job_only"] = "직업은 1개만 선택가능, 레벨 10 이상",
                ["confirmation_job_select_only"] = "직업은 1개만 선택가능",
                ["skill_type_job_active"] = "직업 액티브 스킬 - {0}키",

                // === Archer Job ===
                ["archer_desc_multishot_fallback"] = "5발씩 2회 발사합니다.",
                ["archer_desc_arrow_damage_fallback"] = "화살 1발은 활+화살 공격력의 50%",
                ["archer_passive_skills"] = "점프 높이 +{0}%, 낙하 데미지 -{1}%",
                ["archer_passive_lv1"] = "점프 +{0}%, 낙하 -{1}%, 공격 스테미나 -{2}%, 화살/볼트 {3}% 미소모",
                ["archer_passive_lv2"] = "점프 +{0}%, 독 저항 +{1}%, 공격 스테미나 -{2}%, 화살/볼트 {3}% 미소모",
                ["archer_passive_lv3"] = "점프 +{0}%, 낙하 -{1}%, 독/냉기 저항 +{2}%, 공격 스테미나 -{3}%, 화살/볼트 {4}% 미소모",
                ["archer_passive_lv4"] = "점프 +{0}%, 낙하 -{1}%, 독/냉기/화염 저항 +{2}%, 공격 스테미나 -{3}%, 화살/볼트 {4}% 미소모",
                ["archer_passive_lv5"] = "점프 +{0}%, 낙하 -{1}%, 모든 속성 저항 +{2}%, 공격 스테미나 -{3}%, 화살/볼트 {4}% 미소모",
                ["requirement_archer"] = "활 착용, 아처 직업",
                ["archer_current_level"] = "현재 레벨",
                ["archer_max_level"] = "★ 최대 레벨 달성",
                ["archer_next_level_cost"] = "Lv{0} 업그레이드 재료",
                ["archer_effect_arrows"] = "{0}발씩 {1}회 발사, 1발당 {2}% 데미지",
                ["archer_level_item_required"] = "아처 Lv{0} 업그레이드 재료가 부족합니다",
                ["archer_upgrade_confirm"] = "아처 Lv{0}로 업그레이드 하겠습니까?",
                ["archer_missing_items"] = "부족: {0}",
                ["rogue_upgrade_title"] = "⚔️ 로그 직업 승급",
                ["rogue_upgrade_confirm"] = "로그 Lv{0}로 업그레이드 하겠습니까?",
                ["rogue_missing_items"] = "부족: {0}",
                ["item_trophy_skeleton"] = "해골 트로피",
                ["item_trophy_greydwarf"] = "그레이드워프 트로피",
                ["item_trophy_greydwarfbrute"] = "그레이드워프 브루트 트로피",
                ["item_trophy_greydwarfshaman"] = "그레이드워프 샤먼 트로피",
                ["item_trophy_troll"] = "트롤 트로피",
                ["item_trophy_elder"] = "엘더 트로피",
                ["item_trophy_abomination"] = "어보미네이션 트로피",
                ["item_trophy_bonemass"] = "본메스 트로피",
                ["item_trophy_hatchling"] = "드레이크 트로피",
                ["item_trophy_dragonqueen"] = "모더 트로피",
                ["item_trophy_goblinking"] = "야글루스 트로피",
                ["item_trophy_thequeen"] = "여왕 트로피",
                ["item_trophy_frosttroll"] = "서리 트롤 트로피",
                ["item_trophy_seekerqueen"] = "시커 여왕 트로피",
                ["item_trophy_blob"] = "블랍 트로피",
                ["item_trophy_hare"] = "토끼 트로피",
                ["item_trophy_growth"] = "그로스 트로피",
                ["item_trophy_ulv"] = "울브 트로피",
                ["item_trophy_bonemaw"] = "본매우 트로피",
                ["item_trophy_leech"] = "리치 트로피",
                ["item_trophy_charredarcher"] = "차르드 아처 트로피",
                ["stack_explosion_upgrade_title"] = "💥 약점폭발 강화",
                ["stack_explosion_upgrade_confirm"] = "약점폭발을 Lv{0}으로 강화합니다.\n필요 트로피가 인벤토리에서 소모됩니다.\n계속하시겠습니까?",
                ["stack_explosion_max_level"] = "약점폭발이 최대 레벨(Lv7)입니다.",
                ["stack_explosion_level_item_required"] = "약점폭발 Lv{0} 강화에 필요한 트로피가 부족합니다.",
                ["stack_explosion_missing_items"] = "부족한 재료: {0}",
                ["stack_explosion_next_level_req"] = "Lv{0} 강화 조건",
                ["stack_explosion_upgrade_ready"] = "강화 가능",
                ["assassin_heart_upgrade_title"] = "🗡️ 암살자의 심장 강화",
                ["assassin_heart_upgrade_confirm"] = "암살자의 심장을 Lv{0}으로 강화합니다.\n필요 트로피가 인벤토리에서 소모됩니다.\n계속하시겠습니까?",
                ["assassin_heart_max_level"] = "암살자의 심장이 최대 레벨(Lv7)입니다.",
                ["assassin_heart_level_item_required"] = "암살자의 심장 Lv{0} 강화에 필요한 트로피가 부족합니다.",
                ["assassin_heart_missing_items"] = "부족한 재료: {0}",
                ["assassin_heart_next_level_req"] = "Lv{0} 강화 조건",
                ["assassin_heart_upgrade_ready"] = "강화 가능",
                ["rush_slash_upgrade_title"] = "⚔️ 돌진베기 강화",
                ["rush_slash_upgrade_confirm"] = "돌진베기를 Lv{0}으로 강화합니다.\n필요 트로피가 인벤토리에서 소모됩니다.\n계속하시겠습니까?",
                ["rush_slash_max_level"] = "돌진베기가 최대 레벨(Lv7)입니다.",
                ["rush_slash_level_item_required"] = "돌진베기 Lv{0} 강화에 필요한 트로피가 부족합니다.",
                ["rush_slash_missing_items"] = "부족한 재료: {0}",
                ["rush_slash_next_level_req"] = "Lv{0} 강화 조건",
                ["rush_slash_upgrade_ready"] = "강화 가능",
                ["whirlwind_upgrade_title"] = "🌀 회오리베기 강화",
                ["whirlwind_upgrade_confirm"] = "회오리베기를 Lv{0}으로 강화합니다.\n필요 트로피가 인벤토리에서 소모됩니다.\n계속하시겠습니까?",
                ["whirlwind_max_level"] = "회오리베기가 최대 레벨(Lv7)입니다.",
                ["whirlwind_level_item_required"] = "회오리베기 Lv{0} 강화에 필요한 트로피가 부족합니다.",
                ["whirlwind_missing_items"] = "부족한 재료: {0}",
                ["whirlwind_next_level_req"] = "Lv{0} 강화 조건",
                ["whirlwind_upgrade_ready"] = "강화 가능",
                ["heal_upgrade_title"] = "💚 힐링 스킬 강화",
                ["heal_upgrade_confirm"] = "힐링 스킬을 Lv{0}으로 강화합니다.\n필요 트로피가 인벤토리에서 소모됩니다.\n계속하시겠습니까?",
                ["heal_max_level"] = "힐링 스킬이 최대 레벨(Lv7)입니다.",
                ["heal_level_item_required"] = "힐링 스킬 Lv{0} 강화에 필요한 트로피가 부족합니다.",
                ["heal_missing_items"] = "부족한 재료: {0}",
                ["heal_next_level_req"] = "Lv{0} 강화 조건",
                ["heal_upgrade_ready"] = "강화 가능",
                ["shield_charge_upgrade_title"] = "🛡️ 방패돌진 강화",
                ["shield_charge_upgrade_confirm"] = "방패돌진을 Lv{0}으로 강화합니다.\n필요 트로피가 인벤토리에서 소모됩니다.\n계속하시겠습니까?",
                ["shield_charge_max_level"] = "방패돌진이 최대 레벨(Lv7)입니다.",
                ["shield_charge_level_item_required"] = "방패돌진 Lv{0} 강화에 필요한 트로피가 부족합니다.",
                ["shield_charge_missing_items"] = "부족한 재료: {0}",
                ["shield_charge_next_level_req"] = "Lv{0} 강화 조건",
                ["shield_charge_upgrade_ready"] = "강화 가능",

                ["fury_hammer_upgrade_title"] = "🔨 분노의 심장 강화",
                ["fury_hammer_upgrade_confirm"] = "분노의 심장을 Lv{0}으로 강화합니다.\n필요 트로피가 인벤토리에서 소모됩니다.\n계속하시겠습니까?",
                ["fury_hammer_max_level"] = "분노의 심장이 최대 레벨(Lv7)입니다.",
                ["fury_hammer_level_item_required"] = "분노의 심장 Lv{0} 강화에 필요한 트로피가 부족합니다.",
                ["fury_hammer_missing_items"] = "부족한 재료: {0}",
                ["fury_hammer_next_level_req"] = "Lv{0} 강화 조건",
                ["fury_hammer_upgrade_ready"] = "강화 가능",
                ["item_trophy_neck"] = "목 트로피",

                ["penetrate_upgrade_title"] = "⚡ 꿰뚫는 창 강화",
                ["penetrate_upgrade_confirm"] = "꿰뚫는 창을 Lv{0}으로 강화합니다.\n필요 트로피가 인벤토리에서 소모됩니다.\n계속하시겠습니까?",
                ["penetrate_max_level"] = "꿰뚫는 창이 최대 레벨(Lv7)입니다.",
                ["penetrate_level_item_required"] = "꿰뚫는 창 Lv{0} 강화에 필요한 트로피가 부족합니다.",
                ["penetrate_missing_items"] = "부족한 재료: {0}",
                ["penetrate_next_level_req"] = "Lv{0} 강화 조건",
                ["penetrate_upgrade_ready"] = "강화 가능",

                // 연공창 레벨업 키
                ["combo_upgrade_title"] = "🌀 연공창 강화",
                ["combo_upgrade_confirm"] = "연공창을 Lv{0}으로 강화합니다.\n필요 트로피가 인벤토리에서 소모됩니다.\n계속하시겠습니까?",
                ["combo_max_level"] = "연공창이 최대 레벨(Lv7)입니다.",
                ["combo_level_item_required"] = "연공창 Lv{0} 강화에 필요한 트로피가 부족합니다.",
                ["combo_missing_items"] = "부족한 재료: {0}",
                ["combo_next_level_req"] = "Lv{0} 강화 조건",
                ["combo_upgrade_ready"] = "강화 가능",

                // === Tanker Job ===
                ["tanker_skill_warcry"] = "전장의 함성",
                ["tanker_desc_warcry"] = "{0}m 범위 적을 도발해 {1}초 동안 나를 공격하게 만듭니다.(보스 {2}초), 시전자는 {3}초 동안 피해감소 {4}%",
                ["tanker_desc_warcry_fallback"] = "적을 도발해 5초 동안 나를 공격하게 만듭니다.(보스 1초), 시전자는 피해감소 20%가 5초 지속",
                ["tanker_skill_type_taunt"] = "액티브 도발 스킬 - Y키",
                ["tanker_passive_damage_reduction"] = "받는 피해량 -{0}%",

                // === Berserker Job ===
                ["berserker_skill_rage"] = "버서커 분노",
                ["berserker_desc_rage"] = "{0}초간 분노 상태 발동하여 강력한 공격력 증가",
                ["berserker_desc_rage_detail"] = "체력 손실 1%당 데미지 +{0}%, 최대 +{1}% 한계",
                ["berserker_rage_effect"] = "분노 효과",
                ["berserker_rage_damage_per_health"] = "체력 손실 1%당 데미지 +{0}%",
                ["berserker_passive_desc"] = "스태미나 재생 +20%, 최대 체력 +{3}%, 체력 {0}% 이하 시 {1}초간 무적 (쿨타임 {2}분)",
                ["berserker_not_in_rage"] = "분노 상태가 아님",
                ["berserker_current_status"] = "현재 체력: {0}%\n현재 데미지 보너스: +{1}%\n분노 상태: 활성",
                ["berserker_simulation_title"] = "체력별 데미지 보너스 예상:",
                ["berserker_simulation_line"] = "체력 {0}%: +{1}% 데미지",
                ["berserker_simulation_max"] = "최대 한계: +{0}%",
                ["berserker_default_tooltip"] = "설명:\n[액티브 스킬 - Y키]\n20초 동안 체력의 -1% 비례 데미지 +2%, 체력이 적을수록 더 강한 데미지\n\n[패시브 스킬]\n• 스태미나 리젠 +20% (항상 적용)\n• 체력 10% 이하 시 7초간 무적 (쿨타임 300초)\n\n추가: 최대 +200% 데미지 한계, 빨간/황금 오라 효과\n범위: 자신\n소모: 스태미나 20 (액티브만)\n쿨타임: 45초 (액티브), 300초 (패시브)\n필요조건: 직업 버서커\n확인사항: 직업은 1개만 선택가능, Lv 10 이상\n필요 아이템: 고대 바크 스피어",
                ["requirement_job_berserker"] = "직업 버서커",

                // === Rogue Job ===
                ["rogue_desc_shadow_strike"] = "{0}초 은신, 어그로 제거 범위 {1}m",
                ["rogue_desc_attack_bonus"] = "{0}초 공격력 +{1}%",
                ["rogue_passive_desc"] = "공격 속도 +{0}%, 스태미나 사용 -{1}%, 속성 저항 +{2}%",
                ["requirement_rogue"] = "단검, 클로 착용, 로그 직업",

                // === Mage Job ===
                ["mage_desc_aoe"] = "범위 공격력 {0}%",
                ["mage_passive_resistance"] = "마법 속성 저항 +{0}%",
                ["requirement_mage"] = "지팡이 착용, 메이지 직업",

                // === Healer/Staff ===
                ["healer_self_heal_included"] = "시전자 포함 치료",
                ["healer_self_heal_excluded"] = "시전자는 치료되지 않음 (다른 플레이어만 치료)",
                ["healer_desc_instant"] = "시전자 중심 {0}m 범위 즉시 힐링",
                ["healer_desc_heal_percent"] = "아군 최대체력의 {0}% 즉시 회복",
                ["healer_healing_effect"] = "힐링 효과",
                ["healer_instant_heal"] = "아군 최대체력의 {0} 즉시 회복",
                ["staff_desc_dual_cast_fallback"] = "7발 추가 마법 발사체를 0.25초 간격으로 연속 발사",
                ["staff_desc_dual_cast_damage_fallback"] = "지팡이/완드 공격력의 15%",

                // === StatusEffect Names (L.Get 시스템 연동) ===
                ["se_assassin_heart"] = "암살자의 심장",
                ["se_assassin_heart_tooltip"] = "치명타 데미지 {0}배",
                ["se_arrow_rain_frost"] = "화살비 빙결",
                ["se_ice_breath_slow"] = "빙결 폭발탄",
                ["se_ice_breath_slow_tooltip"] = "이동속도 -50%",
            };
        }

        private static Dictionary<string, string> GetEnglish_WeaponSkills()
        {
            return new Dictionary<string, string>
            {
                // === Stealth System ===
                ["stealth_reason_attack"] = "Attack",
                ["stealth_reason_damage"] = "Damage taken",
                ["stealth_reason_expired"] = "Time expired",

                // === General UI ===
                ["key"] = "key",
                ["skill_points"] = "Skill Points",
                ["reset_button"] = "Reset",
                ["skill_learned"] = "{0} skill learned!",
                ["skill_already_learned"] = "Skill already learned",
                ["skill_prerequisites_not_met"] = "Prerequisites not met",
                ["skill_insufficient_points"] = "Not enough skill points",
                ["skill_level_required"] = "Level {0} required",
                ["skill_acquire_title"] = "{0} Acquire",
                ["skill_acquire_materials"] = "Required Materials:",
                ["skill_acquire_confirm"] = "Do you really want to learn this skill?",

                // === Skill Types ===
                ["skill_type_passive"] = "Passive Skill",
                ["skill_type_active_y"] = "Active Skill (Y Key)",
                ["skill_type_active_r"] = "Active Skill (Z Key)",
                ["skill_type_active_g"] = "Active Skill (G Key)",
                ["skill_type_active_h"] = "Active Skill (H Key)",
                ["skill_type_job_active"] = "Job Active Skill (Y Key)",

                // === Tooltip Labels ===
                ["tooltip_description"] = "Description",
                ["tooltip_range"] = "Range",
                ["tooltip_cost"] = "Cost",
                ["tooltip_skill_type"] = "Skill Type",
                ["tooltip_cooldown"] = "Cooldown",
                ["tooltip_max_duration"] = "Max Duration",
                ["tooltip_requirements"] = "Requirements",
                ["tooltip_notice"] = "Notice",
                ["tooltip_required_points"] = "Required Points",
                ["tooltip_learned"] = "Learned",
                ["tooltip_damage"] = "Damage",
                ["tooltip_passive"] = "Passive",
                ["tooltip_required_item"] = "Required Item",
                ["tooltip_error"] = "Tooltip generation error",
                ["tooltip_unknown_skill"] = "Unknown {0} skill",

                // === Skill Types Extended ===
                ["skill_type_active"] = "Active Skill",
                ["skill_type_active_key"] = "Active Skill - {0} Key",

                // === Weapon Requirements ===
                ["requirement_sword_equip"] = "Sword equipped",
                ["requirement_spear_equip"] = "Spear equipped",
                ["requirement_mace_equip"] = "Mace equipped",
                ["requirement_polearm_equip"] = "Polearm equipped",
                ["requirement_knife_equip"] = "Knife equipped",
                ["requirement_bow_equip"] = "Bow equipped",
                ["requirement_crossbow_equip"] = "Crossbow equipped",
                ["requirement_crossbow_bolt"] = "Crossbow + Bolt in inventory",
                ["requirement_staff_equip"] = "Staff equipped",
                ["requirement_weapon_equip"] = "Weapon equipped",
                ["requirement_shield_equip"] = "Shield equipped",
                ["requirement_one_hand_melee"] = "One-handed melee weapon equipped",

                // === Units ===
                ["unit_seconds"] = "s",
                ["unit_meter"] = "m",
                ["unit_arrow"] = "Arrow",
                ["unit_pieces"] = "pcs",

                // === Item Names ===
                ["item_wood"] = "Wood",
                ["item_finewood"] = "Fine Wood",
                ["item_elderbark"] = "Ancient Bark",
                ["item_raspberry"] = "Raspberry",
                ["item_mushroom"] = "Mushroom",
                ["item_blueberries"] = "Blueberries",
                ["item_copper_ore"] = "Copper Ore",
                ["item_iron_ore"] = "Iron Ore",
                ["item_iron_scrap"] = "Iron Scrap",
                ["item_silver_ore"] = "Silver Ore",
                ["item_bronze_sword"] = "Bronze Sword",
                ["item_bronze_helmet"] = "Bronze Helmet",
                ["item_iron_sword"] = "Iron Sword",
                ["item_iron_helmet"] = "Iron Helmet",
                ["item_silver_sword"] = "Silver Sword",
                ["item_drake_helmet"] = "Drake Helmet",
                ["item_copper_knife"] = "Copper Knife",
                ["item_crude_bow"] = "Crude Bow",
                ["item_spear"] = "Spear",
                ["item_roundlog"] = "Round Log",
                ["item_corewood"] = "Core Wood",
                ["item_yggdrasilwood"] = "Yggdrasil Wood",
                ["item_stone"] = "Stone",
                ["item_bronze"] = "Bronze",
                ["item_iron"] = "Iron",
                ["item_copper"] = "Copper",
                ["item_tin"] = "Tin",
                ["item_silver"] = "Silver",
                ["item_flint"] = "Flint",
                ["item_mushroomyellow"] = "Yellow Mushroom",
                ["item_mushroomblue"] = "Blue Mushroom",
                ["item_coal"] = "Coal",
                ["item_obsidian"] = "Obsidian",

                // === Item Requirement Formats ===
                ["item_consumed"] = "(consumed)",
                ["item_quantity_required"] = "{0} x{1} in inventory",
                ["item_equip_required"] = "{0} equipped",
                ["item_equip_consume"] = "{0} equipped(consumed)",

                // === Tooltip Format Strings ===
                ["seconds_format"] = "{0}s",
                ["stamina_format"] = "Stamina {0}",
                ["stamina_percent_format"] = "Stamina {0}%",
                ["attack_power_bonus_format"] = "Attack power +{0}%",
                ["knockback_format"] = "Knockback {0}m",
                ["bow_explosive_tooltip_desc"] = "Fire explosive arrow, deals explosion damage to nearby enemies on hit",
                ["bow_explosive_damage_format"] = "Explosion damage {0}% of attack power",
                ["bow_explosive_range_format"] = "Explosion radius {0}m",
                ["bow_arrow_rain_tooltip_desc"] = "Activate buff, then fire bow at target — arrows rain from 200m above (50% vs Bosses)",
                ["bow_arrow_rain_damage_format"] = "{0} arrows × (Bow+Arrow) {1}% damage",
                ["bow_arrow_rain_range_format"] = "Fall radius {0}m • AOE 3m",
                ["crossbow_oneshot_tooltip_desc"] = "Slow reload on activation (-50% speed), powerful strike within {0}s + 7m AOE lightning knockback",

                // === Common Tooltip Text ===
                ["tooltip_job_limit"] = "Only one job can be selected",
                ["tooltip_level_required"] = "Level {0} or higher",
                ["tooltip_same_weapon_only"] = "Multiple skills only within same weapon tree",
                ["tooltip_not_invincible"] = "Not invincible during skill use",
                ["tooltip_eikthyr_trophy"] = "Eikthyr Trophy",
                ["trophy_eikthyr_required"] = "Eikthyr Trophy required",

                // === Sword Skill Names ===
                ["sword_skill_expert"] = "Sword Expert",
                ["sword_skill_rush_slash"] = "Rush Slash",
                ["sword_skill_fast_slash"] = "Fast Slash",
                ["sword_skill_counter"] = "Counter Stance",
                ["sword_skill_combo"] = "Combo Slash",
                ["sword_skill_riposte"] = "Riposte",
                ["sword_skill_all_in_one"] = "Attack & Defense",
                ["sword_skill_duel"] = "True Duel",
                ["sword_skill_parry_rush"] = "Whirlwind Slash",
                ["sword_skill_ultimate"] = "Ultimate Slash",

                // === Sword Skill Descriptions ===
                ["sword_desc_expert"] = "Sword damage +{0}%\n2-hit combo damage +{1}% ({2}s)",
                ["sword_desc_rush_slash"] = "Dash {0}m forward, then slash 3 times while circling the monster",
                ["sword_desc_rush_slash_1st"] = "1st slash: {0}% damage",
                ["sword_desc_rush_slash_2nd"] = "2nd slash: {0}% damage",
                ["sword_desc_rush_slash_3rd"] = "3rd slash (Finisher): {0}% damage",
                ["sword_desc_rush_slash_path"] = "Hits all monsters along movement path",
                ["rush_slash_path_hit"] = "Path Slash!",
                ["sword_desc_fast_slash"] = "Attack speed +{0}%",
                ["sword_desc_counter"] = "Defense +{1}% for {0}s after successful parry",
                ["sword_desc_combo"] = "3-hit combo damage +{0}% ({1}s)",
                ["sword_desc_riposte"] = "Slash damage +{0}",
                ["sword_desc_all_in_one"] = "Two-Handed Sword: Attack +{0}%, Block Power +{1}%",
                ["sword_desc_duel"] = "Attack speed +{0}%",
                ["sword_desc_parry_rush"] = "H-key: 3-hit whirlwind AoE {0}m/{1}m/{2}m",
                ["sword_desc_parry_rush_damage"] = "Hit {0}: {1}% damage",
                ["requirement_two_handed_sword"] = "Two-Handed Sword equipped",
                ["requirement_sword_or_shield_equip"] = "Sword or Shield equipped",
                ["sword_desc_parry_rush_push"] = "Knockback {0}m",
                ["sword_desc_ultimate"] = "All sword skill effects +{0}%",

                // === Sword Additional Tooltips ===
                ["tooltip_sword_effect_note"] = "※ Effect activates when using sword",
                ["tooltip_sword_damage_boost"] = "Sword damage boost",
                ["tooltip_skill_not_found"] = "{0} skill info not found",
                ["tooltip_generation_error"] = "Tooltip generation error",

                // === Archer Skill ===
                ["archer_skill_multishot"] = "Multi-Shot",
                ["archer_desc_multishot"] = "Fire {0} arrows x{1} times, each arrow deals {2}% of bow+arrow damage",
                ["archer_desc_passive"] = "Jump height +{0}%, Fall damage -{1}%",
                ["archer_range_arrows"] = "Fires {0} arrows",

                // === Mace Skill Names ===
                ["mace_skill_expert"] = "Mace Expert",
                ["mace_skill_guardian"] = "Shield Charge",
                ["mace_skill_fury"] = "Fury Hammer",
                ["mace_skill_damage_boost"] = "Mace Enhancement",
                ["mace_skill_stun_boost"] = "Stun Enhancement",
                ["mace_skill_guard_boost"] = "Spin Strike",
                ["mace_skill_heavy_strike"] = "Heavy Strike",
                ["mace_skill_knockback"] = "Knockback",
                ["mace_skill_tanker"] = "Tanker",
                ["mace_skill_dps_boost"] = "DPS Enhancement",
                ["mace_skill_grandmaster"] = "Swift Attack",

                // === Mace Skill Descriptions ===
                ["mace_desc_expert"] = "Damage +{0}%, Stun chance +{1}%, Stun duration +{2}s",
                ["mace_desc_damage_boost"] = "Mace damage +{0}%",
                ["mace_desc_stun_boost"] = "Stun chance +{0}%, Stun duration +{1}s",
                ["mace_desc_guard_boost"] = "Secondary attack damage +{0}%, AoE range {1}m, knockback {2}m",
                ["mace_desc_heavy_strike"] = "Blunt +{0}",
                ["mace_desc_knockback"] = "When not blocking, {0}% chance to push attacker on hit",
                ["mace_desc_tanker"] = "Health +{0}, Damage reduction +{1}%",
                ["mace_desc_dps_boost"] = "Damage +{0}%",
                ["mace_desc_grandmaster"] = "Attack speed +{0}%",
                ["spin_attack_hit"] = "🌀 Spin Strike +{0}%",
                ["mace_desc_fury_attack"] = "{0} consecutive strikes",
                ["mace_desc_fury_interval"] = "Attack interval {0}s, about {1}s total",
                ["mace_desc_fury_damage"] = "Hit 1-4: {0}%, Hit 5 (Finisher): {1}%",
                ["mace_desc_guardian_buff"] = "Shield rush dealing {0}% of block power as damage",
                ["mace_desc_guardian_damage"] = "Deal {0}% of block power as damage",
                ["mace_desc_guardian_note"] = "Strike enemies with your shield and taunt nearby enemies within 5m",
                ["mace_desc_guardian_multihit"] = "Multi-hit: +{0}% of block power per VFX pulse within 3m radius + critical effect",
                ["mace_effect_buff"] = "Dash distance",
                ["requirement_two_hand_mace"] = "One/Two-handed mace equipped",
                ["requirement_mace_shield"] = "Shield equipped",
                ["tooltip_effect"] = "Effect",
                ["tooltip_special_note"] = "Special Note",

                // === Spear Skill Names ===
                ["spear_skill_expert"] = "Spear Expert",
                ["spear_skill_penetrate"] = "Piercing Spear",
                ["spear_skill_combo"] = "Combo Spear",
                ["spear_skill_throw"] = "Throw Expert",
                ["spear_skill_crit"] = "Vital Strike",
                ["spear_skill_pierce"] = "Chain Stab",
                ["spear_skill_evasion"] = "Evasion Strike",
                ["spear_skill_explosion"] = "Fast Spear",
                ["spear_skill_dual"] = "Dual Thrust",

                // === Spear Skill Descriptions ===
                ["spear_desc_expert"] = "{0}% chance on hit to trigger 1 extra attack at {1}% speed",
                ["spear_expert_proc"] = "Lightning Strike!",
                ["spear_desc_throw"] = "Spear throw damage +{0}%",
                ["spear_desc_crit"] = "Spear damage +{0}%",
                ["spear_desc_pierce"] = "Pierce damage +{0}",
                ["spear_desc_evasion"] = "On attack: Evasion +{0}% for 5s, Attack stamina -{1}%",
                ["spear_evasion_buff"] = "Evasion Strike: Evasion +{0}% (5s)",
                ["spear_throw_passive_activated"] = "✨ Spear Throw +{0}%!",
                ["spear_desc_explosion"] = "Attack Speed +{0}%",
                ["spear_desc_dual"] = "2-hit combo: Damage +{1}% for {0}s",
                ["spear_desc_penetrate"] = "Lightning shock mode for {0}s, triggers on {1} consecutive hits",
                ["spear_desc_penetrate_mechanic"] = "1st attack: dash to monster within 7m | 2nd attack: in-place (repeats)",
                ["spear_desc_penetrate_damage"] = "Weapon damage +{0}%",
                ["spear_desc_combo"] = "Enhanced throw: knockback target and nearby monsters",
                ["spear_desc_combo_damage"] = "+{0}%",
                ["spear_desc_combo_range"] = "Radius {0}m",
                ["requirement_one_hand_spear"] = "One-handed spear equipped",

                // === Polearm Skill Names ===
                ["polearm_skill_expert"] = "Polearm Expert",
                ["polearm_skill_king"] = "Pierce Charge",
                ["polearm_skill_whirlwind"] = "Whirlwind",
                ["polearm_skill_spin"] = "Spin Slash",
                ["polearm_skill_suppress"] = "Suppress Attack",
                ["polearm_skill_hero"] = "Hero Strike",
                ["polearm_skill_area"] = "Wide Slash",
                ["polearm_skill_ground"] = "Storm Slash",
                ["polearm_skill_moon"] = "Crescent Slash",
                ["polearm_skill_charge"] = "Polearm Enhancement",

                // === Polearm Skill Descriptions ===
                ["polearm_desc_expert"] = "Attack range +{0}%",
                ["polearm_desc_spin"] = "Special (wheel mouse) attack damage +{0}%",
                ["polearm_desc_suppress"] = "Damage +{0}%",
                ["polearm_desc_hero"] = "{0}% chance to stagger",
                ["polearm_desc_area"] = "2-hit combo: Damage +{0}% ({1}s)",
                ["polearm_desc_ground"] = "After 1st attack, within 4s: wheel mouse attack adds +{0} lightning",
                ["polearm_desc_moon"] = "Attack range +{0}%, Stamina cost -{1}%",
                ["polearm_desc_charge"] = "Pierce damage +{0}",
                ["polearm_desc_king"] = "Dash {0}m (follows terrain), hit enemies within 3m path, stops at obstacles",
                ["polearm_desc_king_first"] = "Damage +{0}%",
                ["polearm_desc_king_aoe"] = "Damage +{0}% (Rear {1}°, {2}m)",
                ["polearm_desc_king_knockback"] = "{0}m",
                ["polearm_desc_whirlwind"] = "Hold mouse wheel button to move forward in camera direction with whirlwind attacks. Damage {0}% of weapon",
                ["polearm_desc_whirlwind_damage"] = "Weapon damage {0}% (includes 6m AoE)",
                ["unit_cycle"] = "cycle",
                ["tooltip_first_hit"] = "First Hit",
                ["tooltip_aoe_knockback"] = "AOE Knockback",
                ["tooltip_knockback_distance"] = "Knockback Distance",

                // === Knife Skill Names ===
                ["knife_skill_expert"] = "Knife Expert",
                ["knife_skill_assassin"] = "Assassin's Heart",
                ["knife_skill_evasion"] = "Evasion Mastery",
                ["knife_skill_move_speed"] = "Quick Movement",
                ["knife_skill_attack_speed"] = "Quick Attack",
                ["knife_skill_crit_rate"] = "Critical Mastery",
                ["knife_skill_combat_damage"] = "Lethal Damage",
                ["knife_skill_execution"] = "Assassin",
                ["knife_skill_assassination"] = "Assassination",
                ["knife_skill_stack_explosion"] = "Stack Explosion",

                // === Knife Skill Descriptions ===
                ["knife_desc_expert"] = "Backstab damage +{0}%",
                ["knife_desc_evasion"] = "Evasion chance +{0}%",
                ["knife_desc_move_speed"] = "Move speed +{0}%",
                ["knife_move_speed_buff"] = "Quick Movement! Move speed +{0}%",
                ["knife_desc_attack_speed"] = "Slash +{0}, Pierce +{0}",
                ["knife_desc_crit_rate"] = "Crit chance +{0}%",
                ["knife_desc_attack_evasion"] = "On attack: +{0}% evasion for {1}s",
                ["knife_desc_combat_damage"] = "Attack power +{0}%",
                ["knife_desc_execution"] = "Crit damage +{0}%, Crit chance +{1}%",
                ["knife_desc_assassination"] = "{0}% chance to stagger on {1} consecutive hits",
                ["knife_desc_assassin_main"] = "Teleport behind enemy within {0}m\nStun target for {2}s + {3} consecutive attacks ({4}% each)\nReturn to original position after attacks",
                ["knife_desc_assassin_note"] = "Ultimate skill that pushes all assassin abilities to the limit",
                ["knife_desc_assassin_note2"] = "Skill cancelled if no enemy within {0}m",
                ["knife_desc_stack_explosion"] = "Stack on each hit (max {0}), lasts {1}s\nH key: Explode stacks, {2}% fire damage per stack",
                ["knife_desc_stack_explosion_detail"] = "Stack on each hit; auto-explode at {0} stacks or manually with Mouse Button 2\nStacks last {1}s, auto-explode after {2}s max, {3}% weapon damage per stack + AOE ({4}% of stack damage)",
                ["knife_desc_stack_explosion_note"] = "Stacks reset if no hit within {0}s",
                ["stack_explosion_no_stack"] = "Stack Explosion: No stacks",
                ["stack_explosion_no_target"] = "Stack Explosion: No valid target",
                ["stack_explosion_buff_start"] = "Stack Explosion ready! Attack to build stacks",
                ["stack_explosion_buff_expire"] = "Stack Explosion buff expired — Explode!",
                ["stack_explosion_max_stack"] = "Stack Explosion max stacks — Explode!",
                ["requirement_knife_claw"] = "Knife or Claw equipped",

                // === Staff Skill Names ===
                ["staff_skill_expert"] = "Staff Expert",
                ["staff_skill_dual_cast"] = "Double Casting",
                ["staff_skill_heal"] = "Heal",

                // === Staff Skill Descriptions ===
                ["staff_desc_dual_cast"] = "Fire {0} additional magic projectiles in rapid succession (0.25s interval)",
                ["staff_desc_dual_cast_damage"] = "{0}% of Staff/Wand damage",
                ["staff_desc_dual_cast_angle_unit"] = "±{0}°",
                ["staff_desc_dual_cast_note"] = "Buff lasts 30s, triggers on next magic attack",
                ["requirement_staff_wand"] = "Staff or Wand equipped",
                ["tooltip_dispersion_angle"] = "Spread Angle",

                // === Bow Skill Names ===
                ["bow_skill_explosive"] = "Explosive Arrow",

                // === Crossbow Skill Names ===
                ["crossbow_skill_oneshot"] = "One Shot",
                ["crossbow_ice_breath_tooltip_desc"] = "Equip Crossbow + H Key — fire ice breath in 10m·±35° cone",

                // === Job Skill Names ===
                ["job_skill_archer"] = "Archer",
                ["job_skill_tanker"] = "Tanker",
                ["job_skill_berserker"] = "Berserker",
                ["job_skill_rogue"] = "Rogue",
                ["job_skill_mage"] = "Mage",
                ["job_skill_paladin"] = "Paladin",

                // === Job Names ===
                ["job_archer"] = "Archer",
                ["job_mage"] = "Mage",
                ["job_tanker"] = "Tanker",
                ["job_rogue"] = "Rogue",
                ["job_paladin"] = "Paladin",
                ["job_berserker"] = "Berserker",

                // === Weapon Types ===
                ["weapon_sword"] = "Sword",
                ["weapon_spear"] = "Spear",
                ["weapon_mace"] = "Mace",
                ["weapon_polearm"] = "Polearm",
                ["weapon_knife"] = "Knife",
                ["weapon_bow"] = "Bow",
                ["weapon_crossbow"] = "Crossbow",
                ["weapon_staff"] = "Staff",

                // === Stat Names ===
                ["stat_damage"] = "Damage",
                ["stat_health"] = "Health",
                ["stat_stamina"] = "Stamina",
                ["stat_eitr"] = "Eitr",
                ["stat_armor"] = "Armor",
                ["stat_crit_chance"] = "Crit Chance",
                ["stat_crit_damage"] = "Crit Damage",
                ["stat_attack_speed"] = "Attack Speed",
                ["stat_move_speed"] = "Move Speed",
                ["stat_dodge"] = "Dodge",

                // === UI Buttons ===
                ["ui_reset_points"] = "Reset Points",
                ["ui_confirm"] = "Confirm",
                ["ui_cancel"] = "Cancel",
                ["archer_upgrade_title"] = "⚔️ Archer Class Ascension",
                ["archer_upgrade_confirm"] = "Upgrade Archer to Lv{0}?",
                ["archer_level_item_required"] = "Missing Archer Lv{0} upgrade trophies",
                ["archer_missing_items"] = "Missing items: {0}",

                // === Explosive Arrow Level System ===
                ["explosive_arrow_upgrade_title"] = "💥 Explosive Arrow Upgrade",
                ["explosive_arrow_upgrade_confirm"] = "Upgrade Explosive Arrow to Lv{0}.\nRequired trophies will be consumed from inventory.\nProceed?",
                ["explosive_arrow_max_level"] = "Explosive Arrow is at max level (Lv7).",
                ["explosive_arrow_level_item_required"] = "Not enough trophies for Explosive Arrow Lv{0} upgrade.",
                ["explosive_arrow_missing_items"] = "Missing: {0}",
                ["explosive_arrow_next_level_req"] = "Lv{0} Upgrade Requirements",
                ["explosive_arrow_upgrade_ready"] = "Ready to upgrade",
                ["item_trophy_frosttroll"] = "Frost Troll Trophy",
                ["item_trophy_sgolem"] = "Stone Golem Trophy",
                ["item_trophy_goblinshaman"] = "Goblin Shaman Trophy",
                ["item_trophy_gjall"] = "Gjall Trophy",
                ["item_trophy_fader"] = "Fader Trophy",
                ["item_trophy_fallenvalkyrie"] = "Fallen Valkyrie Trophy",

                // === Arrow Rain Level System ===
                ["arrow_rain_upgrade_title"] = "🌧️ Arrow Rain Upgrade",
                ["arrow_rain_upgrade_confirm"] = "Upgrade Arrow Rain to Lv{0}.\nRequired trophies will be consumed from inventory.\nProceed?",
                ["arrow_rain_max_level"] = "Arrow Rain is at max level (Lv7).",
                ["arrow_rain_level_item_required"] = "Not enough trophies for Arrow Rain Lv{0} upgrade.",
                ["arrow_rain_missing_items"] = "Missing: {0}",
                ["arrow_rain_next_level_req"] = "Lv{0} Upgrade Requirements",
                ["arrow_rain_upgrade_ready"] = "Ready to upgrade",
                ["item_trophy_greydwarfshaman"] = "Greydwarf Shaman Trophy",
                ["item_trophy_draugrelite"] = "Draugr Elite Trophy",
                ["item_trophy_fenring"] = "Fenring Trophy",
                ["item_trophy_lox"] = "Lox Trophy",
                ["item_trophy_seekerbrute"] = "Seeker Brute Trophy",
                ["item_trophy_volture"] = "Volture Trophy",
                ["oneshot_upgrade_title"] = "🎯 One Shot Upgrade",
                ["oneshot_upgrade_confirm"] = "Upgrade One Shot to Lv{0}.\nRequired trophies will be consumed from inventory.\nProceed?",
                ["oneshot_max_level"] = "One Shot is at max level (Lv7).",
                ["oneshot_level_item_required"] = "Not enough trophies for One Shot Lv{0} upgrade.",
                ["oneshot_missing_items"] = "Missing: {0}",
                ["oneshot_next_level_req"] = "Lv{0} Upgrade Requirements",
                ["oneshot_upgrade_ready"] = "Ready to upgrade",
                ["item_trophy_hatchling"] = "Drake Trophy",
                ["item_trophy_surtling"] = "Surtling Trophy",
                ["item_trophy_deathsquito"] = "Deathsquito Trophy",
                ["item_trophy_seeker"] = "Seeker Trophy",
                ["item_trophy_morgen"] = "Morgen Trophy",
                ["item_trophy_greydwarfbrute"] = "Greydwarf Brute Trophy",
                ["item_trophy_draugr"] = "Draugr Trophy",
                ["item_trophy_wolf"] = "Wolf Trophy",
                ["item_trophy_goblinbrute"] = "Fuling Berserker Trophy",
                ["item_trophy_tick"] = "Tick Trophy",
                ["item_trophy_charredwarrior"] = "Charred Warrior Trophy",
                ["icebreath_upgrade_title"] = "❄️ Ice Breath Upgrade",
                ["icebreath_upgrade_confirm"] = "Upgrade Ice Breath to Lv{0}.\nRequired trophies will be consumed from inventory.\nProceed?",
                ["icebreath_max_level"] = "Ice Breath is at max level (Lv7).",
                ["icebreath_level_item_required"] = "Not enough trophies for Ice Breath Lv{0} upgrade.",
                ["icebreath_missing_items"] = "Missing: {0}",
                ["icebreath_next_level_req"] = "Lv{0} Upgrade Requirements",
                ["icebreath_upgrade_ready"] = "Ready to upgrade",
                ["item_trophy_foresttroll"] = "Forest Troll Trophy",
                ["item_trophy_draugrelite"] = "Draugr Elite Trophy",
                ["item_trophy_cultist"] = "Cultist Trophy",
                ["item_trophy_goblin"] = "Fuling Trophy",
                ["item_trophy_dvergr"] = "Dvergr Trophy",
                ["item_trophy_charredmage"] = "Charred Mage Trophy",
                ["item_trophy_blob"] = "Blob Trophy",
                ["item_trophy_hare"] = "Hare Trophy",
                ["item_trophy_growth"] = "Growth Trophy",
                ["item_trophy_ulv"] = "Ulv Trophy",
                ["item_trophy_bonemaw"] = "Bonemaw Trophy",
                ["dualcast_upgrade_title"] = "✨ Dual Cast Upgrade",
                ["dualcast_upgrade_confirm"] = "Upgrade Dual Cast to Lv{0}.\nRequired trophies will be consumed from inventory.\nProceed?",
                ["dualcast_max_level"] = "Dual Cast is at max level (Lv7).",
                ["dualcast_level_item_required"] = "Not enough trophies for Dual Cast Lv{0} upgrade.",
                ["dualcast_missing_items"] = "Missing: {0}",
                ["dualcast_next_level_req"] = "Lv{0} Upgrade Requirements",
                ["dualcast_upgrade_ready"] = "Ready to upgrade",
                ["item_trophy_leech"] = "Leech Trophy",
                ["item_trophy_charredarcher"] = "Charred Archer Trophy",
                ["stack_explosion_upgrade_title"] = "💥 Weak Point Explosion Upgrade",
                ["stack_explosion_upgrade_confirm"] = "Upgrade Weak Point Explosion to Lv{0}.\nRequired trophies will be consumed from inventory.\nProceed?",
                ["stack_explosion_max_level"] = "Weak Point Explosion is at max level (Lv7).",
                ["stack_explosion_level_item_required"] = "Not enough trophies for Weak Point Explosion Lv{0} upgrade.",
                ["stack_explosion_missing_items"] = "Missing: {0}",
                ["stack_explosion_next_level_req"] = "Lv{0} Upgrade Requirements",
                ["stack_explosion_upgrade_ready"] = "Ready to upgrade",
                ["assassin_heart_upgrade_title"] = "🗡️ Assassin's Heart Upgrade",
                ["assassin_heart_upgrade_confirm"] = "Upgrade Assassin's Heart to Lv{0}.\nRequired trophies will be consumed from inventory.\nProceed?",
                ["assassin_heart_max_level"] = "Assassin's Heart is at max level (Lv7).",
                ["assassin_heart_level_item_required"] = "Not enough trophies for Assassin's Heart Lv{0} upgrade.",
                ["assassin_heart_missing_items"] = "Missing: {0}",
                ["assassin_heart_next_level_req"] = "Lv{0} Upgrade Requirements",
                ["assassin_heart_upgrade_ready"] = "Ready to upgrade",
                ["rush_slash_upgrade_title"] = "⚔️ Rush Slash Upgrade",
                ["rush_slash_upgrade_confirm"] = "Upgrade Rush Slash to Lv{0}.\nRequired trophies will be consumed from inventory.\nProceed?",
                ["rush_slash_max_level"] = "Rush Slash is at max level (Lv7).",
                ["rush_slash_level_item_required"] = "Not enough trophies for Rush Slash Lv{0} upgrade.",
                ["rush_slash_missing_items"] = "Missing: {0}",
                ["rush_slash_next_level_req"] = "Lv{0} Upgrade Requirements",
                ["rush_slash_upgrade_ready"] = "Ready to upgrade",
                ["whirlwind_upgrade_title"] = "🌀 Whirlwind Slash Upgrade",
                ["whirlwind_upgrade_confirm"] = "Upgrade Whirlwind Slash to Lv{0}.\nRequired trophies will be consumed from inventory.\nProceed?",
                ["whirlwind_max_level"] = "Whirlwind Slash is at max level (Lv7).",
                ["whirlwind_level_item_required"] = "Not enough trophies for Whirlwind Slash Lv{0} upgrade.",
                ["whirlwind_missing_items"] = "Missing: {0}",
                ["whirlwind_next_level_req"] = "Lv{0} Upgrade Requirements",
                ["whirlwind_upgrade_ready"] = "Ready to upgrade",
                ["heal_upgrade_title"] = "💚 Heal Skill Upgrade",
                ["heal_upgrade_confirm"] = "Upgrade Heal Skill to Lv{0}.\nRequired trophies will be consumed from inventory.\nProceed?",
                ["heal_max_level"] = "Heal Skill is at max level (Lv7).",
                ["heal_level_item_required"] = "Not enough trophies for Heal Skill Lv{0} upgrade.",
                ["heal_missing_items"] = "Missing: {0}",
                ["heal_next_level_req"] = "Lv{0} Upgrade Requirements",
                ["heal_upgrade_ready"] = "Ready to upgrade",
                ["shield_charge_upgrade_title"] = "🛡️ Shield Charge Upgrade",
                ["shield_charge_upgrade_confirm"] = "Upgrade Shield Charge to Lv{0}.\nRequired trophies will be consumed from inventory.\nProceed?",
                ["shield_charge_max_level"] = "Shield Charge is at max level (Lv7).",
                ["shield_charge_level_item_required"] = "Not enough trophies for Shield Charge Lv{0} upgrade.",
                ["shield_charge_missing_items"] = "Missing: {0}",
                ["shield_charge_next_level_req"] = "Lv{0} Upgrade Requirements",
                ["shield_charge_upgrade_ready"] = "Ready to upgrade",

                ["fury_hammer_upgrade_title"] = "🔨 Fury Hammer Upgrade",
                ["fury_hammer_upgrade_confirm"] = "Upgrade Fury Hammer to Lv{0}.\nRequired trophies will be consumed from inventory.\nProceed?",
                ["fury_hammer_max_level"] = "Fury Hammer is at max level (Lv7).",
                ["fury_hammer_level_item_required"] = "Not enough trophies for Fury Hammer Lv{0} upgrade.",
                ["fury_hammer_missing_items"] = "Missing: {0}",
                ["fury_hammer_next_level_req"] = "Lv{0} Upgrade Requirements",
                ["fury_hammer_upgrade_ready"] = "Ready to upgrade",
                ["item_trophy_neck"] = "Neck Trophy",

                ["penetrate_upgrade_title"] = "⚡ Piercing Spear Upgrade",
                ["penetrate_upgrade_confirm"] = "Upgrade Piercing Spear to Lv{0}.\nRequired trophies will be consumed from inventory.\nProceed?",
                ["penetrate_max_level"] = "Piercing Spear is at max level (Lv7).",
                ["penetrate_level_item_required"] = "Not enough trophies for Piercing Spear Lv{0} upgrade.",
                ["penetrate_missing_items"] = "Missing: {0}",
                ["penetrate_next_level_req"] = "Lv{0} Upgrade Requirements",
                ["penetrate_upgrade_ready"] = "Ready to upgrade",

                ["combo_upgrade_title"] = "🌀 Combo Spear Upgrade",
                ["combo_upgrade_confirm"] = "Upgrade Combo Spear to Lv{0}.\nRequired trophies will be consumed from inventory.\nProceed?",
                ["combo_max_level"] = "Combo Spear is at max level (Lv7).",
                ["combo_level_item_required"] = "Not enough trophies for Combo Spear Lv{0} upgrade.",
                ["combo_missing_items"] = "Missing: {0}",
                ["combo_next_level_req"] = "Lv{0} Upgrade Requirements",
                ["combo_upgrade_ready"] = "Ready to upgrade",

                ["producer_upgrade_title"] = "🛠️ Producer Class Ascension",
                ["producer_upgrade_confirm"] = "Upgrade Producer to Lv{0}?",
                ["producer_missing_items"] = "Missing items: {0}",
                ["ui_reset_confirm_title"] = "Reset Skills Confirm",
                ["ui_reset_confirm_message"] = "Are you sure you want to reset all skills?\nThis action cannot be undone.",
                ["ui_reset_production"] = "Reset Pd",
                ["ui_reset_production_confirm_title"] = "Reset Production Expert Confirm",
                ["ui_reset_production_confirm_message"] = "Are you sure you want to reset Production Expert skills?\nThis action cannot be undone.",
                ["ui_selective_reset_prompt_title"] = "Selective Skill Reset",
                ["ui_selective_reset_prompt_message"] = "Click skills to select them for reset.\nCoins will be consumed per selected skill.\nProceed?",
                ["ui_selective_reset_confirm"] = "Confirm Reset",
                ["ui_selective_reset_cancel"] = "Cancel Selection",
                ["ui_selective_reset_cost_display"] = "Cost: {0} Coins",
                ["ui_selective_reset_insufficient_coins"] = "Not enough coins. (Required: {0}, Have: {1})",
                ["ui_selective_reset_no_selection"] = "Please select skills to reset.",
                ["ui_selective_reset_prerequisite_required"] = "Must deselect dependent skill first.",
                ["ui_selective_reset_success"] = "Skills reset! -{0} Coins",
                ["ui_music_on"] = "Music On",
                ["ui_music_off"] = "Music Off",
                ["ui_escape"] = "Exit",
                ["ui_escape_cooldown"] = "Available in {0}m",
                ["ui_escape_confirm"] = "Emergency Character Escape.\nYou will be moved to the starting point.\nCan be used once every 3 hours.",

                // === Skill Investment Messages ===
                ["skill_insufficient_points_detail"] = "Not enough skill points. (Required: {0}, Available: {1})",
                ["skill_invest_success"] = "✅ Skill points invested!",
                ["items_insufficient"] = "Insufficient items required",

                // === Additional Tooltip Keys ===
                ["tooltip_none"] = "None",
                ["tooltip_self"] = "Self",
                ["tooltip_affect_range"] = "Affect Range",
                ["tooltip_passive_effect"] = "Passive Effect",
                ["tooltip_additional"] = "Additional",
                ["tooltip_no_player"] = "No player info",
                ["tooltip_calculation_error"] = "Calculation error",
                ["tooltip_simulation_error"] = "Simulation error",
                ["tooltip_load_error"] = "Cannot load skill info",
                ["stat_arrow"] = "Arrow",
                ["item_eikthyr_trophy"] = "Eikthyr Trophy",
                ["confirmation_job_only"] = "Only one job can be selected, Level 10+",
                ["confirmation_job_select_only"] = "Only one job can be selected",
                ["skill_type_job_active"] = "Job Active Skill - {0} Key",

                // === StatusEffect Names (L.Get system) ===
                ["se_assassin_heart"] = "Assassin's Heart",
                ["se_assassin_heart_tooltip"] = "Critical Damage x{0}",
                ["se_arrow_rain_frost"] = "Arrow Rain: Frost",
                ["se_ice_breath_slow"] = "Ice Breath: Slow",
                ["se_ice_breath_slow_tooltip"] = "Move Speed -50%",
            };
        }
    }
}
