using System;
using System.Collections.Generic;
using CaptainSkillTree.MMO_System;

namespace CaptainSkillTree.SkillTree
{
    /// <summary>
    /// 서버→클라이언트 Config 브로드캐스트 (partial)
    /// 모든 수치 Config 항목을 포함. 키 바인딩(HotKey*)은 제외.
    /// </summary>
    public static partial class SkillTreeConfig
    {
        public static void BroadcastConfigToClients()
        {
            if (!_isServer) return;

            try
            {
                var configData = new Dictionary<string, float>
                {
                    // ══════════════════════════════════════════════
                    // Global (SkillTreeConfig)
                    // ══════════════════════════════════════════════
                    ["move_speed_max_bonus"]                         = MoveSpeedMaxBonus?.Value ?? 70f,
                    ["attack_speed_max_bonus"]                       = AttackSpeedMaxBonus?.Value ?? 70f,
                    ["Job_Lv1_Cost"]                                 = JobLv1Cost?.Value ?? 1000f,
                    ["Job_Lv2_Cost"]                                 = JobLv2Cost?.Value ?? 2000f,
                    ["Job_Lv3_Cost"]                                 = JobLv3Cost?.Value ?? 3000f,
                    ["Job_Lv4_Cost"]                                 = JobLv4Cost?.Value ?? 4000f,
                    ["Job_Lv5_Cost"]                                 = JobLv5Cost?.Value ?? 5000f,
                    ["ShowResetButtons"]                             = ShowResetButtons?.Value == true ? 1f : 0f,
                    ["Job_Reset_Cost"]                               = JobResetCost?.Value ?? 1000f,
                    ["Active_Reset_Cost"]                            = ActiveResetCost?.Value ?? 500f,
                    ["Passive_Reset_Cost"]                           = PassiveResetCost?.Value ?? 100f,

                    // ══════════════════════════════════════════════
                    // Attack Tree
                    // ══════════════════════════════════════════════
                    ["attack_root_required_points"]                  = Attack_Config.AttackRootRequiredPoints?.Value ?? 2f,
                    ["atk_opener_required_points"]                   = Attack_Config.AtkOpenerRequiredPoints?.Value ?? 3f,
                    ["atk_opener_melee_required_points"]             = Attack_Config.AtkOpenerMeleeRequiredPoints?.Value ?? 2f,
                    ["atk_opener_bow_required_points"]               = Attack_Config.AtkOpenerBowRequiredPoints?.Value ?? 2f,
                    ["atk_opener_crossbow_required_points"]          = Attack_Config.AtkOpenerCrossbowRequiredPoints?.Value ?? 2f,
                    ["atk_opener_magic_required_points"]             = Attack_Config.AtkOpenerMagicRequiredPoints?.Value ?? 2f,
                    ["atk_pursuit_required_points"]                  = Attack_Config.AtkPursuitRequiredPoints?.Value ?? 2f,
                    ["atk_pursuit_speed_required_points"]            = Attack_Config.AtkPursuitSpeedRequiredPoints?.Value ?? 2f,
                    ["atk_frenzy_trigger_required_points"]           = Attack_Config.AtkFrenzyTriggerRequiredPoints?.Value ?? 2f,
                    ["atk_frenzy_required_points"]                   = Attack_Config.AtkFrenzyRequiredPoints?.Value ?? 3f,
                    ["attack_step6_critdmg_required_points"]         = Attack_Config.AttackStep6CritDmgRequiredPoints?.Value ?? 3f,
                    ["attack_step6_finisher_required_points"]        = Attack_Config.AttackStep6FinisherRequiredPoints?.Value ?? 3f,
                    ["attack_step6_twohand_required_points"]         = Attack_Config.AttackStep6TwoHandRequiredPoints?.Value ?? 3f,
                    ["attack_step6_staff_required_points"]           = Attack_Config.AttackStep6StaffRequiredPoints?.Value ?? 3f,
                    ["Attack_Expert_Damage"]                         = Attack_Config.AttackRootDamageBonus?.Value ?? 3f,
                    ["Tier1_Opener_DamageBonus"]                     = Attack_Config.AtkOpenerDamageBonus?.Value ?? 5f,
                    ["Tier1_Opener_StaminaReduction"]                = Attack_Config.AtkOpenerStaminaReduction?.Value ?? 15f,
                    ["Tier1_Opener_Duration"]                        = Attack_Config.AtkOpenerDuration?.Value ?? 5f,
                    ["Tier1_Opener_Cooldown"]                        = Attack_Config.AtkOpenerCooldown?.Value ?? 35f,
                    ["Tier2_OpenerMelee_FinisherBonus"]              = Attack_Config.AtkOpenerMeleeFinisherBonus?.Value ?? 10f,
                    ["Tier2_OpenerBow_CritChance"]                   = Attack_Config.AtkOpenerBowCritChance?.Value ?? 8f,
                    ["Tier2_OpenerCrossbow_FirstShotBonus"]          = Attack_Config.AtkOpenerCrossbowFirstShotBonus?.Value ?? 10f,
                    ["Tier2_OpenerMagic_StaggerProc"]                = Attack_Config.AtkOpenerMagicStaggerProc?.Value ?? 1f,
                    ["Tier3_Pursuit_DamageBonus"]                    = Attack_Config.AtkPursuitDamageBonus?.Value ?? 5f,
                    ["Tier3_Pursuit_ChainDamageBonus"]               = Attack_Config.AtkPursuitChainDamageBonus?.Value ?? 5f,
                    ["Tier3_Pursuit_ChainWindow"]                    = Attack_Config.AtkPursuitChainWindow?.Value ?? 5f,
                    ["Tier4_PursuitSpeed_SpeedBonus"]                = Attack_Config.AtkPursuitSpeedBonus?.Value ?? 12f,
                    ["Tier4_FrenzyTrigger_StaminaReduction"]         = Attack_Config.AtkFrenzyTriggerStaminaReduction?.Value ?? 15f,
                    ["Tier5_Frenzy_StackBonusBase"]                  = Attack_Config.AtkFrenzyStackBonusBase?.Value ?? 5f,
                    ["Tier5_Frenzy_StackBonusChain"]                 = Attack_Config.AtkFrenzyStackBonusChain?.Value ?? 8f,
                    ["Tier5_Frenzy_MaxStacks"]                       = Attack_Config.AtkFrenzyMaxStacks?.Value ?? 5f,
                    ["Tier5_Frenzy_HitsPerStack"]                    = Attack_Config.AtkFrenzyHitsPerStack?.Value ?? 3f,
                    ["Tier5_Frenzy_Tier6Amplifier"]                  = Attack_Config.AtkFrenzyTier6Amplifier?.Value ?? 1.3f,
                    ["Attack_Step6_CritDamageBonus"]                 = Attack_Config.AttackCritDamageBonus?.Value ?? 5f,
                    ["Attack_Step6_TwoHandedBonus"]                  = Attack_Config.AttackTwoHandedBonus?.Value ?? 5f,
                    ["Attack_Step6_StaffElemental"]                  = Attack_Config.AttackStaffElemental?.Value ?? 5f,
                    ["Attack_Step6_FinisherMeleeBonus"]              = Attack_Config.AttackFinisherMeleeBonus?.Value ?? 5f,

                    // ══════════════════════════════════════════════
                    // Speed Tree
                    // ══════════════════════════════════════════════
                    ["speed_root_required_points"]                   = Speed_Config.SpeedRootRequiredPoints?.Value ?? 2f,
                    ["speed_step1_required_points"]                  = Speed_Config.SpeedStep1RequiredPoints?.Value ?? 2f,
                    ["speed_step5_required_points"]                  = Speed_Config.SpeedStep5RequiredPoints?.Value ?? 3f,
                    ["speed_step7_required_points"]                  = Speed_Config.SpeedStep7RequiredPoints?.Value ?? 3f,
                    ["speed_step2_meleeflow_rp"]                     = Speed_Config.SpeedStep2_MeleeFlowRequiredPoints?.Value ?? 2f,
                    ["speed_step2_crossbowexpert_rp"]                = Speed_Config.SpeedStep2_CrossbowExpertRequiredPoints?.Value ?? 2f,
                    ["speed_step2_bowexpert_rp"]                     = Speed_Config.SpeedStep2_BowExpertRequiredPoints?.Value ?? 2f,
                    ["speed_step2_mobilecast_rp"]                    = Speed_Config.SpeedStep2_MobileCastRequiredPoints?.Value ?? 2f,
                    ["speed_step3_practitioner1_rp"]                 = Speed_Config.SpeedStep3_Practitioner1RequiredPoints?.Value ?? 2f,
                    ["speed_step3_practitioner2_rp"]                 = Speed_Config.SpeedStep3_Practitioner2RequiredPoints?.Value ?? 2f,
                    ["speed_step4_energizer_rp"]                     = Speed_Config.SpeedStep4_EnergizerRequiredPoints?.Value ?? 2f,
                    ["speed_step4_captain_rp"]                       = Speed_Config.SpeedStep4_CaptainRequiredPoints?.Value ?? 2f,
                    ["speed_step6_dexterity_rp"]                     = Speed_Config.SpeedStep6_DexterityRequiredPoints?.Value ?? 2f,
                    ["speed_step6_endurance_rp"]                     = Speed_Config.SpeedStep6_EnduranceRequiredPoints?.Value ?? 2f,
                    ["speed_step6_intellect_rp"]                     = Speed_Config.SpeedStep6_IntellectRequiredPoints?.Value ?? 2f,
                    ["speed_step8_meleeaccel_rp"]                    = Speed_Config.SpeedStep8_MeleeAccelRequiredPoints?.Value ?? 2f,
                    ["speed_step8_crossbowaccel_rp"]                 = Speed_Config.SpeedStep8_CrossbowAccelRequiredPoints?.Value ?? 2f,
                    ["speed_step8_bowaccel_rp"]                      = Speed_Config.SpeedStep8_BowAccelRequiredPoints?.Value ?? 2f,
                    ["speed_step8_castaccel_rp"]                     = Speed_Config.SpeedStep8_CastAccelRequiredPoints?.Value ?? 2f,
                    ["Speed_Expert_MoveSpeed"]                       = Speed_Config.SpeedRootMoveSpeed?.Value ?? 5f,
                    ["Speed_Step1_DodgeMoveSpeed"]                   = Speed_Config.SpeedBaseDodgeMoveSpeed?.Value ?? 10f,
                    ["Speed_Step1_DodgeDuration"]                    = Speed_Config.SpeedBaseDodgeDuration?.Value ?? 0.1f,
                    ["Speed_Step2_MeleeComboAttackSpeed"]            = Speed_Config.SpeedMeleeComboAttackSpeed?.Value ?? 10f,
                    ["Speed_Step2_MeleeComboStamina"]                = Speed_Config.SpeedMeleeComboStamina?.Value ?? 10f,
                    ["Speed_Step2_MeleeComboDuration"]               = Speed_Config.SpeedMeleeComboDuration?.Value ?? 5f,
                    ["Speed_Step2_CrossbowExpertSpeed"]              = Speed_Config.SpeedCrossbowExpertSpeed?.Value ?? 10f,
                    ["Speed_Step2_CrossbowExpertDuration"]           = Speed_Config.SpeedCrossbowExpertDuration?.Value ?? 5f,
                    ["Speed_Step2_CrossbowExpertReload"]             = Speed_Config.SpeedCrossbowExpertReload?.Value ?? 10f,
                    ["Speed_Step2_BowExpertStamina"]                 = Speed_Config.SpeedBowExpertStamina?.Value ?? 10f,
                    ["Speed_Step2_BowExpertDrawSpeed"]               = Speed_Config.SpeedBowExpertDrawSpeed?.Value ?? 10f,
                    ["Speed_Step2_StaffCastMoveSpeed"]               = Speed_Config.SpeedStaffCastMoveSpeed?.Value ?? 10f,
                    ["Speed_Step2_StaffCastEitrReduction"]           = Speed_Config.SpeedStaffCastEitrReduction?.Value ?? 10f,
                    ["Speed_Step3_Ex1MeleeSkill"]                    = Speed_Config.SpeedEx1MeleeSkill?.Value ?? 5f,
                    ["Speed_Step3_Ex1CrossbowSkill"]                 = Speed_Config.SpeedEx1CrossbowSkill?.Value ?? 5f,
                    ["Speed_Step3_Ex2StaffSkill"]                    = Speed_Config.SpeedEx2StaffSkill?.Value ?? 5f,
                    ["Speed_Step3_Ex2BowSkill"]                      = Speed_Config.SpeedEx2BowSkill?.Value ?? 5f,
                    ["Speed_Step4_FoodEfficiency"]                   = Speed_Config.SpeedFoodEfficiency?.Value ?? 5f,
                    ["Speed_Step4_ShipBonus"]                        = Speed_Config.SpeedShipBonus?.Value ?? 5f,
                    ["Speed_Step5_JumpSkillLevel"]                   = Speed_Config.JumpSkillLevelBonus?.Value ?? 1f,
                    ["Speed_Step5_JumpStamina"]                      = Speed_Config.JumpStaminaReduction?.Value ?? 10f,
                    ["Speed_Step6_DexAttackSpeed"]                   = Speed_Config.SpeedDexterityAttackSpeedBonus?.Value ?? 5f,
                    ["Speed_Step6_DexMoveSpeed"]                     = Speed_Config.SpeedDexterityMoveSpeedBonus?.Value ?? 3f,
                    ["Speed_Step6_EnduranceStamina"]                 = Speed_Config.SpeedEnduranceStaminaBonus?.Value ?? 10f,
                    ["Speed_Step6_IntellectEitr"]                    = Speed_Config.SpeedIntellectEitrBonus?.Value ?? 10f,
                    ["Speed_Step7_AllMasterRun"]                     = Speed_Config.AllMasterRunSkill?.Value ?? 5f,
                    ["Speed_Step7_AllMasterJump"]                    = Speed_Config.AllMasterJumpSkill?.Value ?? 5f,
                    ["Speed_Step8_MeleeAttackSpeed"]                 = Speed_Config.SpeedMeleeAttackSpeed?.Value ?? 10f,
                    ["Speed_Step8_MeleeTripleBonus"]                 = Speed_Config.SpeedMeleeComboTripleBonus?.Value ?? 10f,
                    ["Speed_Step8_CrossbowDrawSpeed"]                = Speed_Config.SpeedCrossbowDrawSpeed?.Value ?? 10f,
                    ["Speed_Step8_CrossbowReloadMove"]               = Speed_Config.SpeedCrossbowReloadMoveSpeed?.Value ?? 5f,
                    ["Speed_Step8_BowDrawSpeed"]                     = Speed_Config.SpeedBowDrawSpeed?.Value ?? 10f,
                    ["Speed_Step8_BowDrawMove"]                      = Speed_Config.SpeedBowDrawMoveSpeed?.Value ?? 5f,
                    ["Speed_Step8_StaffCastSpeed"]                   = Speed_Config.SpeedStaffCastSpeedFinal?.Value ?? 10f,
                    ["Speed_Step8_StaffTripleEitr"]                  = Speed_Config.SpeedStaffTripleEitrRecovery?.Value ?? 5f,
                    ["Speed_Tier1_BaseAttackSpeed"]                  = Speed_Config.SpeedBaseAttackSpeed?.Value ?? 3f,
                    ["Speed_Tier1_BaseDodgeSpeed"]                   = Speed_Config.SpeedBaseDodgeSpeed?.Value ?? 3f,
                    ["Speed_Tier2_MeleeComboSpeed"]                  = Speed_Config.SpeedMeleeComboSpeed?.Value ?? 5f,
                    ["Speed_Tier2_BowExpertDuration"]                = Speed_Config.SpeedBowExpertDuration?.Value ?? 5f,
                    ["Speed_Tier2_StaffCastSpeed"]                   = Speed_Config.SpeedStaffCastSpeed?.Value ?? 5f,
                    ["Speed_Tier2_MeleeComboBonus"]                  = Speed_Config.SpeedMeleeComboStamina?.Value ?? 5f,
                    ["Speed_Tier2_CrossbowReloadSpeed"]              = Speed_Config.SpeedCrossbowDrawSpeed?.Value ?? 5f,
                    ["Speed_Tier2_BowHitBonus"]                      = Speed_Config.SpeedBowExpertStamina?.Value ?? 5f,
                    ["Speed_Tier2_BowHitDuration"]                   = Speed_Config.SpeedBowExpertDuration?.Value ?? 5f,

                    // ══════════════════════════════════════════════
                    // Defense Tree
                    // ══════════════════════════════════════════════
                    ["defense_root_required_points"]                 = Defense_Config.DefenseRootRequiredPoints?.Value ?? 2f,
                    ["defense_step1_required_points"]                = Defense_Config.DefenseStep1RequiredPoints?.Value ?? 2f,
                    ["defense_step2_dodge_required_points"]          = Defense_Config.DefenseStep2DodgeRequiredPoints?.Value ?? 2f,
                    ["defense_step2_health_required_points"]         = Defense_Config.DefenseStep2HealthRequiredPoints?.Value ?? 2f,
                    ["defense_step3_breath_required_points"]         = Defense_Config.DefenseStep3BreathRequiredPoints?.Value ?? 3f,
                    ["defense_step3_agile_required_points"]          = Defense_Config.DefenseStep3AgileRequiredPoints?.Value ?? 3f,
                    ["defense_step3_boost_required_points"]          = Defense_Config.DefenseStep3BoostRequiredPoints?.Value ?? 3f,
                    ["defense_step3_shield_required_points"]         = Defense_Config.DefenseStep3ShieldRequiredPoints?.Value ?? 3f,
                    ["defense_step4_mental_required_points"]         = Defense_Config.DefenseStep4MentalRequiredPoints?.Value ?? 3f,
                    ["defense_step4_instant_required_points"]        = Defense_Config.DefenseStep4InstantRequiredPoints?.Value ?? 3f,
                    ["defense_step4_tanker_required_points"]         = Defense_Config.DefenseStep4TankerRequiredPoints?.Value ?? 3f,
                    ["defense_step5_focus_required_points"]          = Defense_Config.DefenseStep5FocusRequiredPoints?.Value ?? 3f,
                    ["defense_step5_stamina_required_points"]        = Defense_Config.DefenseStep5StaminaRequiredPoints?.Value ?? 3f,
                    ["defense_step5_heal_required_points"]           = Defense_Config.DefenseStep5HealRequiredPoints?.Value ?? 3f,
                    ["defense_step5_parry_required_points"]          = Defense_Config.DefenseStep5ParryRequiredPoints?.Value ?? 3f,
                    ["defense_step6_mind_required_points"]           = Defense_Config.DefenseStep6MindRequiredPoints?.Value ?? 4f,
                    ["defense_step6_attack_required_points"]         = Defense_Config.DefenseStep6AttackRequiredPoints?.Value ?? 4f,
                    ["defense_step6_doublejump_required_points"]     = Defense_Config.DefenseStep6DoubleJumpRequiredPoints?.Value ?? 4f,
                    ["defense_step6_body_required_points"]           = Defense_Config.DefenseStep6BodyRequiredPoints?.Value ?? 4f,
                    ["defense_step6_true_required_points"]           = Defense_Config.DefenseStep6TrueRequiredPoints?.Value ?? 4f,
                    ["Defense_Root_HealthBonus"]                     = Defense_Config.DefenseRootHealthBonus?.Value ?? 5f,
                    ["Defense_Root_ArmorBonus"]                      = Defense_Config.DefenseRootArmorBonus?.Value ?? 2f,
                    ["Defense_Survival_HealthBonus"]                 = Defense_Config.SurvivalHealthBonus?.Value ?? 5f,
                    ["Defense_Survival_ArmorBonus"]                  = Defense_Config.SurvivalArmorBonus?.Value ?? 5f,
                    ["Defense_Dodge_StaminaBonus"]                   = Defense_Config.DodgeStaminaBonus?.Value ?? 10f,
                    ["Defense_Dodge_EitrBonus"]                      = Defense_Config.DodgeEitrBonus?.Value ?? 10f,
                    ["Defense_Health_HealthBonus"]                   = Defense_Config.HealthBonus?.Value ?? 20f,
                    ["Defense_Health_ArmorBonus"]                    = Defense_Config.HealthArmorBonus?.Value ?? 5f,
                    ["Defense_Breath_EitrBonus"]                     = Defense_Config.BreathEitrBonus?.Value ?? 10f,
                    ["Defense_Agile_DodgeBonus"]                     = Defense_Config.AgileDodgeBonus?.Value ?? 5f,
                    ["Defense_Agile_InvincibilityBonus"]             = Defense_Config.AgileInvincibilityBonus?.Value ?? 20f,
                    ["Defense_Boost_HealthBonus"]                    = Defense_Config.BoostHealthBonus?.Value ?? 15f,
                    ["Defense_ShieldTraining_BlockPower"]            = Defense_Config.ShieldTrainingBlockPowerBonus?.Value ?? 30f,
                    ["Defense_Shockwave_Radius"]                     = Defense_Config.ShockwaveRadius?.Value ?? 3f,
                    ["Defense_Shockwave_StunDuration"]               = Defense_Config.ShockwaveStunDuration?.Value ?? 1f,
                    ["Defense_Shockwave_Cooldown"]                   = Defense_Config.ShockwaveCooldown?.Value ?? 120f,
                    ["Defense_Tanker_ArmorBonus"]                    = Defense_Config.TankerArmorBonus?.Value ?? 12f,
                    ["Defense_Stomp_Radius"]                         = Defense_Config.StompRadius?.Value ?? 3f,
                    ["Defense_Stomp_Knockback"]                      = Defense_Config.StompKnockback?.Value ?? 20f,
                    ["Defense_Stomp_Cooldown"]                       = Defense_Config.StompCooldown?.Value ?? 120f,
                    ["Defense_Stomp_HealthThreshold"]                = Defense_Config.StompHealthThreshold?.Value ?? 0.35f,
                    ["Defense_Stomp_VFXDuration"]                    = Defense_Config.StompVFXDuration?.Value ?? 1f,
                    ["Defense_Focus_RunStaminaReduction"]            = Defense_Config.FocusRunStaminaReduction?.Value ?? 10f,
                    ["Defense_Focus_JumpStaminaReduction"]           = Defense_Config.FocusJumpStaminaReduction?.Value ?? 10f,
                    ["Defense_Stamina_DodgeBonus"]                   = Defense_Config.StaminaDodgeBonus?.Value ?? 5f,
                    ["Defense_Stamina_RollStaminaReduction"]         = Defense_Config.StaminaRollStaminaReduction?.Value ?? 12f,
                    ["Defense_TrollRegen_Bonus"]                     = Defense_Config.TrollRegenBonus?.Value ?? 2f,
                    ["Defense_TrollRegen_Interval"]                  = Defense_Config.TrollRegenInterval?.Value ?? 2f,
                    ["Defense_ParryMaster_BlockPower"]               = Defense_Config.ParryMasterBlockPowerBonus?.Value ?? 40f,
                    ["Defense_ParryMaster_ParryDuration"]            = Defense_Config.ParryMasterParryDurationBonus?.Value ?? 1f,
                    ["Defense_Attack_DodgeBonus"]                    = Defense_Config.AttackDodgeBonus?.Value ?? 5f,
                    ["Defense_Body_HealthBonus"]                     = Defense_Config.BodyHealthBonus?.Value ?? 30f,
                    ["Defense_Body_ArmorBonus"]                      = Defense_Config.BodyArmorBonus?.Value ?? 10f,
                    ["Defense_JotunnShield_BlockStaminaReduction"]   = Defense_Config.JotunnShieldBlockStaminaReduction?.Value ?? 25f,
                    ["Defense_JotunnShield_NormalSpeedBonus"]        = Defense_Config.JotunnShieldNormalSpeedBonus?.Value ?? 5f,
                    ["Defense_JotunnShield_TowerSpeedBonus"]         = Defense_Config.JotunnShieldTowerSpeedBonus?.Value ?? 10f,

                    // ══════════════════════════════════════════════
                    // Spear Tree
                    // ══════════════════════════════════════════════
                    ["spear_expert_required_points"]                 = Spear_Config.SpearExpertRequiredPoints?.Value ?? 2f,
                    ["spear_step1_required_points"]                  = Spear_Config.SpearStep1RequiredPoints?.Value ?? 2f,
                    ["spear_step2_required_points"]                  = Spear_Config.SpearStep2RequiredPoints?.Value ?? 2f,
                    ["spear_step3_required_points"]                  = Spear_Config.SpearStep3RequiredPoints?.Value ?? 2f,
                    ["spear_step4_required_points"]                  = Spear_Config.SpearStep4RequiredPoints?.Value ?? 2f,
                    ["spear_penetrate_required_points"]              = Spear_Config.SpearPenetrateRequiredPoints?.Value ?? 3f,
                    ["spear_combo_required_points"]                  = Spear_Config.SpearComboRequiredPoints?.Value ?? 3f,
                    ["spear_Step1_attack_speed"]                     = Spear_Config.SpearStep1AttackSpeed?.Value ?? 10f,
                    ["spear_Step1_damage_bonus"]                     = Spear_Config.SpearStep1DamageBonus?.Value ?? 10f,
                    ["spear_Step1_duration"]                         = Spear_Config.SpearStep1Duration?.Value ?? 5f,
                    ["spear_Step1_throw_cooldown"]                   = Spear_Config.SpearStep1ThrowCooldown?.Value ?? 15f,
                    ["spear_Step1_throw_damage"]                     = Spear_Config.SpearStep1ThrowDamage?.Value ?? 1.5f,
                    ["spear_Step1_crit_damage_bonus"]                = Spear_Config.SpearStep1CritDamageBonus?.Value ?? 20f,
                    ["spear_Step2_evasion_bonus"]                    = Spear_Config.SpearStep2EvasionBonus?.Value ?? 15f,
                    ["spear_Step2_evasion_stamina_reduction"]        = Spear_Config.SpearStep2EvasionStaminaReduction?.Value ?? 10f,
                    ["spear_Step3_pierce_damage"]                    = Spear_Config.SpearStep3PierceDamageBonus?.Value ?? 15f,
                    ["spear_Step3_quick_attack_speed"]               = Spear_Config.SpearQuickAttackSpeed?.Value ?? 15f,
                    ["spear_expert_proc_chance"]                     = Spear_Config.SpearExpertProcChance?.Value ?? 30f,
                    ["spear_expert_speed_boost"]                     = Spear_Config.SpearExpertSpeedBoostPercent?.Value ?? 10f,
                    ["spear_dual_damage_bonus"]                      = Spear_Config.SpearDualDamageBonus?.Value ?? 20f,
                    ["spear_dual_duration"]                          = Spear_Config.SpearDualDuration?.Value ?? 5f,
                    ["spear_Step5_penetrate_buff_duration"]          = Spear_Config.SpearStep5PenetrateBuffDuration?.Value ?? 10f,
                    ["spear_Step5_penetrate_lightning_damage"]       = Spear_Config.SpearStep5PenetrateLightningDamage?.Value ?? 30f,
                    ["spear_Step5_penetrate_combo_count"]            = Spear_Config.SpearStep5PenetrateComboCount?.Value ?? 3f,
                    ["spear_Step5_penetrate_cooldown"]               = Spear_Config.SpearStep5PenetrateCooldown?.Value ?? 20f,
                    ["spear_Step5_penetrate_stamina_cost"]           = Spear_Config.SpearStep5PenetrateStaminaCost?.Value ?? 20f,
                    ["spear_Step5_combo_cooldown"]                   = Spear_Config.SpearStep5ComboCooldown?.Value ?? 20f,
                    ["spear_Step5_combo_damage"]                     = Spear_Config.SpearStep5ComboDamage?.Value ?? 1.2f,
                    ["spear_Step5_combo_stamina_cost"]               = Spear_Config.SpearStep5ComboStaminaCost?.Value ?? 15f,
                    ["spear_Step5_combo_knockback_radius"]           = Spear_Config.SpearStep5ComboKnockbackRadius?.Value ?? 5f,
                    ["spear_Step5_combo_range"]                      = Spear_Config.SpearStep5ComboRange?.Value ?? 8f,
                    ["spear_Step5_combo_buff_duration"]              = Spear_Config.SpearStep5ComboBuffDuration?.Value ?? 8f,
                    ["spear_Step5_combo_max_uses"]                   = Spear_Config.SpearStep5ComboMaxUses?.Value ?? 3f,

                    // ══════════════════════════════════════════════
                    // Bow Tree
                    // ══════════════════════════════════════════════
                    ["bow_expert_required_points"]                   = Bow_Config.BowExpertRequiredPoints?.Value ?? 2f,
                    ["bow_focusshot_required_points"]                = Bow_Config.BowFocusShotRequiredPoints?.Value ?? 2f,
                    ["bow_multishot_required_points"]                = Bow_Config.BowMultishotRequiredPoints?.Value ?? 2f,
                    ["bow_step3_required_points"]                    = Bow_Config.BowStep3RequiredPoints?.Value ?? 2f,
                    ["bow_silentstrike_required_points"]             = Bow_Config.BowSilentStrikeRequiredPoints?.Value ?? 2f,
                    ["bow_step4_required_points"]                    = Bow_Config.BowStep4RequiredPoints?.Value ?? 3f,
                    ["bow_huntinginstinct_required_points"]          = Bow_Config.BowHuntingInstinctRequiredPoints?.Value ?? 3f,
                    ["bow_step5_required_points"]                    = Bow_Config.BowStep5RequiredPoints?.Value ?? 3f,
                    ["bow_explosive_required_points"]                = Bow_Config.BowExplosiveArrowRequiredPoints?.Value ?? 4f,
                    ["Bow_MultiShot_Lv1_Chance"]                     = Bow_Config.BowMultishotLv1Chance?.Value ?? 30f,
                    ["Bow_MultiShot_Lv2_Chance"]                     = Bow_Config.BowMultishotLv2Chance?.Value ?? 60f,
                    ["Bow_MultiShot_ArrowCount"]                     = Bow_Config.BowMultishotArrowCount?.Value ?? 2f,
                    ["Bow_MultiShot_ArrowConsumption"]               = Bow_Config.BowMultishotArrowConsumption?.Value ?? 2f,
                    ["Bow_MultiShot_DamagePercent"]                  = Bow_Config.BowMultishotDamagePercent?.Value ?? 70f,
                    ["bow_Step1_expert_damage_bonus"]                = Bow_Config.BowStep1ExpertDamageBonus?.Value ?? 10f,
                    ["bow_Step2_headshot_zone_ratio"]                = Bow_Config.BowHeadshotZoneRatio?.Value ?? 0.25f,
                    ["bow_Step3_speedshot_skill_bonus"]              = Bow_Config.BowStep3SpeedShotSkillBonus?.Value ?? 5f,
                    ["bow_Step3_silentshot_damage_bonus"]            = Bow_Config.BowStep3SilentShotDamageBonus?.Value ?? 20f,
                    ["bow_Step3_special_arrow_chance"]               = Bow_Config.BowStep3SpecialArrowChance?.Value ?? 10f,
                    ["bow_Step5_instinct_crit_bonus"]                = Bow_Config.BowStep5InstinctCritBonus?.Value ?? 15f,
                    ["bow_Step5_master_crit_damage"]                 = Bow_Config.BowStep5MasterCritDamage?.Value ?? 20f,
                    ["bow_Step6_explosive_damage"]                   = Bow_Config.BowExplosiveArrowDamage?.Value ?? 80f,
                    ["bow_Step6_explosive_cooldown"]                 = Bow_Config.BowExplosiveArrowCooldown?.Value ?? 30f,
                    ["bow_Step6_explosive_stamina_cost"]             = Bow_Config.BowExplosiveArrowStaminaCost?.Value ?? 20f,
                    ["bow_Step6_explosive_radius"]                   = Bow_Config.BowExplosiveArrowRadius?.Value ?? 3f,
                    ["bow_Step6_arrow_rain_damage"]                  = Bow_Config.ArrowRainDamagePercent?.Value ?? 60f,
                    ["bow_Step6_arrow_rain_count"]                   = Bow_Config.ArrowRainArrowCount?.Value ?? 10f,
                    ["bow_Step6_arrow_rain_radius"]                  = Bow_Config.ArrowRainRadius?.Value ?? 8f,
                    ["bow_Step6_arrow_rain_cooldown"]                = Bow_Config.ArrowRainCooldown?.Value ?? 30f,
                    ["bow_Step6_arrow_rain_stamina"]                 = Bow_Config.ArrowRainStaminaCost?.Value ?? 20f,
                    ["bow_Step6_arrow_rain_points"]                  = Bow_Config.ArrowRainRequiredPoints?.Value ?? 4f,

                    // ══════════════════════════════════════════════
                    // Crossbow Tree
                    // ══════════════════════════════════════════════
                    ["crossbow_expert_required_points"]              = Crossbow_Config.CrossbowExpertRequiredPoints?.Value ?? 2f,
                    ["crossbow_step2_required_points"]               = Crossbow_Config.CrossbowStep2RequiredPoints?.Value ?? 2f,
                    ["crossbow_balanced_aim_required_points"]        = Crossbow_Config.CrossbowBalancedAimRequiredPoints?.Value ?? 2f,
                    ["crossbow_rapid_reload_required_points"]        = Crossbow_Config.CrossbowRapidReloadRequiredPoints?.Value ?? 2f,
                    ["crossbow_honest_shot_required_points"]         = Crossbow_Config.CrossbowHonestShotRequiredPoints?.Value ?? 2f,
                    ["crossbow_step4_required_points"]               = Crossbow_Config.CrossbowStep4RequiredPoints?.Value ?? 2f,
                    ["crossbow_rapid_fire_lv2_required_points"]      = Crossbow_Config.CrossbowRapidFireLv2RequiredPoints?.Value ?? 3f,
                    ["crossbow_final_strike_required_points"]        = Crossbow_Config.CrossbowFinalStrikeRequiredPoints?.Value ?? 3f,
                    ["crossbow_oneshot_required_points"]             = Crossbow_Config.CrossbowOneShotRequiredPoints?.Value ?? 4f,
                    ["crossbow_ice_breath_required_points"]          = Crossbow_Config.CrossbowIceBreathRequiredPoints?.Value ?? 4f,
                    ["crossbow_expert_damage_bonus"]                 = Crossbow_Config.CrossbowExpertDamageBonus?.Value ?? 5f,
                    ["crossbow_rapid_fire_chance"]                   = Crossbow_Config.CrossbowRapidFireChance?.Value ?? 15f,
                    ["crossbow_rapid_fire_shots"]                    = Crossbow_Config.CrossbowRapidFireShotCount?.Value ?? 3f,
                    ["crossbow_rapid_fire_damage"]                   = Crossbow_Config.CrossbowRapidFireDamagePercent?.Value ?? 35f,
                    ["crossbow_rapid_fire_delay"]                    = Crossbow_Config.CrossbowRapidFireDelay?.Value ?? 0.33f,
                    ["crossbow_rapid_fire_bolt_consumption"]         = Crossbow_Config.CrossbowRapidFireBoltConsumption?.Value ?? 1f,
                    ["crossbow_balance_knockback_chance"]            = Crossbow_Config.CrossbowBalanceKnockbackChance?.Value ?? 30f,
                    ["crossbow_balance_knockback_distance"]          = Crossbow_Config.CrossbowBalanceKnockbackDistance?.Value ?? 3f,
                    ["crossbow_rapid_reload_speed"]                  = Crossbow_Config.CrossbowRapidReloadSpeed?.Value ?? 10f,
                    ["crossbow_mark_damage_bonus"]                   = Crossbow_Config.CrossbowMarkDamageBonus?.Value ?? 35f,
                    ["crossbow_auto_reload_chance"]                  = Crossbow_Config.CrossbowAutoReloadChance?.Value ?? 30f,
                    ["crossbow_rapid_fire_lv2_chance"]               = Crossbow_Config.CrossbowRapidFireLv2Chance?.Value ?? 30f,
                    ["crossbow_rapid_fire_lv2_shots"]                = Crossbow_Config.CrossbowRapidFireLv2ShotCount?.Value ?? 3f,
                    ["crossbow_rapid_fire_lv2_damage"]               = Crossbow_Config.CrossbowRapidFireLv2DamagePercent?.Value ?? 35f,
                    ["crossbow_rapid_fire_lv2_delay"]                = Crossbow_Config.CrossbowRapidFireLv2Delay?.Value ?? 0.33f,
                    ["crossbow_rapid_fire_lv2_bolt_consumption"]     = Crossbow_Config.CrossbowRapidFireLv2BoltConsumption?.Value ?? 1f,
                    ["crossbow_final_strike_hp_threshold"]           = Crossbow_Config.CrossbowFinalStrikeHpThreshold?.Value ?? 50f,
                    ["crossbow_final_strike_damage_bonus"]           = Crossbow_Config.CrossbowFinalStrikeDamageBonus?.Value ?? 30f,
                    ["crossbow_one_shot_duration"]                   = Crossbow_Config.CrossbowOneShotDuration?.Value ?? 30f,
                    ["crossbow_one_shot_damage_bonus"]               = Crossbow_Config.CrossbowOneShotDamageBonus?.Value ?? 120f,
                    ["crossbow_one_shot_knockback"]                  = Crossbow_Config.CrossbowOneShotKnockback?.Value ?? 5f,
                    ["crossbow_one_shot_cooldown"]                   = Crossbow_Config.CrossbowOneShotCooldown?.Value ?? 60f,
                    ["crossbow_ice_breath_cooldown"]                 = Crossbow_Config.CrossbowIceBreathCooldown?.Value ?? 35f,
                    ["crossbow_ice_breath_stamina"]                  = Crossbow_Config.CrossbowIceBreathStaminaCost?.Value ?? 20f,
                    ["crossbow_ice_breath_first_hit_pct"]            = Crossbow_Config.CrossbowIceBreathFirstHitPct?.Value ?? 80f,
                    ["crossbow_ice_breath_dot_pct"]                  = Crossbow_Config.CrossbowIceBreathDotPct?.Value ?? 35f,
                    ["crossbow_ice_breath_dot_count"]                = Crossbow_Config.CrossbowIceBreathDotCount?.Value ?? 5f,

                    // ══════════════════════════════════════════════
                    // Mace Tree
                    // ══════════════════════════════════════════════
                    ["Mace_Expert_RequiredPoints"]                   = Mace_Config.MaceExpertRequiredPoints?.Value ?? 2f,
                    ["Mace_Expert_DamageBonus"]                      = Mace_Config.MaceExpertDamageBonus?.Value ?? 5f,
                    ["Mace_Expert_StunChance"]                       = Mace_Config.MaceExpertStunChance?.Value ?? 20f,
                    ["Mace_Expert_StunDuration"]                     = Mace_Config.MaceExpertStunDuration?.Value ?? 0.5f,
                    ["Mace_Step1_RequiredPoints"]                    = Mace_Config.MaceStep1RequiredPoints?.Value ?? 1f,
                    ["Mace_Step1_DamageBonus"]                       = Mace_Config.MaceStep1DamageBonus?.Value ?? 10f,
                    ["Mace_Step2_RequiredPoints"]                    = Mace_Config.MaceStep2RequiredPoints?.Value ?? 2f,
                    ["Mace_Step2_StunChanceBonus"]                   = Mace_Config.MaceStep2StunChanceBonus?.Value ?? 15f,
                    ["Mace_Step2_StunDurationBonus"]                 = Mace_Config.MaceStep2StunDurationBonus?.Value ?? 0.5f,
                    ["Mace_Step3_Guard_RequiredPoints"]              = Mace_Config.MaceStep3GuardRequiredPoints?.Value ?? 2f,
                    ["Mace_Step3_SpinStrike_DamageBonus"]            = Mace_Config.MaceStep3SpinDamageBonus?.Value ?? 20f,
                    ["Mace_Step3_SpinStrike_Range"]                  = Mace_Config.MaceStep3SpinRange?.Value ?? 12f,
                    ["Mace_Step3_Heavy_RequiredPoints"]              = Mace_Config.MaceStep3HeavyRequiredPoints?.Value ?? 3f,
                    ["Mace_Step3_Heavy_DamageBonus"]                 = Mace_Config.MaceStep3HeavyDamageBonus?.Value ?? 20f,
                    ["Mace_Step4_RequiredPoints"]                    = Mace_Config.MaceStep4RequiredPoints?.Value ?? 3f,
                    ["Mace_Step4_KnockbackChance"]                   = Mace_Config.MaceStep4KnockbackChance?.Value ?? 30f,
                    ["Mace_Step5_Tank_RequiredPoints"]               = Mace_Config.MaceStep5TankRequiredPoints?.Value ?? 2f,
                    ["Mace_Step5_Tank_HealthBonus"]                  = Mace_Config.MaceStep5TankHealthBonus?.Value ?? 25f,
                    ["Mace_Step5_Tank_DamageReduction"]              = Mace_Config.MaceStep5TankDamageReduction?.Value ?? 10f,
                    ["Mace_Step5_Dps_RequiredPoints"]                = Mace_Config.MaceStep5DpsRequiredPoints?.Value ?? 3f,
                    ["Mace_Step5_Dps_DamageBonus"]                   = Mace_Config.MaceStep5DpsDamageBonus?.Value ?? 20f,
                    ["Mace_Step6_RequiredPoints"]                    = Mace_Config.MaceStep6RequiredPoints?.Value ?? 2f,
                    ["Mace_Step6_Sokgong_AttackSpeedBonus"]          = Mace_Config.MaceStep6AttackSpeedBonus?.Value ?? 10f,
                    ["Mace_FuryHammer_RequiredPoints"]               = Mace_Config.FuryHammerRequiredPoints?.Value ?? 3f,
                    ["Mace_FuryHammer_NormalHitMultiplier"]          = Mace_Config.FuryHammerNormalHitMultiplier?.Value ?? 40f,
                    ["Mace_FuryHammer_FinalHitMultiplier"]           = Mace_Config.FuryHammerFinalHitMultiplier?.Value ?? 60f,
                    ["Mace_FuryHammer_StaminaCost"]                  = Mace_Config.FuryHammerStaminaCost?.Value ?? 30f,
                    ["Mace_FuryHammer_Cooldown"]                     = Mace_Config.FuryHammerCooldown?.Value ?? 30f,
                    ["Mace_FuryHammer_AoeRadius"]                    = Mace_Config.FuryHammerAoeRadius?.Value ?? 5f,
                    ["Mace_GuardianHeart_Cooldown"]                  = Mace_Config.GuardianHeartCooldown?.Value ?? 35f,
                    ["Mace_GuardianHeart_StaminaCost"]               = Mace_Config.GuardianHeartStaminaCost?.Value ?? 20f,
                    ["Mace_ShieldCharge_DamagePercent"]              = Mace_Config.ShieldChargeDamagePercent?.Value ?? 70f,
                    ["Mace_GuardianHeart_RequiredPoints"]            = Mace_Config.GuardianHeartRequiredPoints?.Value ?? 3f,

                    // ══════════════════════════════════════════════
                    // Knife Tree
                    // ══════════════════════════════════════════════
                    ["knife_expert_required_points"]                 = Knife_Config.KnifeExpertRequiredPoints?.Value ?? 1f,
                    ["knife_step2_required_points"]                  = Knife_Config.KnifeEvasionRequiredPoints?.Value ?? 1f,
                    ["knife_step3_required_points"]                  = Knife_Config.KnifeMoveSpeedRequiredPoints?.Value ?? 1f,
                    ["knife_step4_required_points"]                  = Knife_Config.KnifeAttackSpeedRequiredPoints?.Value ?? 1f,
                    ["knife_step5_required_points"]                  = Knife_Config.KnifeCritRateRequiredPoints?.Value ?? 1f,
                    ["knife_step6_required_points"]                  = Knife_Config.KnifeCombatDamageRequiredPoints?.Value ?? 1f,
                    ["knife_step7_required_points"]                  = Knife_Config.KnifeExecutionRequiredPoints?.Value ?? 1f,
                    ["knife_step8_required_points"]                  = Knife_Config.KnifeAssassinationRequiredPoints?.Value ?? 1f,
                    ["knife_step9_required_points"]                  = Knife_Config.KnifeAssassinHeartRequiredPoints?.Value ?? 1f,
                    ["knife_step10_required_points"]                 = Knife_Config.KnifeStackExplosionRequiredPoints?.Value ?? 3f,
                    ["knife_expert_backstab_bonus"]                  = Knife_Config.KnifeExpertBackstabBonus?.Value ?? 200f,
                    ["knife_step2_evasion_bonus"]                    = Knife_Config.KnifeEvasionBonus?.Value ?? 30f,
                    ["knife_step2_evasion_duration"]                 = Knife_Config.KnifeEvasionDuration?.Value ?? 3f,
                    ["knife_step3_move_speed_bonus"]                 = Knife_Config.KnifeMoveSpeedBonus?.Value ?? 20f,
                    ["knife_step4_attack_damage_bonus"]              = Knife_Config.KnifeAttackDamageBonus?.Value ?? 1f,
                    ["knife_step4_attack_damage_duration"]           = Knife_Config.KnifeAttackDamageDuration?.Value ?? 10f,
                    ["knife_step5_attack_evasion_bonus"]             = Knife_Config.KnifeAttackEvasionBonus?.Value ?? 25f,
                    ["knife_step5_attack_evasion_duration"]          = Knife_Config.KnifeAttackEvasionDuration?.Value ?? 10f,
                    ["knife_step5_attack_evasion_cooldown"]          = Knife_Config.KnifeAttackEvasionCooldown?.Value ?? 30f,
                    ["knife_step6_combat_damage_bonus"]              = Knife_Config.KnifeCombatDamageBonus?.Value ?? 25f,
                    ["knife_step7_execution_crit_damage"]            = Knife_Config.KnifeExecutionCritDamage?.Value ?? 25f,
                    ["knife_step7_execution_crit_chance"]            = Knife_Config.KnifeExecutionCritChance?.Value ?? 12f,
                    ["knife_step8_assassination_stagger_chance"]     = Knife_Config.KnifeAssassinationStaggerChance?.Value ?? 38f,
                    ["knife_step8_assassination_required_hits"]      = Knife_Config.KnifeAssassinationRequiredHits?.Value ?? 3f,
                    ["knife_step9_assassin_heart_crit_damage"]       = Knife_Config.KnifeAssassinHeartCritDamage?.Value ?? 2f,
                    ["knife_step9_assassin_heart_duration"]          = Knife_Config.KnifeAssassinHeartDuration?.Value ?? 15f,
                    ["knife_step9_assassin_heart_stamina_cost"]      = Knife_Config.KnifeAssassinHeartStaminaCost?.Value ?? 30f,
                    ["knife_step9_assassin_heart_cooldown"]          = Knife_Config.KnifeAssassinHeartCooldown?.Value ?? 60f,
                    ["knife_step9_assassin_heart_teleport_range"]    = Knife_Config.KnifeAssassinHeartTeleportRange?.Value ?? 7f,
                    ["knife_step9_assassin_heart_teleport_behind"]   = Knife_Config.KnifeAssassinHeartTeleportBehind?.Value ?? 1f,
                    ["knife_step9_assassin_heart_stun_duration"]     = Knife_Config.KnifeAssassinHeartStunDuration?.Value ?? 1f,
                    ["knife_step9_assassin_heart_attack_count"]      = Knife_Config.KnifeAssassinHeartAttackCount?.Value ?? 3f,
                    ["knife_step9_assassin_heart_attack_interval"]   = Knife_Config.KnifeAssassinHeartAttackInterval?.Value ?? 0.3f,
                    ["knife_step10_stamina_cost"]                    = Knife_Config.KnifeStackExplosionStaminaCost?.Value ?? 15f,
                    ["knife_step10_cooldown"]                        = Knife_Config.KnifeStackExplosionCooldown?.Value ?? 45f,
                    ["knife_step10_damage_percent"]                  = Knife_Config.KnifeStackExplosionDamagePercent?.Value ?? 60f,
                    ["knife_step10_max_stacks"]                      = Knife_Config.KnifeStackExplosionMaxStacks?.Value ?? 7f,
                    ["knife_step10_stack_duration"]                  = Knife_Config.KnifeStackExplosionStackDuration?.Value ?? 4f,
                    ["knife_step10_buff_duration"]                   = Knife_Config.KnifeStackExplosionBuffDuration?.Value ?? 12f,
                    ["knife_step10_aoe_percent"]                     = Knife_Config.KnifeStackExplosionAoePercent?.Value ?? 45f,

                    // ══════════════════════════════════════════════
                    // Sword Tree
                    // ══════════════════════════════════════════════
                    ["Sword_Expert_RequiredPoints"]                  = Sword_Config.SwordExpertRequiredPoints?.Value ?? 2f,
                    ["Sword_Expert_DamageBonus"]                     = Sword_Config.SwordExpertDamageBonus?.Value ?? 10f,
                    ["sword_expert_damage"]                          = Sword_Config.SwordExpertDamageBonus?.Value ?? 10f,
                    ["Sword_Step1_RequiredPoints"]                   = Sword_Config.SwordStep1FastSlashRequiredPoints?.Value ?? 2f,
                    ["Sword_Step1_Counter_RequiredPoints"]           = Sword_Config.SwordStep1CounterRequiredPoints?.Value ?? 3f,
                    ["Sword_Step1_Counter_Duration"]                 = Sword_Config.SwordStep1CounterDuration?.Value ?? 5f,
                    ["Sword_Step1_Counter_DefenseBonus"]             = Sword_Config.SwordStep1CounterDefenseBonus?.Value ?? 30f,
                    ["Sword_Step1_FastSlash_Speed"]                  = Sword_Config.SwordStep1FastSlashSpeed?.Value ?? 10f,
                    ["Sword_Step2_RequiredPoints"]                   = Sword_Config.SwordStep2ComboSlashRequiredPoints?.Value ?? 1f,
                    ["Sword_Step2_ComboSlash_Bonus"]                 = Sword_Config.SwordStep2ComboSlashBonus?.Value ?? 15f,
                    ["Sword_Step2_ComboSlash_Duration"]              = Sword_Config.SwordStep2ComboSlashDuration?.Value ?? 5f,
                    ["Sword_Step3_RequiredPoints"]                   = Sword_Config.SwordStep3RiposteRequiredPoints?.Value ?? 1f,
                    ["Sword_Step3_Riposte_DamageBonus"]              = Sword_Config.SwordStep3RiposteDamageBonus?.Value ?? 5f,
                    ["Sword_Step3_AllInOne_RequiredPoints"]          = Sword_Config.SwordStep3AllInOneRequiredPoints?.Value ?? 2f,
                    ["Sword_Step3_AllInOne_AttackBonus"]             = Sword_Config.SwordStep3AllInOneAttackBonus?.Value ?? 10f,
                    ["Sword_Step3_AllInOne_DefenseBonus"]            = Sword_Config.SwordStep3AllInOneDefenseBonus?.Value ?? 15f,
                    ["Sword_Step4_RequiredPoints"]                   = Sword_Config.SwordStep4TrueDuelRequiredPoints?.Value ?? 3f,
                    ["Sword_Step4_TrueDuel_Speed"]                   = Sword_Config.SwordStep4TrueDuelSpeed?.Value ?? 15f,
                    ["Sword_Step5_RequiredPoints"]                   = Sword_Config.SwordStep5DefenseSwitchRequiredPoints?.Value ?? 3f,
                    ["ParryRush_Duration"]                           = Sword_Config.ParryRushDuration?.Value ?? 30f,
                    ["ParryRush_BlockPowerRatio"]                    = Sword_Config.ParryRushBlockPowerRatio?.Value ?? 50f,
                    ["ParryRush_PushDistance"]                       = Sword_Config.ParryRushPushDistance?.Value ?? 4f,
                    ["ParryRush_StaminaCost"]                        = Sword_Config.ParryRushStaminaCost?.Value ?? 10f,
                    ["ParryRush_Cooldown"]                           = Sword_Config.ParryRushCooldown?.Value ?? 60f,
                    ["Sword_Step6_RequiredPoints"]                   = Sword_Config.RushSlashRequiredPoints?.Value ?? 3f,
                    ["Rush_Slash_1st_DamageRatio"]                   = Sword_Config.RushSlash1stDamageRatio?.Value ?? 70f,
                    ["Rush_Slash_2nd_DamageRatio"]                   = Sword_Config.RushSlash2ndDamageRatio?.Value ?? 80f,
                    ["Rush_Slash_3rd_DamageRatio"]                   = Sword_Config.RushSlash3rdDamageRatio?.Value ?? 90f,
                    ["Rush_Slash_InitialDistance"]                   = Sword_Config.RushSlashInitialDistance?.Value ?? 5f,
                    ["Rush_Slash_SideDistance"]                      = Sword_Config.RushSlashSideDistance?.Value ?? 3f,
                    ["Rush_Slash_StaminaCost"]                       = Sword_Config.RushSlashStaminaCost?.Value ?? 30f,
                    ["Rush_Slash_Cooldown"]                          = Sword_Config.RushSlashCooldown?.Value ?? 25f,
                    ["Rush_Slash_MoveSpeed"]                         = Sword_Config.RushSlashMoveSpeed?.Value ?? 20f,
                    ["Rush_Slash_AttackSpeedBonus"]                  = Sword_Config.RushSlashAttackSpeedBonus?.Value ?? 220f,
                    ["Rush_Slash_PathWidth"]                         = Sword_Config.RushSlashPathWidth?.Value ?? 1.5f,

                    // ══════════════════════════════════════════════
                    // Staff Tree  (ConfigEntry는 private → *Value 래퍼 사용)
                    // ══════════════════════════════════════════════
                    ["staff_tier0_expert_damage"]                    = Staff_Config.StaffExpertDamageValue,
                    ["staff_tier0_expert_rp"]                        = Staff_Config.StaffExpertRequiredPointsValue,
                    ["staff_tier1_focus_eitr"]                       = Staff_Config.StaffFocusEitrReductionValue,
                    ["staff_tier1_focus_rp"]                         = Staff_Config.StaffFocusRequiredPointsValue,
                    ["staff_tier1_flow_eitr"]                        = Staff_Config.StaffStreamEitrBonusValue,
                    ["staff_tier1_flow_rp"]                          = Staff_Config.StaffStreamRequiredPointsValue,
                    ["staff_tier2_amp_chance"]                       = Staff_Config.StaffAmpChanceValue,
                    ["staff_tier2_amp_damage"]                       = Staff_Config.StaffAmpDamageValue,
                    ["staff_tier2_amp_eitr"]                         = Staff_Config.StaffAmpEitrCostIncreaseValue,
                    ["staff_tier2_amp_rp"]                           = Staff_Config.StaffAmpRequiredPointsValue,
                    ["staff_tier3_frost_damage"]                     = Staff_Config.StaffFrostDamageBonusValue,
                    ["staff_tier3_frost_rp"]                         = Staff_Config.StaffFrostRequiredPointsValue,
                    ["staff_tier3_fire_damage"]                      = Staff_Config.StaffFireDamageBonusValue,
                    ["staff_tier3_fire_rp"]                          = Staff_Config.StaffFireRequiredPointsValue,
                    ["staff_tier3_lightning_damage"]                 = Staff_Config.StaffLightningDamageBonusValue,
                    ["staff_tier3_lightning_rp"]                     = Staff_Config.StaffLightningRequiredPointsValue,
                    ["staff_tier4_luck_chance"]                      = Staff_Config.StaffLuckManaChanceValue,
                    ["staff_tier4_luck_rp"]                          = Staff_Config.StaffLuckManaRequiredPointsValue,
                    ["staff_tier5_dualcast_count"]                   = Staff_Config.StaffDoubleCastProjectileCountValue,
                    ["staff_tier5_dualcast_damage"]                  = Staff_Config.StaffDoubleCastDamagePercentValue,
                    ["staff_tier5_dualcast_eitr"]                    = Staff_Config.StaffDoubleCastEitrCostValue,
                    ["staff_tier5_dualcast_cd"]                      = Staff_Config.StaffDoubleCastCooldownValue,
                    ["staff_tier5_dualcast_rp"]                      = Staff_Config.StaffDoubleCastRequiredPointsValue,
                    ["staff_tier5_fancast_radius"]                   = Staff_Config.StaffFanCastRadiusValue,
                    ["staff_tier5_fancast_height"]                   = Staff_Config.StaffFanCastHeightValue,
                    ["staff_tier5_fancast_hover"]                    = Staff_Config.StaffFanCastHoverTimeValue,
                    ["staff_tier5_fancast_gap"]                      = Staff_Config.StaffFanCastLaunchGapValue,
                    ["staff_tier5_heal_cd"]                          = Staff_Config.StaffHealCooldownValue,
                    ["staff_tier5_heal_eitr"]                        = Staff_Config.StaffHealEitrCostValue,
                    ["staff_tier5_heal_percent"]                     = Staff_Config.StaffHealPercentageValue,
                    ["staff_tier5_heal_range"]                       = Staff_Config.StaffHealRangeValue,
                    ["staff_tier5_heal_rp"]                          = Staff_Config.StaffHealRequiredPointsValue,

                    // ══════════════════════════════════════════════
                    // Polearm Tree
                    // ══════════════════════════════════════════════
                    ["polearm_expert_required_points"]               = Polearm_Config.PolearmExpertRequiredPoints?.Value ?? 2f,
                    ["polearm_step1_required_points"]                = Polearm_Config.PolearmSpinWheelRequiredPoints?.Value ?? 2f,
                    ["polearm_step2a_required_points"]               = Polearm_Config.PolearmPolearmBoostRequiredPoints?.Value ?? 2f,
                    ["polearm_step2b_required_points"]               = Polearm_Config.PolearmHeroStrikeRequiredPoints?.Value ?? 2f,
                    ["polearm_step3_required_points"]                = Polearm_Config.PolearmAreaComboRequiredPoints?.Value ?? 2f,
                    ["polearm_step4a_required_points"]               = Polearm_Config.PolearmGroundWheelRequiredPoints?.Value ?? 2f,
                    ["polearm_step4b_required_points"]               = Polearm_Config.PolearmMoonSlashRequiredPoints?.Value ?? 2f,
                    ["polearm_suppress_required_points"]             = Polearm_Config.PolearmSuppressRequiredPoints?.Value ?? 3f,
                    ["polearm_king_required_points"]                 = Polearm_Config.PolearmKingRequiredPoints?.Value ?? 3f,
                    ["polearm_whirlwind_required_points"]            = Polearm_Config.PolearmWhirlwindRequiredPoints?.Value ?? 3f,
                    ["polearm_expert_range_bonus"]                   = Polearm_Config.PolearmExpertRangeBonus?.Value ?? 1f,
                    ["polearm_step1_spin_wheel_damage"]              = Polearm_Config.PolearmStep1SpinWheelDamage?.Value ?? 1f,
                    ["polearm_step1_suppress_damage"]                = Polearm_Config.PolearmStep1SuppressDamage?.Value ?? 1f,
                    ["polearm_step2_hero_knockback_chance"]          = Polearm_Config.PolearmStep2HeroKnockbackChance?.Value ?? 30f,
                    ["polearm_step3_area_combo_bonus"]               = Polearm_Config.PolearmStep3AreaComboBonus?.Value ?? 10f,
                    ["polearm_step3_area_combo_duration"]            = Polearm_Config.PolearmStep3AreaComboDuration?.Value ?? 5f,
                    ["polearm_step3_stormslash_explosion"]           = Polearm_Config.PolearmStep3StormSlashExplosion?.Value ?? 1f,
                    ["polearm_step4_moon_range_bonus"]               = Polearm_Config.PolearmStep4MoonRangeBonus?.Value ?? 1f,
                    ["polearm_step4_moon_stamina_reduction"]         = Polearm_Config.PolearmStep4MoonStaminaReduction?.Value ?? 10f,
                    ["polearm_step4_charge_damage"]                  = Polearm_Config.PolearmStep4ChargeDamageBonus?.Value ?? 1f,
                    ["polearm_pierce_charge_dash_distance"]          = Polearm_Config.PolearmPierceChargeDashDistance?.Value ?? 10f,
                    ["polearm_pierce_charge_primary_damage"]         = Polearm_Config.PolearmPierceChargePrimaryDamage?.Value ?? 1f,
                    ["polearm_pierce_charge_aoe_damage"]             = Polearm_Config.PolearmPierceChargeAoeDamage?.Value ?? 1f,
                    ["polearm_pierce_charge_aoe_angle"]              = Polearm_Config.PolearmPierceChargeAoeAngle?.Value ?? 60f,
                    ["polearm_pierce_charge_aoe_radius"]             = Polearm_Config.PolearmPierceChargeAoeRadius?.Value ?? 5f,
                    ["polearm_pierce_charge_knockback_distance"]     = Polearm_Config.PolearmPierceChargeKnockbackDistance?.Value ?? 5f,
                    ["polearm_pierce_charge_stamina_cost"]           = Polearm_Config.PolearmPierceChargeStaminaCost?.Value ?? 30f,
                    ["polearm_pierce_charge_cooldown"]               = Polearm_Config.PolearmPierceChargeCooldown?.Value ?? 25f,
                    ["polearm_whirlwind_damage_percent"]             = Polearm_Config.PolearmWhirlwindDamagePercent?.Value ?? 50f,
                    ["polearm_whirlwind_stamina_per_sec"]            = Polearm_Config.PolearmWhirlwindStaminaPerSec?.Value ?? 5f,
                    ["polearm_whirlwind_move_speed"]                 = Polearm_Config.PolearmWhirlwindMoveSpeed?.Value ?? 5f,
                    ["polearm_whirlwind_attack_interval"]            = Polearm_Config.PolearmWhirlwindAttackInterval?.Value ?? 0.5f,
                    ["polearm_whirlwind_vfx_interval"]               = Polearm_Config.PolearmWhirlwindVfxInterval?.Value ?? 0.25f,
                    ["polearm_whirlwind_cooldown"]                   = Polearm_Config.PolearmWhirlwindCooldown?.Value ?? 30f,
                    ["polearm_whirlwind_max_duration"]               = Polearm_Config.PolearmWhirlwindMaxDuration?.Value ?? 8f,

                    // ══════════════════════════════════════════════
                    // Archer Job
                    // ══════════════════════════════════════════════
                    ["Archer_MultiShot_ArrowCount"]                  = Archer_Config.ArcherMultiShotArrowCount?.Value ?? 3f,
                    ["Archer_MultiShot_ArrowConsumption"]            = Archer_Config.ArcherMultiShotArrowConsumption?.Value ?? 3f,
                    ["Archer_MultiShot_DamagePercent"]               = Archer_Config.ArcherMultiShotDamagePercent?.Value ?? 60f,
                    ["Archer_MultiShot_Cooldown"]                    = Archer_Config.ArcherMultiShotCooldown?.Value ?? 20f,
                    ["Archer_MultiShot_Charges"]                     = Archer_Config.ArcherMultiShotCharges?.Value ?? 1f,
                    ["Archer_MultiShot_StaminaCost"]                 = Archer_Config.ArcherMultiShotStaminaCost?.Value ?? 20f,
                    ["Archer_JumpHeightBonus"]                       = Archer_Config.ArcherJumpHeightBonus?.Value ?? 1.2f,
                    ["Archer_FallDamageReduction"]                   = Archer_Config.ArcherFallDamageReduction?.Value ?? 30f,
                    ["Archer_Lv2_JumpHeightBonus"]                   = Archer_Config.ArcherLv2JumpHeightBonus?.Value ?? 1.3f,
                    ["Archer_Lv3_JumpHeightBonus"]                   = Archer_Config.ArcherLv3JumpHeightBonus?.Value ?? 1.4f,
                    ["Archer_Lv4_JumpHeightBonus"]                   = Archer_Config.ArcherLv4JumpHeightBonus?.Value ?? 1.5f,
                    ["Archer_Lv5_JumpHeightBonus"]                   = Archer_Config.ArcherLv5JumpHeightBonus?.Value ?? 1.6f,
                    ["Archer_Lv3_FallDamageReduction"]               = Archer_Config.ArcherLv3FallDamageReduction?.Value ?? 50f,
                    ["Archer_Lv4_FallDamageReduction"]               = Archer_Config.ArcherLv4FallDamageReduction?.Value ?? 70f,
                    ["Archer_Lv5_FallDamageReduction"]               = Archer_Config.ArcherLv5FallDamageReduction?.Value ?? 100f,
                    ["Archer_ElementalResistPerLevel"]               = Archer_Config.ArcherElementalResistPerLevel?.Value ?? 1f,
                    ["Archer_Lv2_BonusArrows"]                       = Archer_Config.ArcherLv2BonusArrows?.Value ?? 1f,
                    ["Archer_Lv2_DamagePercent"]                     = Archer_Config.ArcherLv2DamagePercent?.Value ?? 65f,
                    ["Archer_Lv3_BonusArrows"]                       = Archer_Config.ArcherLv3BonusArrows?.Value ?? 2f,
                    ["Archer_Lv3_DamagePercent"]                     = Archer_Config.ArcherLv3DamagePercent?.Value ?? 70f,
                    ["Archer_Lv4_BonusArrows"]                       = Archer_Config.ArcherLv4BonusArrows?.Value ?? 2f,
                    ["Archer_Lv4_DamagePercent"]                     = Archer_Config.ArcherLv4DamagePercent?.Value ?? 75f,
                    ["Archer_Lv5_BonusArrows"]                       = Archer_Config.ArcherLv5BonusArrows?.Value ?? 3f,
                    ["Archer_Lv5_DamagePercent"]                     = Archer_Config.ArcherLv5DamagePercent?.Value ?? 80f,
                    ["Archer_Lv5_BonusCharges"]                      = Archer_Config.ArcherLv5BonusCharges?.Value ?? 1f,

                    // ══════════════════════════════════════════════
                    // Tanker Job
                    // ══════════════════════════════════════════════
                    ["Tanker_Taunt_Cooldown"]                        = Tanker_Config.TankerTauntCooldown?.Value ?? 60f,
                    ["Tanker_Taunt_StaminaCost"]                     = Tanker_Config.TankerTauntStaminaCost?.Value ?? 25f,
                    ["Tanker_Taunt_Range"]                           = Tanker_Config.TankerTauntRange?.Value ?? 12f,
                    ["Tanker_Taunt_Duration"]                        = Tanker_Config.TankerTauntDuration?.Value ?? 9f,
                    ["Tanker_Taunt_BossDuration"]                    = Tanker_Config.TankerTauntBossDuration?.Value ?? 1f,
                    ["Tanker_Taunt_DamageReduction"]                 = Tanker_Config.TankerTauntDamageReduction?.Value ?? 20f,
                    ["Tanker_Taunt_BuffDuration"]                    = Tanker_Config.TankerTauntBuffDuration?.Value ?? 8f,
                    ["Tanker_Taunt_EffectHeight"]                    = Tanker_Config.TankerTauntEffectHeight?.Value ?? 2f,
                    ["Tanker_Taunt_EffectScale"]                     = Tanker_Config.TankerTauntEffectScale?.Value ?? 0.8f,
                    ["Tanker_Taunt_ReflectPercent"]                  = Tanker_Config.TankerTauntReflectPercent?.Value ?? 10f,
                    ["Tanker_Passive_DamageReduction"]               = Tanker_Config.TankerPassiveDamageReduction?.Value ?? 15f,
                    ["Tanker_Hp_Bonus_Lv1"]                          = Tanker_Config.TankerHpBonusLv1?.Value ?? 25f,
                    ["Tanker_Hp_Bonus_Lv2"]                          = Tanker_Config.TankerHpBonusLv2?.Value ?? 30f,
                    ["Tanker_Hp_Bonus_Lv3"]                          = Tanker_Config.TankerHpBonusLv3?.Value ?? 35f,
                    ["Tanker_Hp_Bonus_Lv4"]                          = Tanker_Config.TankerHpBonusLv4?.Value ?? 40f,
                    ["Tanker_Hp_Bonus_Lv5"]                          = Tanker_Config.TankerHpBonusLv5?.Value ?? 50f,
                    ["Tanker_Lv2_BlockPower"]                        = Tanker_Config.TankerLv2BlockPower?.Value ?? 5f,
                    ["Tanker_Lv3_BlockPower"]                        = Tanker_Config.TankerLv3BlockPower?.Value ?? 10f,
                    ["Tanker_Lv4_BlockPower"]                        = Tanker_Config.TankerLv4BlockPower?.Value ?? 15f,
                    ["Tanker_Lv5_BlockPower"]                        = Tanker_Config.TankerLv5BlockPower?.Value ?? 20f,
                    ["Tanker_ReflectDuration_Lv1"]                   = Tanker_Config.TankerReflectDurationLv1?.Value ?? 10f,
                    ["Tanker_ReflectDuration_Lv2"]                   = Tanker_Config.TankerReflectDurationLv2?.Value ?? 12f,
                    ["Tanker_ReflectDuration_Lv3"]                   = Tanker_Config.TankerReflectDurationLv3?.Value ?? 14f,
                    ["Tanker_ReflectDuration_Lv4"]                   = Tanker_Config.TankerReflectDurationLv4?.Value ?? 16f,
                    ["Tanker_ReflectDuration_Lv5"]                   = Tanker_Config.TankerReflectDurationLv5?.Value ?? 20f,

                    // ══════════════════════════════════════════════
                    // Rogue Job
                    // ══════════════════════════════════════════════
                    ["Rogue_ShadowStrike_Cooldown"]                  = Rogue_Config.RogueShadowStrikeCooldown?.Value ?? 35f,
                    ["Rogue_ShadowStrike_StaminaCost"]               = Rogue_Config.RogueShadowStrikeStaminaCost?.Value ?? 20f,
                    ["Rogue_ShadowStrike_AttackBonus"]               = Rogue_Config.RogueShadowStrikeAttackBonus?.Value ?? 35f,
                    ["Rogue_ShadowStrike_BuffDuration"]              = Rogue_Config.RogueShadowStrikeBuffDuration?.Value ?? 8f,
                    ["Rogue_ShadowStrike_Charges"]                   = Rogue_Config.RogueShadowStrikeCharges?.Value ?? 1f,
                    ["Rogue_Lv2_Cooldown"]                           = Rogue_Config.RogueLv2Cooldown?.Value ?? 32f,
                    ["Rogue_Lv3_Cooldown"]                           = Rogue_Config.RogueLv3Cooldown?.Value ?? 30f,
                    ["Rogue_Lv4_Cooldown"]                           = Rogue_Config.RogueLv4Cooldown?.Value ?? 28f,
                    ["Rogue_Lv5_Cooldown"]                           = Rogue_Config.RogueLv5Cooldown?.Value ?? 25f,
                    ["Rogue_Lv2_AttackBonus"]                        = Rogue_Config.RogueLv2AttackBonus?.Value ?? 40f,
                    ["Rogue_Lv3_AttackBonus"]                        = Rogue_Config.RogueLv3AttackBonus?.Value ?? 45f,
                    ["Rogue_Lv4_AttackBonus"]                        = Rogue_Config.RogueLv4AttackBonus?.Value ?? 50f,
                    ["Rogue_Lv5_AttackBonus"]                        = Rogue_Config.RogueLv5AttackBonus?.Value ?? 55f,
                    ["Rogue_Lv2_BuffDuration"]                       = Rogue_Config.RogueLv2BuffDuration?.Value ?? 9f,
                    ["Rogue_Lv3_BuffDuration"]                       = Rogue_Config.RogueLv3BuffDuration?.Value ?? 10f,
                    ["Rogue_Lv4_BuffDuration"]                       = Rogue_Config.RogueLv4BuffDuration?.Value ?? 11f,
                    ["Rogue_Lv5_BuffDuration"]                       = Rogue_Config.RogueLv5BuffDuration?.Value ?? 12f,
                    ["Rogue_Poison_Range"]                           = Rogue_Config.RoguePoisonRange?.Value ?? 15f,
                    ["Rogue_Poison_InstantDamage"]                   = Rogue_Config.RoguePoisonInstantDamage?.Value ?? 20f,
                    ["Rogue_Poison_DotDamage"]                       = Rogue_Config.RoguePoisonDotDamage?.Value ?? 30f,
                    ["Rogue_Poison_DotDuration"]                     = Rogue_Config.RoguePoisonDotDuration?.Value ?? 10f,
                    ["Rogue_Poison_VFXCount"]                        = Rogue_Config.RoguePoisonVFXCount?.Value ?? 6f,
                    ["Rogue_Poison_VFXInterval"]                     = Rogue_Config.RoguePoisonVFXInterval?.Value ?? 0.5f,
                    ["Rogue_Lv2_PoisonBlasts"]                       = Rogue_Config.RogueLv2PoisonBlasts?.Value ?? 7f,
                    ["Rogue_Lv3_PoisonBlasts"]                       = Rogue_Config.RogueLv3PoisonBlasts?.Value ?? 8f,
                    ["Rogue_Lv4_PoisonBlasts"]                       = Rogue_Config.RogueLv4PoisonBlasts?.Value ?? 9f,
                    ["Rogue_Lv5_PoisonBlasts"]                       = Rogue_Config.RogueLv5PoisonBlasts?.Value ?? 10f,
                    ["Rogue_Lv2_PoisonInstant"]                      = Rogue_Config.RogueLv2PoisonInstant?.Value ?? 45f,
                    ["Rogue_Lv3_PoisonInstant"]                      = Rogue_Config.RogueLv3PoisonInstant?.Value ?? 50f,
                    ["Rogue_Lv4_PoisonInstant"]                      = Rogue_Config.RogueLv4PoisonInstant?.Value ?? 55f,
                    ["Rogue_Lv5_PoisonInstant"]                      = Rogue_Config.RogueLv5PoisonInstant?.Value ?? 60f,
                    ["Rogue_Lv2_PoisonDot"]                          = Rogue_Config.RogueLv2PoisonDot?.Value ?? 35f,
                    ["Rogue_Lv3_PoisonDot"]                          = Rogue_Config.RogueLv3PoisonDot?.Value ?? 40f,
                    ["Rogue_Lv4_PoisonDot"]                          = Rogue_Config.RogueLv4PoisonDot?.Value ?? 45f,
                    ["Rogue_Lv5_PoisonDot"]                          = Rogue_Config.RogueLv5PoisonDot?.Value ?? 50f,
                    ["Rogue_Lv5_BonusCharges"]                       = Rogue_Config.RogueLv5BonusCharges?.Value ?? 1f,
                    ["Rogue_AttackSpeed_Bonus"]                      = Rogue_Config.RogueAttackSpeedBonus?.Value ?? 7f,
                    ["Rogue_Stamina_Reduction"]                      = Rogue_Config.RogueStaminaReduction?.Value ?? 15f,
                    ["Rogue_Lv2_AttackSpeed"]                        = Rogue_Config.RogueLv2AttackSpeed?.Value ?? 9f,
                    ["Rogue_Lv3_AttackSpeed"]                        = Rogue_Config.RogueLv3AttackSpeed?.Value ?? 11f,
                    ["Rogue_Lv4_AttackSpeed"]                        = Rogue_Config.RogueLv4AttackSpeed?.Value ?? 13f,
                    ["Rogue_Lv5_AttackSpeed"]                        = Rogue_Config.RogueLv5AttackSpeed?.Value ?? 15f,
                    ["Rogue_Lv2_StaminaReduction"]                   = Rogue_Config.RogueLv2StaminaReduction?.Value ?? 17f,
                    ["Rogue_Lv3_StaminaReduction"]                   = Rogue_Config.RogueLv3StaminaReduction?.Value ?? 19f,
                    ["Rogue_Lv4_StaminaReduction"]                   = Rogue_Config.RogueLv4StaminaReduction?.Value ?? 21f,
                    ["Rogue_Lv5_StaminaReduction"]                   = Rogue_Config.RogueLv5StaminaReduction?.Value ?? 25f,
                    ["Rogue_Lv1_DodgeChance"]                        = Rogue_Config.RogueLv1DodgeChance?.Value ?? 4f,
                    ["Rogue_Lv2_DodgeChance"]                        = Rogue_Config.RogueLv2DodgeChance?.Value ?? 6f,
                    ["Rogue_Lv3_DodgeChance"]                        = Rogue_Config.RogueLv3DodgeChance?.Value ?? 8f,
                    ["Rogue_Lv4_DodgeChance"]                        = Rogue_Config.RogueLv4DodgeChance?.Value ?? 10f,
                    ["Rogue_Lv5_DodgeChance"]                        = Rogue_Config.RogueLv5DodgeChance?.Value ?? 12f,
                    ["Rogue_Lv1_MoveSpeed"]                          = Rogue_Config.RogueLv1MoveSpeed?.Value ?? 5f,
                    ["Rogue_Lv2_MoveSpeed"]                          = Rogue_Config.RogueLv2MoveSpeed?.Value ?? 7f,
                    ["Rogue_Lv3_MoveSpeed"]                          = Rogue_Config.RogueLv3MoveSpeed?.Value ?? 9f,
                    ["Rogue_Lv4_MoveSpeed"]                          = Rogue_Config.RogueLv4MoveSpeed?.Value ?? 12f,
                    ["Rogue_Lv5_MoveSpeed"]                          = Rogue_Config.RogueLv5MoveSpeed?.Value ?? 15f,

                    // ══════════════════════════════════════════════
                    // Mage Job
                    // ══════════════════════════════════════════════
                    ["Mage_AOE_Range"]                               = Mage_Config.MageAOERange?.Value ?? 8f,
                    ["Mage_Eitr_Cost"]                               = Mage_Config.MageEitrCost?.Value ?? 20f,
                    ["Mage_Fire_Rain_Radius"]                        = Mage_Config.MageFireRainRadius?.Value ?? 10f,
                    ["Mage_Fire_Rain_Impact_Radius"]                 = Mage_Config.MageFireRainImpactRadius?.Value ?? 2f,
                    ["Mage_Fire_Rain_Projectile_Count"]              = Mage_Config.MageFireRainProjectileCount?.Value ?? 20f,
                    ["Mage_Lv1_Cooldown"]                            = Mage_Config.MageCooldown_Lv1?.Value ?? 45f,
                    ["Mage_Lv2_Cooldown"]                            = Mage_Config.MageCooldown_Lv2?.Value ?? 45f,
                    ["Mage_Lv3_Cooldown"]                            = Mage_Config.MageCooldown_Lv3?.Value ?? 45f,
                    ["Mage_Lv4_Cooldown"]                            = Mage_Config.MageCooldown_Lv4?.Value ?? 45f,
                    ["Mage_Lv5_Cooldown"]                            = Mage_Config.MageCooldown_Lv5?.Value ?? 45f,
                    ["Mage_Lv1_Elemental_Resistance"]                = Mage_Config.MageElementalResistance_Lv1?.Value ?? 5f,
                    ["Mage_Lv2_Elemental_Resistance"]                = Mage_Config.MageElementalResistance_Lv2?.Value ?? 7f,
                    ["Mage_Lv3_Elemental_Resistance"]                = Mage_Config.MageElementalResistance_Lv3?.Value ?? 9f,
                    ["Mage_Lv4_Elemental_Resistance"]                = Mage_Config.MageElementalResistance_Lv4?.Value ?? 12f,
                    ["Mage_Lv5_Elemental_Resistance"]                = Mage_Config.MageElementalResistance_Lv5?.Value ?? 15f,
                    ["Mage_Lv1_Damage_Multiplier"]                   = Mage_Config.MageDamageMultiplier_Lv1?.Value ?? 22f,
                    ["Mage_Lv2_Damage_Multiplier"]                   = Mage_Config.MageDamageMultiplier_Lv2?.Value ?? 24f,
                    ["Mage_Lv3_Damage_Multiplier"]                   = Mage_Config.MageDamageMultiplier_Lv3?.Value ?? 26f,
                    ["Mage_Lv4_Damage_Multiplier"]                   = Mage_Config.MageDamageMultiplier_Lv4?.Value ?? 28f,
                    ["Mage_Lv5_Damage_Multiplier"]                   = Mage_Config.MageDamageMultiplier_Lv5?.Value ?? 30f,

                    // ══════════════════════════════════════════════
                    // Berserker Job
                    // ══════════════════════════════════════════════
                    ["Berserker_Rage_Cooldown"]                      = Berserker_Config.BerserkerRageCooldown?.Value ?? 45f,
                    ["Berserker_Rage_StaminaCost"]                   = Berserker_Config.BerserkerRageStaminaCost?.Value ?? 20f,
                    ["Berserker_Rage_Duration"]                      = Berserker_Config.BerserkerRageDuration?.Value ?? 20f,
                    ["Berserker_Rage_DamagePerHealthPercent"]        = Berserker_Config.BerserkerRageDamagePerHealthPercent?.Value ?? 2f,
                    ["Berserker_Rage_MaxDamageBonus"]                = Berserker_Config.BerserkerRageMaxDamageBonus?.Value ?? 200f,
                    ["Berserker_Rage_HealthThreshold"]               = Berserker_Config.BerserkerRageHealthThreshold?.Value ?? 100f,
                    ["Berserker_Passive_HealthThreshold"]            = Berserker_Config.BerserkerPassiveHealthThreshold?.Value ?? 10f,
                    ["Berserker_Passive_InvincibilityDuration"]      = Berserker_Config.BerserkerPassiveInvincibilityDuration?.Value ?? 8f,
                    ["Berserker_Passive_Cooldown"]                   = Berserker_Config.BerserkerPassiveCooldown?.Value ?? 600f,
                    ["Berserker_Passive_HealthBonus"]                = Berserker_Config.BerserkerPassiveHealthBonus?.Value ?? 100f,
                    ["Berserker_Lv2_CooldownReduction"]              = Berserker_Config.BerserkerLv2CooldownReduction?.Value ?? 5f,
                    ["Berserker_Lv3_RageDamageReduction"]            = Berserker_Config.BerserkerLv3RageDamageReduction?.Value ?? 15f,
                    ["Berserker_Lv4_LowHpAttackBonus"]              = Berserker_Config.BerserkerLv4LowHpAttackBonus?.Value ?? 15f,
                    ["Berserker_Lv4_LowHpAttackThreshold"]          = Berserker_Config.BerserkerLv4LowHpAttackThreshold?.Value ?? 50f,
                    ["Berserker_Lv5_PassiveCooldownReduction"]       = Berserker_Config.BerserkerLv5PassiveCooldownReduction?.Value ?? 120f,
                    ["Berserker_Lv5_InvincibilityBonus"]             = Berserker_Config.BerserkerLv5InvincibilityBonus?.Value ?? 2f,

                    // ══════════════════════════════════════════════
                    // Producer Job
                    // ══════════════════════════════════════════════
                    ["Producer_Buff_Cooldown"]                       = Producer_Config.ProducerBuff_Cooldown?.Value ?? 60f,
                    ["Producer_Buff_Duration"]                       = Producer_Config.ProducerBuff_Duration?.Value ?? 30f,
                    ["Producer_Buff_Range"]                          = Producer_Config.ProducerBuff_Range?.Value ?? 10f,
                    ["Producer_Buff_AttackBonus"]                    = Producer_Config.ProducerBuff_AttackBonus?.Value ?? 10f,
                    ["Producer_Buff_MaxHealthBonus"]                 = Producer_Config.ProducerBuff_MaxHealthBonus?.Value ?? 20f,
                    ["Producer_Buff_StaminaCost"]                    = Producer_Config.ProducerBuff_StaminaCost?.Value ?? 20f,
                    ["Producer_FarmGrid_Lv1"]                        = Producer_Config.ProducerFarmGrid_Lv1?.Value ?? 3f,
                    ["Producer_FarmGrid_Lv2"]                        = Producer_Config.ProducerFarmGrid_Lv2?.Value ?? 4f,
                    ["Producer_FarmGrid_Lv3"]                        = Producer_Config.ProducerFarmGrid_Lv3?.Value ?? 5f,
                    ["Producer_FarmGrid_Lv4"]                        = Producer_Config.ProducerFarmGrid_Lv4?.Value ?? 6f,
                    ["Producer_FarmGrid_Lv5"]                        = Producer_Config.ProducerFarmGrid_Lv5?.Value ?? 7f,
                    ["Producer_Durability_Lv2"]                      = Producer_Config.ProducerDurability_Lv2?.Value ?? 10f,
                    ["Producer_Durability_Lv3"]                      = Producer_Config.ProducerDurability_Lv3?.Value ?? 20f,
                    ["Producer_Durability_Lv4"]                      = Producer_Config.ProducerDurability_Lv4?.Value ?? 30f,
                    ["Producer_Durability_Lv5"]                      = Producer_Config.ProducerDurability_Lv5?.Value ?? 50f,
                    ["Producer_MaterialReduction_Lv2"]               = Producer_Config.ProducerMaterialReduction_Lv2?.Value ?? 5f,
                    ["Producer_MaterialReduction_Lv3"]               = Producer_Config.ProducerMaterialReduction_Lv3?.Value ?? 10f,
                    ["Producer_MaterialReduction_Lv4"]               = Producer_Config.ProducerMaterialReduction_Lv4?.Value ?? 15f,
                    ["Producer_MaterialReduction_Lv5"]               = Producer_Config.ProducerMaterialReduction_Lv5?.Value ?? 20f,
                    ["Producer_EnchantChance_Lv1"]                   = Producer_Config.ProducerEnchantChance_Lv1?.Value ?? 5f,
                    ["Producer_EnchantChance_Lv2"]                   = Producer_Config.ProducerEnchantChance_Lv2?.Value ?? 8f,
                    ["Producer_EnchantChance_Lv3"]                   = Producer_Config.ProducerEnchantChance_Lv3?.Value ?? 12f,
                    ["Producer_EnchantChance_Lv4"]                   = Producer_Config.ProducerEnchantChance_Lv4?.Value ?? 16f,
                    ["Producer_EnchantChance_Lv5"]                   = Producer_Config.ProducerEnchantChance_Lv5?.Value ?? 20f,

                    // ══════════════════════════════════════════════
                    // Production Tree
                    // ══════════════════════════════════════════════
                    ["production_root_wood_chance"]                  = Production_Config.ProductionRootWoodBonusChance?.Value ?? 50f,
                    ["novice_worker_wood_chance"]                     = Production_Config.NoviceWorkerWoodBonusChance?.Value ?? 25f,
                    ["woodcutting_lv2_chance"]                       = Production_Config.WoodcuttingLv2BonusChance?.Value ?? 25f,
                    ["gathering_lv2_chance"]                         = Production_Config.GatheringLv2BonusChance?.Value ?? 25f,
                    ["mining_lv2_chance"]                            = Production_Config.MiningLv2BonusChance?.Value ?? 25f,
                    ["crafting_lv2_upgrade_chance"]                  = Production_Config.CraftingLv2UpgradeChance?.Value ?? 15f,
                    ["crafting_lv2_durability"]                      = Production_Config.CraftingLv2DurabilityBonus?.Value ?? 15f,
                    ["woodcutting_lv3_chance"]                       = Production_Config.WoodcuttingLv3BonusChance?.Value ?? 35f,
                    ["gathering_lv3_chance"]                         = Production_Config.GatheringLv3BonusChance?.Value ?? 35f,
                    ["mining_lv3_chance"]                            = Production_Config.MiningLv3BonusChance?.Value ?? 25f,
                    ["crafting_lv3_upgrade_chance"]                  = Production_Config.CraftingLv3UpgradeChance?.Value ?? 15f,
                    ["crafting_lv3_durability"]                      = Production_Config.CraftingLv3DurabilityBonus?.Value ?? 15f,
                    ["woodcutting_lv4_chance"]                       = Production_Config.WoodcuttingLv4BonusChance?.Value ?? 45f,
                    ["gathering_lv4_chance"]                         = Production_Config.GatheringLv4BonusChance?.Value ?? 40f,
                    ["mining_lv4_chance"]                            = Production_Config.MiningLv4BonusChance?.Value ?? 25f,
                    ["crafting_lv4_upgrade_chance"]                  = Production_Config.CraftingLv4UpgradeChance?.Value ?? 15f,
                    ["crafting_lv4_durability"]                      = Production_Config.CraftingLv4DurabilityBonus?.Value ?? 15f,

                    // ══════════════════════════════════════════════
                    // Captain Level Config
                    // ══════════════════════════════════════════════
                    ["CaptainLevel_MaxLevel"]                        = CaptainLevelConfig.MaxLevel?.Value ?? 100f,
                    ["CaptainLevel_LevelExp"]                        = CaptainLevelConfig.LevelExp?.Value ?? 300f,
                    ["CaptainLevel_MultiNextLevel"]                  = CaptainLevelConfig.MultiNextLevel?.Value ?? 1.05f,
                    ["CaptainLevel_RateExp"]                         = CaptainLevelConfig.RateExp?.Value ?? 1.0f,
                    ["CaptainLevel_MaxLevelExp"]                     = CaptainLevelConfig.MaxLevelExp?.Value ?? 10f,
                    ["CaptainLevel_MinLevelExp"]                     = CaptainLevelConfig.MinLevelExp?.Value ?? 10f,
                    ["CaptainLevel_ExpForLvlMonster"]                = CaptainLevelConfig.ExpForLvlMonster?.Value ?? 1.5f,
                    ["CaptainLevel_SkillPointsPerLevel"]             = CaptainLevelConfig.SkillPointsPerLevel?.Value ?? 2f,
                    ["CaptainLevel_PointsRequired"]                  = CaptainLevelConfig.PointsRequiredPerLevel?.Value ?? 2f,
                };

                var configString = SerializeConfigData(configData);
                if (ZNet.instance != null && ZRoutedRpc.instance != null)
                {
                    ZRoutedRpc.instance.InvokeRoutedRPC(ZRoutedRpc.Everybody, "CaptainSkillTree.SkillTreeMod_ConfigSync", configString);
                    Plugin.Log.LogInfo($"[SkillTreeConfig] 서버 설정을 모든 클라이언트에게 전송 ({configData.Count}개 항목)");
                }
                else
                {
                    Plugin.Log.LogDebug("[SkillTreeConfig] ZNet 또는 ZRoutedRpc가 아직 초기화되지 않아 Config 전송을 건너뜁니다.");
                }
            }
            catch (Exception ex)
            {
                Plugin.Log.LogError($"[SkillTreeConfig] BroadcastConfigToClients 실패: {ex.Message}\n{ex.StackTrace}");
            }
        }
    }
}
